{
  "branches": [
    {
      "name": "main"
    },
    {
      "name": "dev",
      "prerelease": "beta",
      "channel": "beta"
    }
  ],
  "tagFormat": "v${version}",
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits"
      }
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits"
      }
    ],
    [
      "@semantic-release/npm",
    ],
    [
      "@semantic-release/github"
    ],
    [
      "@semantic-release/git"
    ],
    [
      "@semantic-release/exec",
      {
        "prepare": "pnpm run build"
      }
    ]
  ]
}