// This file is auto-generated by @hey-api/openapi-ts

export const EconomicNewsEntrySchema = {
  properties: {
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp of the event',
    },
    country: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Country',
      description: 'The country of the event',
    },
    event: {
      type: 'string',
      title: 'Event',
      description: 'The event name',
    },
    currency: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Currency',
      description: 'The currency of the event',
    },
    previous: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous',
      description: 'The previous value',
    },
    estimate: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Estimate',
      description: 'The forecasted value',
    },
    actual: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Actual',
      description: 'The actual value',
    },
    change: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Change',
      description: 'The change in value',
    },
    impact: {
      anyOf: [
        {
          type: 'string',
          enum: ['Low', 'Medium', 'High'],
        },
        {
          type: 'null',
        },
      ],
      title: 'Impact',
      description: 'The impact value',
    },
    changePercentage: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Changepercentage',
      description: 'The change percentage',
    },
  },
  type: 'object',
  required: ['timestamp', 'event'],
  title: 'EconomicNewsEntry',
  description:
    'Economic Calendar News Entry Pydantic Model. Aliases are used to match the database table columns.',
} as const;

export const ErrorResponseSchema = {
  properties: {
    detail: {
      type: 'string',
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'ErrorResponse',
  description: 'Error response schema.',
} as const;

export const FnGEntrySchema = {
  properties: {
    value: {
      type: 'integer',
      title: 'Value',
      description: 'The value of the fear and greed index',
    },
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp of the data point',
    },
  },
  type: 'object',
  required: ['value', 'timestamp'],
  title: 'FnGEntry',
  description: 'Fear and Greed Index Data Point Pydantic Model',
} as const;

export const HistogramBinDataSchema = {
  properties: {
    bin_centers: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Bin Centers',
      description: 'Center values for histogram bins',
    },
    bin_edges: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Bin Edges',
      description: 'Edge values defining histogram bins',
    },
    counts: {
      items: {
        type: 'integer',
      },
      type: 'array',
      title: 'Counts',
      description: 'Count of occurrences in each bin',
    },
    density: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Density',
      description: 'Probability density for each bin',
    },
  },
  type: 'object',
  required: ['bin_centers', 'bin_edges', 'counts', 'density'],
  title: 'HistogramBinData',
  description: 'Histogram bin data for a specific metric (close/high/low)',
} as const;

export const HistogramData_InputSchema = {
  properties: {
    query_info: {
      $ref: '#/components/schemas/QueryInfo',
      description: 'Query metadata',
    },
    horizons: {
      additionalProperties: {
        $ref: '#/components/schemas/HorizonHistogramData',
      },
      type: 'object',
      title: 'Horizons',
      description: 'Histogram data for each horizon (1-15)',
    },
  },
  type: 'object',
  required: ['query_info', 'horizons'],
  title: 'HistogramData',
  description: 'Complete histogram data structure',
} as const;

export const HistogramData_OutputSchema = {
  properties: {
    query_info: {
      $ref: '#/components/schemas/QueryInfo',
      description: 'Query metadata',
    },
    horizons: {
      additionalProperties: {
        $ref: '#/components/schemas/HorizonHistogramData',
      },
      type: 'object',
      title: 'Horizons',
      description: 'Histogram data for each horizon (1-15)',
    },
  },
  type: 'object',
  required: ['query_info', 'horizons'],
  title: 'HistogramData',
  description: 'Complete histogram data structure',
} as const;

export const HistogramProbabilitiesSchema = {
  properties: {
    up: {
      type: 'number',
      title: 'Up',
      description: 'Probability of upward movement',
    },
    down: {
      type: 'number',
      title: 'Down',
      description: 'Probability of downward movement',
    },
    mean: {
      type: 'number',
      title: 'Mean',
      description: 'Mean relative change',
    },
    quantiles: {
      additionalProperties: {
        type: 'number',
      },
      type: 'object',
      title: 'Quantiles',
      description: 'Quantile values (q05, q50, q95)',
    },
  },
  type: 'object',
  required: ['up', 'down', 'mean', 'quantiles'],
  title: 'HistogramProbabilities',
  description: 'Probability data for close price movements',
} as const;

export const HorizonHistogramDataSchema = {
  properties: {
    close: {
      $ref: '#/components/schemas/HistogramBinData',
      description: 'Close price histogram',
    },
    high: {
      $ref: '#/components/schemas/HistogramBinData',
      description: 'High price histogram',
    },
    low: {
      $ref: '#/components/schemas/HistogramBinData',
      description: 'Low price histogram',
    },
    probabilities: {
      $ref: '#/components/schemas/HistogramProbabilities',
      description: 'Probability analysis for close prices',
    },
  },
  type: 'object',
  required: ['close', 'high', 'low', 'probabilities'],
  title: 'HorizonHistogramData',
  description: 'Histogram data for a single horizon',
} as const;

export const PaginatedResponse_EconomicNewsEntry_Schema = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/EconomicNewsEntry',
      },
      type: 'array',
      title: 'Data',
    },
    total: {
      type: 'integer',
      title: 'Total',
      description: 'The total number of items',
    },
    page: {
      type: 'integer',
      title: 'Page',
      description: 'The current page number',
    },
    page_size: {
      type: 'integer',
      title: 'Page Size',
      description: 'The number of items per page',
    },
    prev: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Prev',
      description: 'The previous page number',
    },
    next: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next',
      description: 'The next page number',
    },
    last: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Last',
      description: 'The last page number',
    },
  },
  type: 'object',
  required: ['data', 'total', 'page', 'page_size'],
  title: 'PaginatedResponse[EconomicNewsEntry]',
} as const;

export const PolymarketHistogramSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
      description: 'The database ID of the histogram',
    },
    symbol: {
      type: 'string',
      title: 'Symbol',
      description: 'The symbol',
    },
    interval: {
      type: 'string',
      title: 'Interval',
      description: 'The interval',
    },
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp of the histogram',
    },
    histogram: {
      $ref: '#/components/schemas/HistogramData-Output',
      description: 'The histogram data',
    },
    created_at: {
      type: 'integer',
      title: 'Created At',
      description: 'When the histogram was stored',
    },
  },
  type: 'object',
  required: [
    'id',
    'symbol',
    'interval',
    'timestamp',
    'histogram',
    'created_at',
  ],
  title: 'PolymarketHistogram',
  description: 'Polymarket Histogram response model',
} as const;

export const PolymarketHistogramUpdateSchema = {
  properties: {
    symbol: {
      type: 'string',
      title: 'Symbol',
      description: 'The symbol (e.g., BTC, ETH, XRP, SOL)',
      examples: ['BTC'],
    },
    interval: {
      type: 'string',
      enum: ['15min', '1h', '4h'],
      title: 'Interval',
      description: 'The interval for the histogram',
      examples: ['15min'],
    },
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp when histogram was generated',
    },
    histogram: {
      $ref: '#/components/schemas/HistogramData-Input',
      description: 'The complete histogram data',
    },
  },
  type: 'object',
  required: ['symbol', 'interval', 'timestamp', 'histogram'],
  title: 'PolymarketHistogramUpdate',
  description: 'Polymarket Histogram Update model for receiving histogram data',
} as const;

export const PolymarketPredictionSchema = {
  properties: {
    symbol: {
      type: 'string',
      title: 'Symbol',
      description: 'The symbol of the prediction',
    },
    value: {
      type: 'number',
      maximum: 10,
      minimum: -10,
      title: 'Value',
      description: 'The prediction value, constrained between -10 and 10',
    },
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp of the prediction in seconds since epoch',
    },
    interval: {
      type: 'string',
      enum: ['15min', '1h', '4h'],
      title: 'Interval',
      description: 'The prediction interval',
    },
  },
  type: 'object',
  required: ['symbol', 'value', 'timestamp', 'interval'],
  title: 'PolymarketPrediction',
  description: 'Polymarket Prediction model',
} as const;

export const PredictionSchema = {
  properties: {
    symbol: {
      type: 'string',
      title: 'Symbol',
      description: 'The symbol of the prediction',
    },
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp of the prediction creation',
    },
    version: {
      type: 'string',
      enum: ['1.4', '1.5'],
      title: 'Version',
      description: 'The version of the AI model',
    },
    p10: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P10',
      description:
        'The 10th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p30: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P30',
      description:
        'The 30th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p50: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P50',
      description:
        'The 50th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p70: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P70',
      description:
        'The 70th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p90: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P90',
      description:
        'The 90th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    id: {
      type: 'integer',
      title: 'Id',
      description: 'The id of the prediction',
    },
    base_price: {
      type: 'number',
      title: 'Base Price',
      description: 'The base price of the prediction',
    },
    course_change: {
      type: 'number',
      title: 'Course Change',
      description: 'The course change of the prediction, derived from p50 data',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'symbol',
    'timestamp',
    'version',
    'p10',
    'p30',
    'p50',
    'p70',
    'p90',
    'id',
    'base_price',
    'course_change',
  ],
  title: 'Prediction',
  description: 'Prediction model',
} as const;

export const PredictionCreateSchema = {
  properties: {
    symbol: {
      type: 'string',
      title: 'Symbol',
      description: 'The symbol of the prediction',
    },
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The timestamp of the prediction creation',
    },
    version: {
      type: 'string',
      enum: ['1.4', '1.5'],
      title: 'Version',
      description: 'The version of the AI model',
    },
    p10: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P10',
      description:
        'The 10th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p30: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P30',
      description:
        'The 30th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p50: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P50',
      description:
        'The 50th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p70: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P70',
      description:
        'The 70th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
    p90: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'P90',
      description:
        'The 90th percentile of the prediction. List of 24 values in 15 minutes intervals.',
    },
  },
  type: 'object',
  required: [
    'symbol',
    'timestamp',
    'version',
    'p10',
    'p30',
    'p50',
    'p70',
    'p90',
  ],
  title: 'PredictionCreate',
  description: 'Prediction create model',
} as const;

export const QueryInfoSchema = {
  properties: {
    query_end: {
      type: 'integer',
      title: 'Query End',
      description: 'Query end timestamp (candle open)',
    },
    baseline_close: {
      type: 'number',
      title: 'Baseline Close',
      description: 'Baseline close price',
    },
    window_start: {
      type: 'integer',
      title: 'Window Start',
      description: 'Window start timestamp',
    },
    window_end: {
      type: 'integer',
      title: 'Window End',
      description: 'Window end timestamp',
    },
    selected_horizon: {
      type: 'integer',
      title: 'Selected Horizon',
      description: 'Selected horizon for analysis',
    },
    matches_count: {
      type: 'integer',
      title: 'Matches Count',
      description: 'Number of matching patterns found',
    },
  },
  type: 'object',
  required: [
    'query_end',
    'baseline_close',
    'window_start',
    'window_end',
    'selected_horizon',
    'matches_count',
  ],
  title: 'QueryInfo',
  description: 'Query information for histogram generation',
} as const;
