// This file is auto-generated by @hey-api/openapi-ts

export const BroadcastSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    template_preferences: {
      items: {
        prefixItems: [
          {
            type: "string",
            enum: [
              "subscription_predictions_welcome",
              "subscription_dex_signals_welcome",
              "subscription_combo_welcome",
              "new_member",
              "exchange_api_key_expiring",
              "test",
              "new_dex_ai_call",
              "new_dex_ai_call_incognito",
              "order_completion",
              "trading_agent_execution_alert",
              "otp_code",
              "subscription_expiring",
              "subscription_expired",
            ],
          },
          {
            type: "boolean",
          },
        ],
        type: "array",
        maxItems: 2,
        minItems: 2,
      },
      type: "array",
      title: "Template Preferences",
      description:
        "List of templates and whether the broadcast sends the notification for",
    },
    discord_webhook_url: {
      type: "string",
      title: "Discord Webhook Url",
      description: "Discord webhook URL for the broadcast to be sent to",
    },
    telegram_chat_id: {
      type: "string",
      title: "Telegram Chat Id",
      description: "Telegram chat ID for the broadcast to be sent to",
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "template_preferences",
    "discord_webhook_url",
    "telegram_chat_id",
  ],
  title: "Broadcast",
  description: "Broadcast with communication preferences",
} as const;

export const BroadcastCreateSchema = {
  properties: {
    template_preferences: {
      items: {
        prefixItems: [
          {
            type: "string",
            enum: [
              "subscription_predictions_welcome",
              "subscription_dex_signals_welcome",
              "subscription_combo_welcome",
              "new_member",
              "exchange_api_key_expiring",
              "test",
              "new_dex_ai_call",
              "new_dex_ai_call_incognito",
              "order_completion",
              "trading_agent_execution_alert",
              "otp_code",
              "subscription_expiring",
              "subscription_expired",
            ],
          },
          {
            type: "boolean",
          },
        ],
        type: "array",
        maxItems: 2,
        minItems: 2,
      },
      type: "array",
      title: "Template Preferences",
      description:
        "List of templates and whether the broadcast sends the notification for",
    },
    discord_webhook_url: {
      type: "string",
      title: "Discord Webhook Url",
      description: "Discord webhook URL for the broadcast to be sent to",
    },
    telegram_chat_id: {
      type: "string",
      title: "Telegram Chat Id",
      description: "Telegram chat ID for the broadcast to be sent to",
    },
  },
  type: "object",
  required: ["template_preferences", "discord_webhook_url", "telegram_chat_id"],
  title: "BroadcastCreate",
  description: "Create a new broadcast",
} as const;

export const BroadcastUpdateSchema = {
  properties: {
    template_preferences: {
      anyOf: [
        {
          items: {
            prefixItems: [
              {
                type: "string",
                enum: [
                  "subscription_predictions_welcome",
                  "subscription_dex_signals_welcome",
                  "subscription_combo_welcome",
                  "new_member",
                  "exchange_api_key_expiring",
                  "test",
                  "new_dex_ai_call",
                  "new_dex_ai_call_incognito",
                  "order_completion",
                  "trading_agent_execution_alert",
                  "otp_code",
                  "subscription_expiring",
                  "subscription_expired",
                ],
              },
              {
                type: "boolean",
              },
            ],
            type: "array",
            maxItems: 2,
            minItems: 2,
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Template Preferences",
      description:
        "List of templates and whether the broadcast sends the notification for",
    },
    discord_webhook_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Discord Webhook Url",
      description: "Discord webhook URL for the broadcast to be sent to",
    },
    telegram_chat_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Telegram Chat Id",
      description: "Telegram chat ID for the broadcast to be sent to",
    },
  },
  type: "object",
  title: "BroadcastUpdate",
  description: "Update a broadcast",
} as const;

export const DashboardActionButtonSchema = {
  properties: {
    label: {
      type: "string",
      title: "Label",
      description: "The label of the action.",
    },
    action: {
      type: "string",
      enum: ["link", "route"],
      title: "Action",
      description: "The type of action.",
    },
    value: {
      type: "string",
      title: "Value",
      description: "The value of the action.",
    },
  },
  type: "object",
  required: ["label", "action", "value"],
  title: "DashboardActionButton",
} as const;

export const DashboardFieldSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "The name of the field.",
    },
    value: {
      type: "string",
      title: "Value",
      description: "The value of the field.",
    },
  },
  type: "object",
  required: ["name", "value"],
  title: "DashboardField",
} as const;

export const DashboardNotificationSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    template_id: {
      type: "string",
      enum: [
        "subscription_predictions_welcome",
        "subscription_dex_signals_welcome",
        "subscription_combo_welcome",
        "new_member",
        "exchange_api_key_expiring",
        "test",
        "new_dex_ai_call",
        "new_dex_ai_call_incognito",
        "order_completion",
        "trading_agent_execution_alert",
        "otp_code",
        "subscription_expiring",
        "subscription_expired",
      ],
      title: "Template Id",
      description: "Template ID of the notification",
    },
    viewed: {
      type: "boolean",
      title: "Viewed",
      description: "Whether the notification has been marked as seen",
      default: false,
    },
    variables: {
      additionalProperties: true,
      type: "object",
      title: "Variables",
      description: "Variables of the notification",
    },
    user_id: {
      type: "string",
      title: "User Id",
      description: "User ID",
    },
    rendered: {
      $ref: "#/components/schemas/UITemplate",
      description: "Rendered notification",
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "template_id",
    "variables",
    "user_id",
    "rendered",
  ],
  title: "DashboardNotification",
} as const;

export const DashboardNotificationUpdateSchema = {
  properties: {
    viewed: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Viewed",
      description: "Whether the notification has been marked as seen",
    },
  },
  type: "object",
  title: "DashboardNotificationUpdate",
} as const;

export const NotificationCreateSchema = {
  properties: {
    template: {
      type: "string",
      enum: [
        "subscription_predictions_welcome",
        "subscription_dex_signals_welcome",
        "subscription_combo_welcome",
        "new_member",
        "exchange_api_key_expiring",
        "test",
        "new_dex_ai_call",
        "new_dex_ai_call_incognito",
        "order_completion",
        "trading_agent_execution_alert",
        "otp_code",
        "subscription_expiring",
        "subscription_expired",
      ],
      title: "Template",
      description: "Template ID",
    },
    variables: {
      additionalProperties: true,
      type: "object",
      title: "Variables",
      description: "Variables for the template",
    },
    user_ids: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "User Ids",
      description:
        "User IDs to send the notification to. If not provided, will use all users subscribed to the template",
    },
  },
  type: "object",
  required: ["template", "variables"],
  title: "NotificationCreate",
} as const;

export const PaginatedResponse_DashboardNotification_Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/DashboardNotification",
      },
      type: "array",
      title: "Data",
    },
    total: {
      type: "integer",
      title: "Total",
      description: "The total number of items",
    },
    page: {
      type: "integer",
      title: "Page",
      description: "The current page number",
    },
    page_size: {
      type: "integer",
      title: "Page Size",
      description: "The number of items per page",
    },
    prev: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Prev",
      description: "The previous page number",
    },
    next: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Next",
      description: "The next page number",
    },
    last: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Last",
      description: "The last page number",
    },
  },
  type: "object",
  required: ["data", "total", "page", "page_size"],
  title: "PaginatedResponse[DashboardNotification]",
} as const;

export const TemplateSchema = {
  properties: {
    identifier: {
      type: "string",
      enum: [
        "subscription_predictions_welcome",
        "subscription_dex_signals_welcome",
        "subscription_combo_welcome",
        "new_member",
        "exchange_api_key_expiring",
        "test",
        "new_dex_ai_call",
        "new_dex_ai_call_incognito",
        "order_completion",
        "trading_agent_execution_alert",
        "otp_code",
        "subscription_expiring",
        "subscription_expired",
      ],
      title: "Identifier",
      description: "Identifier of the template",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Name of the template",
    },
    variables: {
      additionalProperties: true,
      type: "object",
      title: "Variables",
      description: "Variables for the template",
    },
    channels: {
      items: {
        type: "string",
        enum: ["email", "telegram", "discord", "websocket", "ui"],
      },
      type: "array",
      title: "Channels",
      description: "Channels to send the notification to for this template",
    },
    user_controllable: {
      type: "boolean",
      title: "User Controllable",
      description:
        "Whether the user can enable/disable this notification template in their settings",
    },
  },
  type: "object",
  required: [
    "identifier",
    "name",
    "variables",
    "channels",
    "user_controllable",
  ],
  title: "Template",
} as const;

export const UITemplateSchema = {
  properties: {
    title: {
      type: "string",
      title: "Title",
      description: "The title of the notification.",
    },
    subtitle: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Subtitle",
      description: "The subtitle of the notification.",
    },
    body: {
      type: "string",
      title: "Body",
      description: "The body of the notification.",
    },
    imageUrl: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Imageurl",
      description: "The image URL of the notification.",
    },
    actions: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/DashboardActionButton",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Actions",
      description: "The actions of the notification.",
    },
    fields: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/DashboardField",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Fields",
      description: "The fields of the notification.",
    },
  },
  type: "object",
  required: ["title", "body"],
  title: "UITemplate",
} as const;

export const UserSettingSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    template_preferences: {
      items: {
        prefixItems: [
          {
            type: "string",
            enum: [
              "subscription_predictions_welcome",
              "subscription_dex_signals_welcome",
              "subscription_combo_welcome",
              "new_member",
              "exchange_api_key_expiring",
              "test",
              "new_dex_ai_call",
              "new_dex_ai_call_incognito",
              "order_completion",
              "trading_agent_execution_alert",
              "otp_code",
              "subscription_expiring",
              "subscription_expired",
            ],
          },
          {
            type: "boolean",
          },
        ],
        type: "array",
        maxItems: 2,
        minItems: 2,
      },
      type: "array",
      title: "Template Preferences",
      description:
        "List of templates and whether the user wants to receive the notification",
    },
    user_id: {
      type: "string",
      title: "User Id",
      description: "User ID",
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "template_preferences",
    "user_id",
  ],
  title: "UserSetting",
  description: "User setting with communication preferences",
} as const;

export const UserSettingCreateSchema = {
  properties: {
    template_preferences: {
      items: {
        prefixItems: [
          {
            type: "string",
            enum: [
              "subscription_predictions_welcome",
              "subscription_dex_signals_welcome",
              "subscription_combo_welcome",
              "new_member",
              "exchange_api_key_expiring",
              "test",
              "new_dex_ai_call",
              "new_dex_ai_call_incognito",
              "order_completion",
              "trading_agent_execution_alert",
              "otp_code",
              "subscription_expiring",
              "subscription_expired",
            ],
          },
          {
            type: "boolean",
          },
        ],
        type: "array",
        maxItems: 2,
        minItems: 2,
      },
      type: "array",
      title: "Template Preferences",
      description:
        "List of templates and whether the user wants to receive the notification",
    },
  },
  type: "object",
  required: ["template_preferences"],
  title: "UserSettingCreate",
  description: "Create a new user setting",
} as const;

export const UserSettingUpdateSchema = {
  properties: {
    template_preferences: {
      anyOf: [
        {
          items: {
            prefixItems: [
              {
                type: "string",
                enum: [
                  "subscription_predictions_welcome",
                  "subscription_dex_signals_welcome",
                  "subscription_combo_welcome",
                  "new_member",
                  "exchange_api_key_expiring",
                  "test",
                  "new_dex_ai_call",
                  "new_dex_ai_call_incognito",
                  "order_completion",
                  "trading_agent_execution_alert",
                  "otp_code",
                  "subscription_expiring",
                  "subscription_expired",
                ],
              },
              {
                type: "boolean",
              },
            ],
            type: "array",
            maxItems: 2,
            minItems: 2,
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Template Preferences",
      description:
        "List of templates and whether the user wants to receive the notification",
    },
  },
  type: "object",
  title: "UserSettingUpdate",
  description: "Update a user setting",
} as const;

export const _ExceptionDetail_Literal__unknown_error____invalid_data_request____invalid_data_response____object_already_exists____object_not_found____template_not_found____invalid_template_variables___Schema =
  {
    properties: {
      message: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "null",
          },
        ],
        title: "Message",
        description: "An additional error message",
      },
      code: {
        type: "string",
        enum: [
          "unknown_error",
          "invalid_data_request",
          "invalid_data_response",
          "object_already_exists",
          "object_not_found",
          "template_not_found",
          "invalid_template_variables",
        ],
        title: "Code",
        description: "The unique error code",
      },
      type: {
        type: "string",
        enum: ["user error", "exchange error", "server error", "no error"],
        title: "Type",
        description: "The type of error",
      },
      level: {
        type: "string",
        enum: ["error", "info", "success", "warning"],
        title: "Level",
        description: "The level of the error",
      },
      status_code: {
        type: "integer",
        title: "Status Code",
        description: "The HTTP status code",
      },
      details: {
        title: "Details",
        description: "Additional details about the error",
      },
    },
    type: "object",
    required: ["code", "type", "level", "status_code"],
    title: "ExceptionDetail",
  } as const;
