import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  SendNotificationData,
  SendNotificationError,
  SendNotificationResponse,
  GetNotificationsData,
  GetNotificationsError,
  GetNotificationsResponse,
  UpdateNotificationsData,
  UpdateNotificationsError,
  UpdateNotificationsResponse,
  DeleteNotificationsError,
  DeleteNotificationsResponse,
  UpdateNotificationData,
  UpdateNotificationError,
  UpdateNotificationResponse,
  DeleteNotificationData,
  DeleteNotificationError,
  DeleteNotificationResponse,
  GetUserSettingsError,
  GetUserSettingsResponse,
  UpdateUserSettingsData,
  UpdateUserSettingsError,
  UpdateUserSettingsResponse,
  CreateUserSettingsData,
  CreateUserSettingsError,
  CreateUserSettingsResponse,
  GetBroadcastSettingsError,
  GetBroadcastSettingsResponse,
  CreateBroadcastSettingsData,
  CreateBroadcastSettingsError,
  CreateBroadcastSettingsResponse,
  UpdateBroadcastSettingsData,
  UpdateBroadcastSettingsError,
  UpdateBroadcastSettingsResponse,
  GetTemplatesError,
  GetTemplatesResponse,
  GetTemplateData,
  GetTemplateError,
  GetTemplateResponse,
  PingError,
  PingResponse,
  GetMetricsError,
  GetMetricsResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Send Notification
   * Send template-based notification to the registered channels.
   */
  const sendNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<SendNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      SendNotificationResponse,
      SendNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Get Notifications
   * Get all notifications for the authenticated user. Default sort is `created_at` and default order is `desc`.
   */
  const getNotifications = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetNotificationsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetNotificationsResponse,
      GetNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Update Notifications
   * Bulk update notifications
   */
  const updateNotifications = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateNotificationsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateNotificationsResponse,
      UpdateNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Delete Notifications
   * Delete all notifications for the authenticated user
   */
  const deleteNotifications = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteNotificationsResponse,
      DeleteNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Update Notification
   * Update a notification's viewed status
   */
  const updateNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateNotificationResponse,
      UpdateNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications/{id}",
    });
  };

  /**
   * Delete Notification
   * Delete a notification
   */
  const deleteNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteNotificationResponse,
      DeleteNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications/{id}",
    });
  };

  /**
   * Get User Settings
   * Get user settings for the authenticated user
   */
  const getUserSettings = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetUserSettingsResponse,
      GetUserSettingsError,
      ThrowOnError
    >({
      ...options,
      url: "/settings/user",
    });
  };

  /**
   * Update User Settings
   * Update user settings for the authenticated user
   */
  const updateUserSettings = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateUserSettingsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateUserSettingsResponse,
      UpdateUserSettingsError,
      ThrowOnError
    >({
      ...options,
      url: "/settings/user",
    });
  };

  /**
   * Create User Settings
   * Create user settings for the authenticated user
   */
  const createUserSettings = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateUserSettingsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateUserSettingsResponse,
      CreateUserSettingsError,
      ThrowOnError
    >({
      ...options,
      url: "/settings/user",
    });
  };

  /**
   * Get Broadcast Settings
   * Get all broadcast settings
   */
  const getBroadcastSettings = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBroadcastSettingsResponse,
      GetBroadcastSettingsError,
      ThrowOnError
    >({
      ...options,
      url: "/settings/broadcast",
    });
  };

  /**
   * Create Broadcast Settings
   * Create new broadcast settings
   */
  const createBroadcastSettings = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateBroadcastSettingsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateBroadcastSettingsResponse,
      CreateBroadcastSettingsError,
      ThrowOnError
    >({
      ...options,
      url: "/settings/broadcast",
    });
  };

  /**
   * Update Broadcast Settings
   * Update broadcast settings by ID
   */
  const updateBroadcastSettings = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateBroadcastSettingsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateBroadcastSettingsResponse,
      UpdateBroadcastSettingsError,
      ThrowOnError
    >({
      ...options,
      url: "/settings/broadcast/{id}",
    });
  };

  /**
   * Get Templates
   * Get all templates.
   */
  const getTemplates = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTemplatesResponse,
      GetTemplatesError,
      ThrowOnError
    >({
      ...options,
      url: "/templates",
    });
  };

  /**
   * Get Template
   * Get a template by identifier.
   */
  const getTemplate = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetTemplateData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTemplateResponse,
      GetTemplateError,
      ThrowOnError
    >({
      ...options,
      url: "/templates/{identifier}",
    });
  };

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Metrics
   * Get Prometheus metrics for the application. Returns plain text.
   */
  const getMetrics = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetMetricsResponse,
      GetMetricsError,
      ThrowOnError
    >({
      ...options,
      url: "/metrics",
    });
  };

  return {
    sendNotification,
    getNotifications,
    updateNotifications,
    deleteNotifications,
    updateNotification,
    deleteNotification,
    getUserSettings,
    updateUserSettings,
    createUserSettings,
    getBroadcastSettings,
    createBroadcastSettings,
    updateBroadcastSettings,
    getTemplates,
    getTemplate,
    ping,
    getMetrics,
  };
}
