// This file is auto-generated by @hey-api/openapi-ts

/**
 * Broadcast with communication preferences
 */
export type Broadcast = {
  /**
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * List of templates and whether the broadcast sends the notification for
   */
  template_preferences: Array<
    [
      (
        | 'subscription_predictions_welcome'
        | 'subscription_dex_signals_welcome'
        | 'subscription_combo_welcome'
        | 'new_member'
        | 'exchange_api_key_expiring'
        | 'test'
        | 'dex_first_call'
        | 'dex_profit_call'
        | 'order_completion'
        | 'otp_code'
        | 'subscription_expiring'
        | 'subscription_expired'
        | 'development_update'
        | 'verify_email'
        | 'reset_password'
      ),
      boolean,
    ]
  >;
  /**
   * List of recipients for the broadcast to be sent to
   */
  recipients: Array<BroadcastRecipient>;
};

/**
 * Create a new broadcast
 */
export type BroadcastCreate = {
  /**
   * List of templates and whether the broadcast sends the notification for
   */
  template_preferences: Array<
    [
      (
        | 'subscription_predictions_welcome'
        | 'subscription_dex_signals_welcome'
        | 'subscription_combo_welcome'
        | 'new_member'
        | 'exchange_api_key_expiring'
        | 'test'
        | 'dex_first_call'
        | 'dex_profit_call'
        | 'order_completion'
        | 'otp_code'
        | 'subscription_expiring'
        | 'subscription_expired'
        | 'development_update'
        | 'verify_email'
        | 'reset_password'
      ),
      boolean,
    ]
  >;
  /**
   * List of recipients for the broadcast to be sent to
   */
  recipients: Array<BroadcastRecipient>;
};

/**
 * Webhook recipient configuration
 */
export type BroadcastRecipient = {
  /**
   * Service type for the broadcast
   */
  service: 'discord' | 'telegram';
  /**
   * Webhook URL or chat ID for the service
   */
  value: string;
  /**
   * Optional name/identifier for this recipient
   */
  name?: string | null;
};

/**
 * Service type for the broadcast
 */
export type service = 'discord' | 'telegram';

/**
 * Update a broadcast
 */
export type BroadcastUpdate = {
  /**
   * List of templates and whether the broadcast sends the notification for
   */
  template_preferences?: Array<
    [
      (
        | 'subscription_predictions_welcome'
        | 'subscription_dex_signals_welcome'
        | 'subscription_combo_welcome'
        | 'new_member'
        | 'exchange_api_key_expiring'
        | 'test'
        | 'dex_first_call'
        | 'dex_profit_call'
        | 'order_completion'
        | 'otp_code'
        | 'subscription_expiring'
        | 'subscription_expired'
        | 'development_update'
        | 'verify_email'
        | 'reset_password'
      ),
      boolean,
    ]
  > | null;
  /**
   * List of webhook recipients for the broadcast to be sent to
   */
  recipients?: Array<BroadcastRecipient> | null;
};

export type DashboardActionButton = {
  /**
   * The label of the action.
   */
  label: string;
  /**
   * The type of action.
   */
  action: 'link' | 'route';
  /**
   * The value of the action.
   */
  value: string;
};

/**
 * The type of action.
 */
export type action = 'link' | 'route';

export type DashboardField = {
  /**
   * The name of the field.
   */
  name: string;
  /**
   * The value of the field.
   */
  value: string;
};

export type DashboardNotification = {
  /**
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Template ID of the notification
   */
  template_id:
    | 'subscription_predictions_welcome'
    | 'subscription_dex_signals_welcome'
    | 'subscription_combo_welcome'
    | 'new_member'
    | 'exchange_api_key_expiring'
    | 'test'
    | 'dex_first_call'
    | 'dex_profit_call'
    | 'order_completion'
    | 'otp_code'
    | 'subscription_expiring'
    | 'subscription_expired'
    | 'development_update'
    | 'verify_email'
    | 'reset_password';
  /**
   * Whether the notification has been marked as seen
   */
  viewed?: boolean;
  /**
   * Variables of the notification
   */
  variables: {
    [key: string]: unknown;
  };
  /**
   * User ID
   */
  user_id: string;
  /**
   * Rendered notification
   */
  rendered: UITemplate;
};

/**
 * Template ID of the notification
 */
export type template_id =
  | 'subscription_predictions_welcome'
  | 'subscription_dex_signals_welcome'
  | 'subscription_combo_welcome'
  | 'new_member'
  | 'exchange_api_key_expiring'
  | 'test'
  | 'dex_first_call'
  | 'dex_profit_call'
  | 'order_completion'
  | 'otp_code'
  | 'subscription_expiring'
  | 'subscription_expired'
  | 'development_update'
  | 'verify_email'
  | 'reset_password';

export type DashboardNotificationUpdate = {
  /**
   * Whether the notification has been marked as seen
   */
  viewed?: boolean | null;
};

/**
 * Error response schema.
 */
export type ErrorResponse = {
  detail: string;
};

export type Notification = {
  /**
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Template ID
   */
  template:
    | 'subscription_predictions_welcome'
    | 'subscription_dex_signals_welcome'
    | 'subscription_combo_welcome'
    | 'new_member'
    | 'exchange_api_key_expiring'
    | 'test'
    | 'dex_first_call'
    | 'dex_profit_call'
    | 'order_completion'
    | 'otp_code'
    | 'subscription_expiring'
    | 'subscription_expired'
    | 'development_update'
    | 'verify_email'
    | 'reset_password';
  /**
   * Variables for the template
   */
  variables: {
    [key: string]: string;
  };
  /**
   * User IDs to send the notification to. If not provided, will use all users subscribed to the template
   */
  user_ids?: Array<string> | null;
};

/**
 * Template ID
 */
export type template =
  | 'subscription_predictions_welcome'
  | 'subscription_dex_signals_welcome'
  | 'subscription_combo_welcome'
  | 'new_member'
  | 'exchange_api_key_expiring'
  | 'test'
  | 'dex_first_call'
  | 'dex_profit_call'
  | 'order_completion'
  | 'otp_code'
  | 'subscription_expiring'
  | 'subscription_expired'
  | 'development_update'
  | 'verify_email'
  | 'reset_password';

export type NotificationCreate = {
  /**
   * Template ID
   */
  template:
    | 'subscription_predictions_welcome'
    | 'subscription_dex_signals_welcome'
    | 'subscription_combo_welcome'
    | 'new_member'
    | 'exchange_api_key_expiring'
    | 'test'
    | 'dex_first_call'
    | 'dex_profit_call'
    | 'order_completion'
    | 'otp_code'
    | 'subscription_expiring'
    | 'subscription_expired'
    | 'development_update'
    | 'verify_email'
    | 'reset_password';
  /**
   * Variables for the template
   */
  variables: {
    [key: string]: string;
  };
  /**
   * User IDs to send the notification to. If not provided, will use all users subscribed to the template
   */
  user_ids?: Array<string> | null;
};

/**
 * Result for a single notification sent via a specific channel to a specific recipient.
 */
export type NotificationResult = {
  /**
   * Status of the notification
   */
  status: 'success' | 'error';
  /**
   * Recipient of the notification, email address if channel is email, hash + broadcast ID if channel is discord or telegram, or user ID if channel is dashboard
   */
  recipient: string;
  /**
   * Template ID
   */
  template:
    | 'subscription_predictions_welcome'
    | 'subscription_dex_signals_welcome'
    | 'subscription_combo_welcome'
    | 'new_member'
    | 'exchange_api_key_expiring'
    | 'test'
    | 'dex_first_call'
    | 'dex_profit_call'
    | 'order_completion'
    | 'otp_code'
    | 'subscription_expiring'
    | 'subscription_expired'
    | 'development_update'
    | 'verify_email'
    | 'reset_password';
  /**
   * Error message if the notification failed
   */
  error?: string | null;
  /**
   * Channel of the notification
   */
  channel: 'email' | 'telegram' | 'discord' | 'websocket' | 'ui';
  /**
   * ID of the notification returned by the service in format <channel_id>/<message_id> for discord, <chat_id>/<message_id> for telegram, postmark's MessageID for email and mongo's _id value for dashboard notifications. Can be used to build a link to the notification. None if status is error.
   */
  message_id?: string | null;
  /**
   * ID of the action that triggered the notification. This matches the respective _id field in the notification_actions collection.
   */
  action_id: string;
};

/**
 * Status of the notification
 */
export type status = 'success' | 'error';

/**
 * Channel of the notification
 */
export type channel = 'email' | 'telegram' | 'discord' | 'websocket' | 'ui';

export type PaginatedResponse_DashboardNotification_ = {
  data: Array<DashboardNotification>;
  /**
   * The total number of items
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of items per page
   */
  page_size: number;
  /**
   * The previous page number
   */
  prev?: number | null;
  /**
   * The next page number
   */
  next?: number | null;
  /**
   * The last page number
   */
  last?: number | null;
};

export type PaginatedResponse_NotificationResult_ = {
  data: Array<NotificationResult>;
  /**
   * The total number of items
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of items per page
   */
  page_size: number;
  /**
   * The previous page number
   */
  prev?: number | null;
  /**
   * The next page number
   */
  next?: number | null;
  /**
   * The last page number
   */
  last?: number | null;
};

export type Template = {
  /**
   * Identifier of the template
   */
  identifier:
    | 'subscription_predictions_welcome'
    | 'subscription_dex_signals_welcome'
    | 'subscription_combo_welcome'
    | 'new_member'
    | 'exchange_api_key_expiring'
    | 'test'
    | 'dex_first_call'
    | 'dex_profit_call'
    | 'order_completion'
    | 'otp_code'
    | 'subscription_expiring'
    | 'subscription_expired'
    | 'development_update'
    | 'verify_email'
    | 'reset_password';
  /**
   * Name of the template
   */
  name: string;
  /**
   * Variables for the template
   */
  variables: {
    [key: string]: unknown;
  };
  /**
   * Channels to send the notification to for this template
   */
  channels: Array<'email' | 'telegram' | 'discord' | 'websocket' | 'ui'>;
  /**
   * Whether the user can enable/disable this notification template in their settings
   */
  user_controllable: boolean;
};

/**
 * Identifier of the template
 */
export type identifier =
  | 'subscription_predictions_welcome'
  | 'subscription_dex_signals_welcome'
  | 'subscription_combo_welcome'
  | 'new_member'
  | 'exchange_api_key_expiring'
  | 'test'
  | 'dex_first_call'
  | 'dex_profit_call'
  | 'order_completion'
  | 'otp_code'
  | 'subscription_expiring'
  | 'subscription_expired'
  | 'development_update'
  | 'verify_email'
  | 'reset_password';

export type UITemplate = {
  /**
   * The title of the notification.
   */
  title: string;
  /**
   * The subtitle of the notification.
   */
  subtitle?: string | null;
  /**
   * The body of the notification.
   */
  body: string;
  /**
   * The image URL of the notification.
   */
  imageUrl?: string | null;
  /**
   * The actions of the notification.
   */
  actions?: Array<DashboardActionButton> | null;
  /**
   * The fields of the notification.
   */
  fields?: Array<DashboardField> | null;
};

/**
 * User setting with communication preferences
 */
export type UserSetting = {
  /**
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * List of templates and whether the user wants to receive the notification
   */
  template_preferences: Array<
    [
      (
        | 'subscription_predictions_welcome'
        | 'subscription_dex_signals_welcome'
        | 'subscription_combo_welcome'
        | 'new_member'
        | 'exchange_api_key_expiring'
        | 'test'
        | 'dex_first_call'
        | 'dex_profit_call'
        | 'order_completion'
        | 'otp_code'
        | 'subscription_expiring'
        | 'subscription_expired'
        | 'development_update'
        | 'verify_email'
        | 'reset_password'
      ),
      boolean,
    ]
  >;
  /**
   * User ID
   */
  user_id: string;
};

/**
 * Create a new user setting
 */
export type UserSettingCreate = {
  /**
   * List of templates and whether the user wants to receive the notification
   */
  template_preferences: Array<
    [
      (
        | 'subscription_predictions_welcome'
        | 'subscription_dex_signals_welcome'
        | 'subscription_combo_welcome'
        | 'new_member'
        | 'exchange_api_key_expiring'
        | 'test'
        | 'dex_first_call'
        | 'dex_profit_call'
        | 'order_completion'
        | 'otp_code'
        | 'subscription_expiring'
        | 'subscription_expired'
        | 'development_update'
        | 'verify_email'
        | 'reset_password'
      ),
      boolean,
    ]
  >;
};

/**
 * Update a user setting
 */
export type UserSettingUpdate = {
  /**
   * List of templates and whether the user wants to receive the notification
   */
  template_preferences?: Array<
    [
      (
        | 'subscription_predictions_welcome'
        | 'subscription_dex_signals_welcome'
        | 'subscription_combo_welcome'
        | 'new_member'
        | 'exchange_api_key_expiring'
        | 'test'
        | 'dex_first_call'
        | 'dex_profit_call'
        | 'order_completion'
        | 'otp_code'
        | 'subscription_expiring'
        | 'subscription_expired'
        | 'development_update'
        | 'verify_email'
        | 'reset_password'
      ),
      boolean,
    ]
  > | null;
};

export type SendNotificationData = {
  body: NotificationCreate;
};

export type SendNotificationResponse = Notification;

export type SendNotificationError = ErrorResponse;

export type GetNotificationsData = {
  query?: {
    /**
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * The current page number
     */
    page?: number;
    /**
     * The number of items per page. Default is 100, max is 1000.
     */
    page_size?: number;
    /**
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * The order to sort by
     */
    sort_order?: 'asc' | 'desc' | null;
  };
};

export type GetNotificationsResponse = PaginatedResponse_DashboardNotification_;

export type GetNotificationsError = ErrorResponse;

export type UpdateNotificationsData = {
  body: DashboardNotificationUpdate;
};

export type UpdateNotificationsResponse = void;

export type UpdateNotificationsError = ErrorResponse;

export type DeleteNotificationsResponse = void;

export type DeleteNotificationsError = ErrorResponse;

export type UpdateNotificationData = {
  body: DashboardNotificationUpdate;
  path: {
    id: string;
  };
};

export type UpdateNotificationResponse = void;

export type UpdateNotificationError = ErrorResponse;

export type DeleteNotificationData = {
  path: {
    id: string;
  };
};

export type DeleteNotificationResponse = void;

export type DeleteNotificationError = ErrorResponse;

export type GetNotificationResultsData = {
  query?: {
    /**
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * The current page number
     */
    page?: number;
    /**
     * The number of items per page. Default is 100, max is 1000.
     */
    page_size?: number;
    /**
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * The order to sort by
     */
    sort_order?: 'asc' | 'desc' | null;
  };
};

export type GetNotificationResultsResponse =
  PaginatedResponse_NotificationResult_;

export type GetNotificationResultsError = ErrorResponse;

export type GetUserSettingsResponse = UserSetting;

export type GetUserSettingsError = ErrorResponse;

export type UpdateUserSettingsData = {
  body: UserSettingUpdate;
};

export type UpdateUserSettingsResponse = UserSetting;

export type UpdateUserSettingsError = ErrorResponse;

export type CreateUserSettingsData = {
  body: UserSettingCreate;
};

export type CreateUserSettingsResponse = UserSetting;

export type CreateUserSettingsError = ErrorResponse;

export type GetBroadcastSettingsResponse = Array<Broadcast>;

export type GetBroadcastSettingsError = ErrorResponse;

export type CreateBroadcastSettingsData = {
  body: BroadcastCreate;
};

export type CreateBroadcastSettingsResponse = Broadcast;

export type CreateBroadcastSettingsError = ErrorResponse;

export type UpdateBroadcastSettingsData = {
  body: BroadcastUpdate;
  path: {
    id: string;
  };
};

export type UpdateBroadcastSettingsResponse = Broadcast;

export type UpdateBroadcastSettingsError = ErrorResponse;

export type GetTemplatesResponse = Array<Template>;

export type GetTemplatesError = ErrorResponse;

export type GetTemplateData = {
  path: {
    identifier:
      | 'subscription_predictions_welcome'
      | 'subscription_dex_signals_welcome'
      | 'subscription_combo_welcome'
      | 'new_member'
      | 'exchange_api_key_expiring'
      | 'test'
      | 'dex_first_call'
      | 'dex_profit_call'
      | 'order_completion'
      | 'otp_code'
      | 'subscription_expiring'
      | 'subscription_expired'
      | 'development_update'
      | 'verify_email'
      | 'reset_password';
  };
};

export type GetTemplateResponse = Template;

export type GetTemplateError = ErrorResponse;

export type PingResponse = string;

export type PingError = ErrorResponse;

export type GetMetricsResponse = unknown;

export type GetMetricsError = ErrorResponse;
