// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorIdentifierSchema = {
  type: "string",
  enum: [
    "allocation_below_current_exposure",
    "allocation_below_min_amount",
    "black_swan",
    "bot_already_deleted",
    "bot_disabled",
    "bot_stopping_completed",
    "bot_stopping_started",
    "cancelled_open_order",
    "client_order_id_already_exists",
    "invalid_content_type",
    "delete_bot_error",
    "exchange_invalid_signature",
    "exchange_invalid_timestamp",
    "exchange_ip_address_is_not_authorized",
    "exchange_key_already_exists",
    "exchange_key_in_use",
    "exchange_system_under_maintenance",
    "exchange_rate_limit_exceeded",
    "insufficient_permissions_spot_and_futures_required",
    "exchange_service_temporarily_unavailable",
    "exchange_system_is_busy",
    "exchange_system_configuration_error",
    "exchange_internal_system_error",
    "exchange_user_account_is_frozen",
    "api_key_expired",
    "bearer_token_expired",
    "open_order_expired",
    "forbidden",
    "hedge_mode_not_active",
    "http_request_error",
    "insufficient_balance",
    "insufficient_margin",
    "insufficient_scopes",
    "invalid_api_key",
    "invalid_bearer",
    "invalid_data",
    "invalid_data_response",
    "invalid_exchange_key",
    "invalid_margin_mode",
    "invalid_model_name",
    "exchange_invalid_parameter",
    "leverage_limit_exceeded",
    "order_violates_liquidation_price_constraints",
    "margin_mode_clash",
    "name_not_unique",
    "no_credentials",
    "now_api_down",
    "object_already_exists",
    "object_created",
    "object_deleted",
    "object_locked",
    "object_not_found",
    "object_updated",
    "order_is_already_filled",
    "order_is_being_processed",
    "order_quantity_limit_exceeded",
    "order_does_not_exist",
    "order_price_is_invalid",
    "order_size_too_large",
    "order_size_too_small",
    "orphan_open_order",
    "orphan_close_order",
    "position_limit_exceeded",
    "position_does_not_exist",
    "position_opening_temporarily_suspended",
    "post_only_order_would_immediately_match",
    "request_scope_limit_exceeded",
    "risk_limit_exceeded",
    "rpc_timeout",
    "system_settlement_in_process",
    "strategy_already_exists",
    "strategy_disabled",
    "strategy_leverage_mismatch",
    "strategy_not_supporting_exchange",
    "success",
    "symbol_does_not_exist",
    "trading_action_expired",
    "TRADING_ACTION_SKIPPED_BOT_STOPPING",
    "trading_has_been_locked",
    "trading_is_suspended",
    "unknown_error_occurred",
    "requested_resource_not_found",
  ],
  title: "ApiErrorIdentifier",
  description: "Unique identifier of the API error.",
} as const;

export const ApiErrorLevelSchema = {
  type: "string",
  enum: ["error", "info", "success", "warning"],
  title: "ApiErrorLevel",
  description: "Level of the API error.",
} as const;

export const ApiErrorTypeSchema = {
  type: "string",
  enum: ["user error", "exchange error", "server error", "no error"],
  title: "ApiErrorType",
  description: "Type of the API error.",
} as const;

export const BotSchema = {
  properties: {
    user_id: {
      type: "string",
      title: "User Id",
      description: "UID for the user",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Name of the bot",
    },
    allocation: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Allocation",
      description: "Initial allocation for the bot",
    },
    status: {
      $ref: "#/components/schemas/BotStatus",
      description: "Status of the bot",
    },
    strategy_id: {
      type: "string",
      title: "Strategy Id",
      description: "UID for the trading strategy used by the bot",
    },
    api_key_id: {
      type: "string",
      title: "Api Key Id",
      description: "UID for the API key",
    },
    status_code: {
      anyOf: [
        {
          $ref: "#/components/schemas/ApiErrorIdentifier",
        },
        {
          type: "null",
        },
      ],
      description:
        "Status code of the bot. Set if the bot is stopped by an error.",
    },
    current_allocation: {
      type: "number",
      minimum: 0,
      title: "Current Allocation",
      description:
        "Initial allocation for the bot + accumulated PnL of the orders after the last allocation change",
      default: 0,
    },
    current_exposure: {
      type: "number",
      minimum: 0,
      title: "Current Exposure",
      description:
        "Current exposure of the bot, aka. the sum of the absolute values of the open positions",
      default: 0,
    },
  },
  type: "object",
  required: [
    "user_id",
    "name",
    "allocation",
    "status",
    "strategy_id",
    "api_key_id",
  ],
  title: "Bot",
  description: "Trading bot model for read operations.",
} as const;

export const BotCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Name of the bot",
    },
    allocation: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Allocation",
      description: "Initial allocation for the bot",
    },
    status: {
      $ref: "#/components/schemas/BotStatus",
      description: "Status of the bot",
    },
    strategy_id: {
      type: "string",
      title: "Strategy Id",
      description: "UID for the trading strategy used by the bot",
    },
    api_key_id: {
      type: "string",
      title: "Api Key Id",
      description: "UID for the API key",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["name", "allocation", "status", "strategy_id", "api_key_id"],
  title: "BotCreate",
  description: "Trading bot model for API create operations.",
} as const;

export const BotStatusSchema = {
  type: "string",
  enum: ["running", "stopping", "stopped", "deleted"],
  title: "BotStatus",
} as const;

export const BotUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      description: "Name of the bot",
    },
    allocation: {
      anyOf: [
        {
          type: "integer",
          exclusiveMinimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Allocation",
      description: "Initial allocation for the bot",
    },
    status: {
      anyOf: [
        {
          $ref: "#/components/schemas/BotStatus",
        },
        {
          type: "null",
        },
      ],
      description: "Status of the bot",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "BotUpdate",
  description: "Trading bot model for API update operations.",
} as const;

export const ExceptionDetailSchema = {
  properties: {
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
      description: "An additional error message",
    },
    code: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description: "The unique error code",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "The type of error",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "The level of the error",
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      description: "The HTTP status code",
    },
    details: {
      title: "Details",
      description: "Additional details about the error",
    },
  },
  type: "object",
  required: ["code", "type", "level", "status_code"],
  title: "ExceptionDetail",
  description: "Exception details returned to the client.",
} as const;

export const ExchangeSchema = {
  type: "string",
  enum: ["kucoin", "bingx", "hyperliquid"],
  title: "Exchange",
  description: "Supported exchanges for trading",
} as const;

export const ExchangeKeySchema = {
  properties: {
    user_id: {
      type: "string",
      title: "User Id",
      description: "UID for the user",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    label: {
      type: "string",
      title: "Label",
      description: "Label for the API key",
    },
    deleted: {
      type: "boolean",
      title: "Deleted",
      description: "Whether the API key has been deleted.",
      default: false,
    },
    exchange: {
      $ref: "#/components/schemas/Exchange",
      description: "The exchange the API key is for.",
    },
  },
  type: "object",
  required: ["user_id", "label", "exchange"],
  title: "ExchangeKey",
  description:
    "Exchange key model not containing sensitive information for read operations.",
} as const;

export const ExchangeKeyCreateSchema = {
  properties: {
    label: {
      type: "string",
      title: "Label",
      description: "Label for the API key",
    },
    api_key: {
      type: "string",
      title: "Api Key",
      description: "API key",
    },
    secret: {
      type: "string",
      title: "Secret",
      description: "API secret",
    },
    passphrase: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Passphrase",
      description: "API passphrase. Required by some exchanges.",
    },
    exchange: {
      $ref: "#/components/schemas/Exchange",
      description: "The exchange the API key is for.",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["label", "api_key", "secret", "exchange"],
  title: "ExchangeKeyCreate",
  description: "Exchange key model for API create operations.",
} as const;

export const ExchangeKeyUpdateSchema = {
  properties: {
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Label",
      description: "Label for the API key",
    },
    api_key: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Api Key",
      description: "API key",
    },
    secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Secret",
      description: "API secret",
    },
    passphrase: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Passphrase",
      description: "API passphrase. Required by some exchanges.",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "ExchangeKeyUpdate",
  description: "Exchange key model for API update operations.",
} as const;

export const ExecutionIdsSchema = {
  properties: {
    main: {
      type: "string",
      title: "Main",
      description: "Main execution ID.",
    },
    sl: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Sl",
      description:
        "Stop loss execution IDs. List with multiple items ordered by the next stop loss, e.g. price = 10000 => SLs: ['900', '700', '500'].",
    },
    tp: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tp",
      description:
        "Take profit execution IDs. List with multiple items ordered by the next take profit, e.g. price = 10000 => TPs: ['1100', '1300', '1500'].",
    },
  },
  type: "object",
  required: ["main", "sl", "tp"],
  title: "ExecutionIds",
} as const;

export const FuturesBalanceSchema = {
  properties: {
    apiKeyId: {
      type: "string",
      title: "Apikeyid",
      description: "API key ID",
    },
    asset: {
      type: "string",
      title: "Asset",
      description: "Asset/Currency code",
    },
    balance: {
      type: "number",
      title: "Balance",
      description: "Total balance/equity",
    },
    available: {
      type: "number",
      title: "Available",
      description: "Available balance for trading/withdrawal",
    },
    unrealizedPnl: {
      type: "number",
      title: "Unrealizedpnl",
      description: "Unrealized profit and loss",
    },
    usedMargin: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Usedmargin",
      description: "Used/Position margin",
    },
    frozenAmount: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Frozenamount",
      description: "Frozen/Hold funds",
    },
  },
  type: "object",
  required: ["apiKeyId", "asset", "balance", "available", "unrealizedPnl"],
  title: "FuturesBalance",
  description: "Model for futures balance",
} as const;

export const FuturesTradingActionSchema = {
  properties: {
    leverage: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
          default: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Leverage",
      description: "Leverage to use for futures trades.",
    },
    margin_mode: {
      anyOf: [
        {
          $ref: "#/components/schemas/MarginMode",
        },
        {
          type: "null",
        },
      ],
      description: "Margin mode for futures trades.",
      default: "isolated",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Execution Id",
      description:
        "UID for the execution of the order. Leave empty for open actions. Required on close actions if you have placed a TP/SL before. A specific TP/SL execution ID of the opening order. The allocation should match the TP/SL allocation you set.",
    },
    open_order_execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Open Order Execution Id",
      description:
        "UID for the order to close. Leave empty for open actions. Required on close actions. The main execution ID of the opening order.",
    },
    action_type: {
      $ref: "#/components/schemas/TradingActionType",
      description: "The type of action.",
    },
    market_type: {
      $ref: "#/components/schemas/MarketType",
      description: "The type of market the action is for.",
    },
    strategy_id: {
      type: "string",
      title: "Strategy Id",
      description: "UID for the strategy.",
    },
    symbol: {
      type: "string",
      title: "Symbol",
      description:
        "Trading symbol or asset pair in format: 'symbol/quote_currency' (see market service for valid symbols)",
    },
    is_limit: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Limit",
      description: "Whether this is a limit order. Default is False.",
      default: false,
    },
    limit_price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Limit Price",
      description:
        "The limit price for limit orders. If not set, the market price will be used.",
    },
    allocation: {
      type: "string",
      title: "Allocation",
      description:
        "How much of bot's balance to use for the order (for open actions). How much of the reference open order (open_order_execution_id) to close (for close actions). 0=0%, 1=100%.",
    },
    take_profit: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/TPSL",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Take Profit",
      description:
        "Take profit targets. Can be set for open actions only. Multiple can be set.",
    },
    stop_loss: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/TPSL",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Stop Loss",
      description:
        "Stop loss values. Can be set for open actions only. Multiple can be set.",
    },
    expiry_timestamp: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Expiry Timestamp",
      description:
        "Timestamp of when the order will expire. If not set, the order will not expire. Applied on each bot individually.",
    },
    client_order_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Order Id",
      description: "UID for the client order.",
    },
    position_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Position Id",
      description: "Extra Field. UID for the position to close.",
    },
  },
  type: "object",
  required: [
    "leverage",
    "action_type",
    "market_type",
    "strategy_id",
    "symbol",
    "allocation",
  ],
  title: "FuturesTradingAction",
  description: "Model for futures trading actions",
} as const;

export const FuturesTradingActionCreateSchema = {
  properties: {
    leverage: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
          default: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Leverage",
      description: "Leverage to use for futures trades.",
    },
    margin_mode: {
      anyOf: [
        {
          $ref: "#/components/schemas/MarginMode",
        },
        {
          type: "null",
        },
      ],
      description: "Margin mode for futures trades.",
      default: "isolated",
    },
    execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Execution Id",
      description:
        "UID for the execution of the order. Leave empty for open actions. Required on close actions if you have placed a TP/SL before. A specific TP/SL execution ID of the opening order. The allocation should match the TP/SL allocation you set.",
    },
    open_order_execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Open Order Execution Id",
      description:
        "UID for the order to close. Leave empty for open actions. Required on close actions. The main execution ID of the opening order.",
    },
    action_type: {
      $ref: "#/components/schemas/TradingActionType",
      description: "The type of action.",
    },
    market_type: {
      $ref: "#/components/schemas/MarketType",
      description: "The type of market the action is for.",
    },
    strategy_id: {
      type: "string",
      title: "Strategy Id",
      description: "UID for the strategy.",
    },
    symbol: {
      type: "string",
      title: "Symbol",
      description:
        "Trading symbol or asset pair in format: 'symbol/quote_currency' (see market service for valid symbols)",
    },
    is_limit: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Limit",
      description: "Whether this is a limit order. Default is False.",
      default: false,
    },
    limit_price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Limit Price",
      description:
        "The limit price for limit orders. If not set, the market price will be used.",
    },
    allocation: {
      type: "string",
      title: "Allocation",
      description:
        "How much of bot's balance to use for the order (for open actions). How much of the reference open order (open_order_execution_id) to close (for close actions). 0=0%, 1=100%.",
    },
    take_profit: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/TPSLCreate",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Take Profit",
      description:
        "Take profit targets. Can be set for open actions only. Multiple can be set.",
    },
    stop_loss: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/TPSLCreate",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Stop Loss",
      description:
        "Stop loss values. Can be set for open actions only. Multiple can be set.",
    },
    expiry_timestamp: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Expiry Timestamp",
      description:
        "Timestamp of when the order will expire. If not set, the order will not expire. Applied on each bot individually.",
    },
  },
  type: "object",
  required: [
    "leverage",
    "action_type",
    "market_type",
    "strategy_id",
    "symbol",
    "allocation",
  ],
  title: "FuturesTradingActionCreate",
  description: "Model for sending futures trading actions",
} as const;

export const LogLevelSchema = {
  type: "string",
  enum: ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
  title: "LogLevel",
} as const;

export const MarginModeSchema = {
  type: "string",
  enum: ["isolated", "cross"],
  title: "MarginMode",
  description: "Margin mode for futures trades",
} as const;

export const MarketTypeSchema = {
  type: "string",
  enum: ["spot", "futures"],
  title: "MarketType",
  description: "Market types",
} as const;

export const NotificationSchema = {
  properties: {
    user_id: {
      type: "string",
      title: "User Id",
      description: "UID for the user",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    viewed: {
      type: "boolean",
      title: "Viewed",
      description: "Whether the notification has been marked as seen",
      default: false,
    },
    sent: {
      type: "boolean",
      title: "Sent",
      description: "Whether the notification has been sent as an email",
      default: false,
    },
    identifier: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description:
        "Identifier string. Must match the mapping key in the frontend.",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "Level of the notification. Of type ApiErrorLevel",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "Type of the notification. Of type ApiErrorType",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["user_id", "identifier", "level", "type"],
  title: "Notification",
  description: "Notification model for read operations.",
} as const;

export const NotificationCreateSchema = {
  properties: {
    viewed: {
      type: "boolean",
      title: "Viewed",
      description: "Whether the notification has been marked as seen",
      default: false,
    },
    sent: {
      type: "boolean",
      title: "Sent",
      description: "Whether the notification has been sent as an email",
      default: false,
    },
    identifier: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description:
        "Identifier string. Must match the mapping key in the frontend.",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "Level of the notification. Of type ApiErrorLevel",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "Type of the notification. Of type ApiErrorType",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["identifier", "level", "type"],
  title: "NotificationCreate",
  description: "Notification model for create operations.",
} as const;

export const NotificationUpdateSchema = {
  properties: {
    viewed: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Viewed",
      description: "Whether the notification has been marked as seen",
    },
    sent: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Sent",
      description: "Whether the notification has been sent as an email",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "NotificationUpdate",
  description: "Notification model for API update operations.",
} as const;

export const OrderSchema = {
  properties: {
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    trading_action_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Trading Action Id",
      description: "UID for the trading action that placed the order",
    },
    execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Execution Id",
      description: "UID for the execution (not unique to the bot)",
    },
    exchange_order_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Exchange Order Id",
      description: "UID for the order on the exchange",
    },
    position_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Position Id",
      description: "UID for the position on the exchange",
    },
    api_key_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Api Key Id",
      description: "UID for the API key",
    },
    user_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Id",
      description: "UID for the user",
    },
    bot_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bot Id",
      description: "UID for the bot",
    },
    client_order_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Order Id",
      description: "Client order ID",
    },
    exchange: {
      anyOf: [
        {
          $ref: "#/components/schemas/Exchange",
        },
        {
          type: "null",
        },
      ],
      description: "Exchange name. Of type Exchange",
    },
    symbol: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Symbol",
      description: "Trading symbol on exchange",
    },
    common_symbol: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Common Symbol",
      description: "Common trading symbol",
    },
    price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Price",
      description: "Price of the order",
    },
    action_type: {
      anyOf: [
        {
          $ref: "#/components/schemas/TradingActionType",
        },
        {
          type: "null",
        },
      ],
      description: "Type of trading action. Of type TradingActionType",
    },
    market_type: {
      anyOf: [
        {
          $ref: "#/components/schemas/MarketType",
        },
        {
          type: "null",
        },
      ],
      description: "Market type of the order. Of type MarketType",
    },
    margin_mode: {
      anyOf: [
        {
          $ref: "#/components/schemas/MarginMode",
        },
        {
          type: "null",
        },
      ],
      description: "Margin mode of the order. Of type MarginMode",
    },
    status_code: {
      anyOf: [
        {
          $ref: "#/components/schemas/ApiErrorIdentifier",
        },
        {
          type: "null",
        },
      ],
      description: "API error identifier. Of type ApiErrorIdentifier",
    },
    status: {
      anyOf: [
        {
          $ref: "#/components/schemas/OrderStatus",
        },
        {
          type: "null",
        },
      ],
      description: "Trade status of the order. Of type OrderStatus",
    },
    filled_perc: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Filled Perc",
      description: "Percentage of the order filled",
    },
    filled_qty: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Filled Qty",
      description:
        "Quantity filled. Needed for pnl calculation. In the symbol's base currency.",
    },
    sent_qty: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Sent Qty",
      description:
        "Quantity sent to the exchange. In the symbol's base currency.",
    },
    fee: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Fee",
      description: "Fees for the order",
    },
    leverage: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Leverage",
      description: "Leverage for the order",
    },
    order_details: {
      anyOf: [
        {},
        {
          type: "null",
        },
      ],
      title: "Order Details",
      description: "Exchange specific details of the order",
      default: {},
    },
    pnl: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Pnl",
      description: "Profit and loss for the order",
    },
    order_time: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Order Time",
      description: "Timestamp of order creation on the exchange.",
    },
  },
  type: "object",
  title: "Order",
  description:
    "Response model for orders. All optional as the model is built step by step.",
} as const;

export const OrderStatusSchema = {
  type: "string",
  enum: ["new", "filled", "partially_filled", "cancelled", "failed"],
  title: "OrderStatus",
  description: "Status of the order",
} as const;

export const PostFuturesActionSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Action ID.",
    },
    execution_ids: {
      $ref: "#/components/schemas/ExecutionIds",
      description: "Execution IDs for the action.",
    },
  },
  type: "object",
  required: ["id", "execution_ids"],
  title: "PostFuturesAction",
} as const;

export const SpotTradingActionCreateSchema = {
  properties: {
    execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Execution Id",
      description:
        "UID for the execution of the order. Leave empty for open actions. Required on close actions if you have placed a TP/SL before. A specific TP/SL execution ID of the opening order. The allocation should match the TP/SL allocation you set.",
    },
    open_order_execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Open Order Execution Id",
      description:
        "UID for the order to close. Leave empty for open actions. Required on close actions. The main execution ID of the opening order.",
    },
    action_type: {
      $ref: "#/components/schemas/TradingActionType",
      description: "The type of action.",
    },
    market_type: {
      $ref: "#/components/schemas/MarketType",
      description: "The type of market the action is for.",
    },
    strategy_id: {
      type: "string",
      title: "Strategy Id",
      description: "UID for the strategy.",
    },
    symbol: {
      type: "string",
      title: "Symbol",
      description:
        "Trading symbol or asset pair in format: 'symbol/quote_currency' (see market service for valid symbols)",
    },
    is_limit: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Limit",
      description: "Whether this is a limit order. Default is False.",
      default: false,
    },
    limit_price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Limit Price",
      description:
        "The limit price for limit orders. If not set, the market price will be used.",
    },
    allocation: {
      type: "string",
      title: "Allocation",
      description:
        "How much of bot's balance to use for the order (for open actions). How much of the reference open order (open_order_execution_id) to close (for close actions). 0=0%, 1=100%.",
    },
    take_profit: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/TPSLCreate",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Take Profit",
      description:
        "Take profit targets. Can be set for open actions only. Multiple can be set.",
    },
    stop_loss: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/TPSLCreate",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Stop Loss",
      description:
        "Stop loss values. Can be set for open actions only. Multiple can be set.",
    },
    expiry_timestamp: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Expiry Timestamp",
      description:
        "Timestamp of when the order will expire. If not set, the order will not expire. Applied on each bot individually.",
    },
  },
  type: "object",
  required: [
    "action_type",
    "market_type",
    "strategy_id",
    "symbol",
    "allocation",
  ],
  title: "SpotTradingActionCreate",
  description: "Model for sending spot trading actions",
} as const;

export const StrategySchema = {
  properties: {
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Timestamp of creation",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Timestamp of last update",
    },
    id: {
      type: "string",
      title: "Id",
      description: "Unique identifier for the resource",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Name of the strategy",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Description of the strategy",
    },
    exchanges: {
      items: {
        $ref: "#/components/schemas/StrategyExchangeInfo",
      },
      type: "array",
      title: "Exchanges",
      description: "Exchanges supported by the strategy.",
    },
    enabled: {
      type: "boolean",
      title: "Enabled",
      description:
        "Whether the strategy is enabled. If false, no bots will be created or updated for this strategy, open trades will be rejected. Existing bots will be marked as stopping.",
    },
    performance_fee: {
      type: "number",
      maximum: 1,
      exclusiveMinimum: 0,
      title: "Performance Fee",
      description: "Performance fee for the strategy",
    },
    identifier: {
      type: "string",
      title: "Identifier",
      description:
        "Unique human readable identifier for the strategy e.g. 'daily_trend_momentum'",
    },
    margin_mode: {
      anyOf: [
        {
          $ref: "#/components/schemas/MarginMode",
        },
        {
          type: "null",
        },
      ],
      description:
        "Margin mode to use for the strategy. Not allowed for spot strategies. Must be set for futures strategies.",
    },
    leverage: {
      type: "integer",
      title: "Leverage",
      description: "Leverage for the strategy",
    },
    market_type: {
      $ref: "#/components/schemas/MarketType",
      description: "Market of operation of the strategy",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "name",
    "description",
    "exchanges",
    "enabled",
    "performance_fee",
    "identifier",
    "leverage",
    "market_type",
  ],
  title: "Strategy",
  description: "Strategy model for read operations.",
} as const;

export const StrategyCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Name of the strategy",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Description of the strategy",
    },
    exchanges: {
      items: {
        $ref: "#/components/schemas/StrategyExchangeInfo",
      },
      type: "array",
      title: "Exchanges",
      description: "Exchanges supported by the strategy.",
    },
    enabled: {
      type: "boolean",
      title: "Enabled",
      description:
        "Whether the strategy is enabled. If false, no bots will be created or updated for this strategy, open trades will be rejected. Existing bots will be marked as stopping.",
    },
    performance_fee: {
      type: "number",
      maximum: 1,
      exclusiveMinimum: 0,
      title: "Performance Fee",
      description: "Performance fee for the strategy",
    },
    identifier: {
      type: "string",
      title: "Identifier",
      description:
        "Unique human readable identifier for the strategy e.g. 'daily_trend_momentum'",
    },
    margin_mode: {
      anyOf: [
        {
          $ref: "#/components/schemas/MarginMode",
        },
        {
          type: "null",
        },
      ],
      description:
        "Margin mode to use for the strategy. Not allowed for spot strategies. Must be set for futures strategies.",
    },
    leverage: {
      type: "integer",
      title: "Leverage",
      description: "Leverage for the strategy",
    },
    market_type: {
      $ref: "#/components/schemas/MarketType",
      description: "Market of operation of the strategy",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "name",
    "description",
    "exchanges",
    "enabled",
    "performance_fee",
    "identifier",
    "leverage",
    "market_type",
  ],
  title: "StrategyCreate",
  description: "Strategy model for API create operations.",
} as const;

export const StrategyExchangeInfoSchema = {
  properties: {
    exchange: {
      $ref: "#/components/schemas/Exchange",
      description: "Exchange name. Of type Exchange",
    },
    min_amount: {
      type: "integer",
      title: "Min Amount",
      description: "Minimum amount for the strategy on the exchange",
    },
  },
  type: "object",
  required: ["exchange", "min_amount"],
  title: "StrategyExchangeInfo",
} as const;

export const StrategyUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      description: "Name of the strategy",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Description of the strategy",
    },
    exchanges: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/StrategyExchangeInfo",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Exchanges",
      description: "Exchanges supported by the strategy.",
    },
    enabled: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Enabled",
      description:
        "Whether the strategy is enabled. If false, no bots will be created or updated for this strategy, open trades will be rejected. Existing bots will be marked as stopping.",
    },
    performance_fee: {
      anyOf: [
        {
          type: "number",
          maximum: 1,
          exclusiveMinimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Performance Fee",
      description: "Performance fee for the strategy",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "StrategyUpdate",
  description: "Strategy model for API update operations.",
} as const;

export const TPSLSchema = {
  properties: {
    price_delta: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Price Delta",
      description:
        "The price delta to calculate the limit price from the current market price, e.g. for a SL of 1% the it would be 0.99",
    },
    price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Price",
      description:
        "The limit price to set the target at. If not set, the limit price will be calculated from the current market price.",
    },
    allocation: {
      type: "string",
      title: "Allocation",
      description:
        "Percentage of the open order to sell. All allocations must sum up to 1. Use this allocation again when closing the order.",
    },
    execution_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Execution Id",
      description: "Execution ID of the order.",
    },
    client_order_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Order Id",
      description: "Client order ID of the order.",
    },
  },
  type: "object",
  required: ["allocation"],
  title: "TPSL",
  description: "Runtime fields for take profit and stop loss",
} as const;

export const TPSLCreateSchema = {
  properties: {
    price_delta: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Price Delta",
      description:
        "The price delta to calculate the limit price from the current market price, e.g. for a SL of 1% the it would be 0.99",
    },
    price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Price",
      description:
        "The limit price to set the target at. If not set, the limit price will be calculated from the current market price.",
    },
    allocation: {
      type: "string",
      title: "Allocation",
      description:
        "Percentage of the open order to sell. All allocations must sum up to 1. Use this allocation again when closing the order.",
    },
  },
  type: "object",
  required: ["allocation"],
  title: "TPSLCreate",
  description: "Model for take profit and stop loss",
} as const;

export const TradingActionTypeSchema = {
  type: "string",
  enum: ["open_long", "open_short", "close_long", "close_short"],
  title: "TradingActionType",
  description: "Type of trading action",
} as const;
