import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  GetBotOrdersCountData,
  GetBotOrdersCountError,
  GetBotOrdersCountResponse,
  GetBotsOrdersCountData,
  GetBotsOrdersCountError,
  GetBotsOrdersCountResponse,
  GetBotOrdersPnlData,
  GetBotOrdersPnlError,
  GetBotOrdersPnlResponse,
  GetBotsOrdersPnlData,
  GetBotsOrdersPnlError,
  GetBotsOrdersPnlResponse,
  GetBotsOrdersData,
  GetBotsOrdersError,
  GetBotsOrdersResponse,
  GetBotOrdersData,
  GetBotOrdersError,
  GetBotOrdersResponse,
  GetBotsActionsData,
  GetBotsActionsError,
  GetBotsActionsResponse,
  GetBotActionsData,
  GetBotActionsError,
  GetBotActionsResponse,
  GetBotsData,
  GetBotsError,
  GetBotsResponse,
  CreateBotData,
  CreateBotError,
  CreateBotResponse,
  GetBotData,
  GetBotError,
  GetBotResponse,
  UpdateBotData,
  UpdateBotError,
  UpdateBotResponse,
  DeleteBotData,
  DeleteBotError,
  DeleteBotResponse,
  GetExchangeKeysData,
  GetExchangeKeysError,
  GetExchangeKeysResponse,
  CreateExchangeKeyData,
  CreateExchangeKeyError,
  CreateExchangeKeyResponse,
  GetExchangeKeyBalancesError,
  GetExchangeKeyBalancesResponse,
  GetExchangeKeyByIdData,
  GetExchangeKeyByIdError,
  GetExchangeKeyByIdResponse,
  DeleteExchangeKeyData,
  DeleteExchangeKeyError,
  DeleteExchangeKeyResponse,
  UpdateExchangeKeyData,
  UpdateExchangeKeyError,
  UpdateExchangeKeyResponse,
  PostFuturesActionData,
  PostFuturesActionError,
  PostFuturesActionResponse,
  PostSpotActionData,
  PostSpotActionError,
  PostSpotActionResponse,
  GetActionsCountData,
  GetActionsCountError,
  GetActionsCountResponse,
  GetOrdersCountData,
  GetOrdersCountError,
  GetOrdersCountResponse,
  GetStrategiesData,
  GetStrategiesError,
  GetStrategiesResponse,
  CreateStrategyData,
  CreateStrategyError,
  CreateStrategyResponse,
  GetStrategyUsageError,
  GetStrategyUsageResponse,
  KillStrategyData,
  KillStrategyError,
  KillStrategyResponse,
  UpdateStrategyData,
  UpdateStrategyError,
  UpdateStrategyResponse,
  GetNotificationsData,
  GetNotificationsError,
  GetNotificationsResponse,
  CreateNotificationData,
  CreateNotificationError,
  CreateNotificationResponse,
  UpdateNotificationsData,
  UpdateNotificationsError,
  UpdateNotificationsResponse,
  DeleteNotificationsError,
  DeleteNotificationsResponse,
  UpdateNotificationData,
  UpdateNotificationError,
  UpdateNotificationResponse,
  DeleteNotificationData,
  DeleteNotificationError,
  DeleteNotificationResponse,
  GetExchangeInfosError,
  GetExchangeInfosResponse,
  PingError,
  PingResponse,
  GetMetricsError,
  GetMetricsResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Get Bot Orders Count
   * Get the number of orders for a bot by day, week, month, or year. The default sort is `timestamp` and the default order is `asc`.
   */
  const getBotOrdersCount = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetBotOrdersCountData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotOrdersCountResponse,
      GetBotOrdersCountError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}/orders/count",
    });
  };

  /**
   * Get Bots Orders Count
   * Get the number of orders for all bots of the user by day, week, month, or year. The default sort is `timestamp` and the default order is `asc`.
   */
  const getBotsOrdersCount = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsOrdersCountData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsOrdersCountResponse,
      GetBotsOrdersCountError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/orders/count",
    });
  };

  /**
   * Get Bot Pnl
   * Returns a list of PnLs for a bot over time, sorted by `timestamp` ascending by default.
   *
   * If more than 1000 points exist, PnLs are grouped by day.
   * To get the latest cumulative PnL in a time window, use `sort_by=timestamp`, `sort_order=desc`, and `limit=1`.
   */
  const getBotOrdersPnl = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetBotOrdersPnlData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotOrdersPnlResponse,
      GetBotOrdersPnlError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}/orders/pnl",
    });
  };

  /**
   * Get Bots Pnl
   * Returns a list of PnLs for all bots of the user over time, sorted by `timestamp` ascending by default.
   *
   * If more than 1000 points exist, PnLs are grouped by day.
   * To get the latest cumulative PnL in a time window, use `sort_by=timestamp`, `sort_order=desc`, and `limit=1`.
   */
  const getBotsOrdersPnl = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsOrdersPnlData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsOrdersPnlResponse,
      GetBotsOrdersPnlError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/orders/pnl",
    });
  };

  /**
   * Get Bots Orders
   * Get all orders for all bots of the user. Default sort is `created_at` and default order is `desc`.
   */
  const getBotsOrders = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsOrdersData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsOrdersResponse,
      GetBotsOrdersError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/orders",
    });
  };

  /**
   * Get Bot Orders
   * Get all orders for a bot of the user. Default sort is `created_at` and default order is `desc`.
   */
  const getBotOrders = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetBotOrdersData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotOrdersResponse,
      GetBotOrdersError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}/orders",
    });
  };

  /**
   * Get Bots Actions
   * Get all actions for all bots of the user
   */
  const getBotsActions = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsActionsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsActionsResponse,
      GetBotsActionsError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/actions",
    });
  };

  /**
   * Get Bot Actions
   * Get all orders for a bot of the user
   */
  const getBotActions = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetBotActionsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotActionsResponse,
      GetBotActionsError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}/actions",
    });
  };

  /**
   * Get Bots
   * Returns all bots for the user. Default sort is by created_at, descending. Deleted bots are included by default.
   */
  const getBots = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsResponse,
      GetBotsError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Create Bot
   * Creates a new bot.
   */
  const createBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateBotResponse,
      CreateBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Get Bot
   * Returns a bot for the user.
   */
  const getBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotResponse,
      GetBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}",
    });
  };

  /**
   * Update Bot
   * Updates a bot.
   */
  const updateBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateBotResponse,
      UpdateBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}",
    });
  };

  /**
   * Delete Bot
   * Soft deletes a bot by cancelling all orders and closing all positions.
   */
  const deleteBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteBotResponse,
      DeleteBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}",
    });
  };

  /**
   * Get Exchange Keys
   * Get all exchange keys. Returns all non-deleted API keys by default.
   */
  const getExchangeKeys = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetExchangeKeysData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetExchangeKeysResponse,
      GetExchangeKeysError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys",
    });
  };

  /**
   * Post Exchange Key
   * Create a new exchange key.
   */
  const createExchangeKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateExchangeKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateExchangeKeyResponse,
      CreateExchangeKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys",
    });
  };

  /**
   * Get Exchange Key Balances
   * Get the balances of all exchange keys.
   */
  const getExchangeKeyBalances = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetExchangeKeyBalancesResponse,
      GetExchangeKeyBalancesError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/balances",
    });
  };

  /**
   * Get Exchange Key By Id
   * Get an exchange key by ID.
   */
  const getExchangeKeyById = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetExchangeKeyByIdData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetExchangeKeyByIdResponse,
      GetExchangeKeyByIdError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/{id}",
    });
  };

  /**
   * Delete Exchange Key
   * Delete an API key. This will set the deleted field to true.
   */
  const deleteExchangeKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteExchangeKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteExchangeKeyResponse,
      DeleteExchangeKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/{id}",
    });
  };

  /**
   * Put Exchange Key
   * Update an exchange key.
   */
  const updateExchangeKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateExchangeKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateExchangeKeyResponse,
      UpdateExchangeKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/{id}",
    });
  };

  /**
   * Post Futures Action
   * Endpoint to send futures trading actions. The action is queued for processing and the response is returned immediately. Only API key authentication is supported.
   */
  const postFuturesAction = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<PostFuturesActionData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      PostFuturesActionResponse,
      PostFuturesActionError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/futures",
    });
  };

  /**
   * Post Spot Action
   */
  const postSpotAction = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<PostSpotActionData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      PostSpotActionResponse,
      PostSpotActionError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/spot",
    });
  };

  /**
   * Get Actions Count
   * Get the number of orders for all users by day, week, month, or year. The default sort is `timestamp` and the default order is `asc`..
   */
  const getActionsCount = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetActionsCountData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetActionsCountResponse,
      GetActionsCountError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/count",
    });
  };

  /**
   * Get Orders Count
   * Get the number of orders for all users by day, week, month, or year. The default sort is `timestamp` and the default order is `asc`..
   */
  const getOrdersCount = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetOrdersCountData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetOrdersCountResponse,
      GetOrdersCountError,
      ThrowOnError
    >({
      ...options,
      url: "/orders/count",
    });
  };

  /**
   * Get Strategies
   * Get all strategies.
   */
  const getStrategies = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetStrategiesData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetStrategiesResponse,
      GetStrategiesError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies",
    });
  };

  /**
   * Create Strategy
   * Creates a new strategy.
   */
  const createStrategy = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateStrategyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateStrategyResponse,
      CreateStrategyError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies",
    });
  };

  /**
   * Get Strategy Usage
   * Get the usage count of each strategy.
   */
  const getStrategyUsage = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetStrategyUsageResponse,
      GetStrategyUsageError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies/usage",
    });
  };

  /**
   * Kill Strategy
   * Kills a strategy by disabling it and deleting all bots associated with it.
   */
  const killStrategy = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<KillStrategyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      KillStrategyResponse,
      KillStrategyError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies/{id}",
    });
  };

  /**
   * Update Strategy
   * Updates a strategy. If the strategy is being disabled, all bots associated with it will be set to stopping.
   */
  const updateStrategy = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateStrategyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateStrategyResponse,
      UpdateStrategyError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies/{id}",
    });
  };

  /**
   * Get Notifications
   * Get all notifications for the authenticated user
   */
  const getNotifications = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetNotificationsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetNotificationsResponse,
      GetNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Create Notification
   * Create a new notification
   */
  const createNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateNotificationResponse,
      CreateNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Update Notifications
   * Bulk update notifications
   */
  const updateNotifications = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateNotificationsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateNotificationsResponse,
      UpdateNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Delete Notifications
   * Delete all notifications for the authenticated user
   */
  const deleteNotifications = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteNotificationsResponse,
      DeleteNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Update Notification
   * Update a notification's viewed status
   */
  const updateNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateNotificationResponse,
      UpdateNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications/{id}",
    });
  };

  /**
   * Delete Notification
   * Delete a notification
   */
  const deleteNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteNotificationResponse,
      DeleteNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications/{id}",
    });
  };

  /**
   * Get Exchange Info
   * Returns a list of all exchanges with their information.
   */
  const getExchangeInfos = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetExchangeInfosResponse,
      GetExchangeInfosError,
      ThrowOnError
    >({
      ...options,
      url: "/exchanges/infos",
    });
  };

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Metrics
   * Get Prometheus metrics for the application. Returns plain text.
   */
  const getMetrics = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetMetricsResponse,
      GetMetricsError,
      ThrowOnError
    >({
      ...options,
      url: "/metrics",
    });
  };

  return {
    getBotOrdersCount,
    getBotsOrdersCount,
    getBotOrdersPnl,
    getBotsOrdersPnl,
    getBotsOrders,
    getBotOrders,
    getBotsActions,
    getBotActions,
    getBots,
    createBot,
    getBot,
    updateBot,
    deleteBot,
    getExchangeKeys,
    createExchangeKey,
    getExchangeKeyBalances,
    getExchangeKeyById,
    deleteExchangeKey,
    updateExchangeKey,
    postFuturesAction,
    postSpotAction,
    getActionsCount,
    getOrdersCount,
    getStrategies,
    createStrategy,
    getStrategyUsage,
    killStrategy,
    updateStrategy,
    getNotifications,
    createNotification,
    updateNotifications,
    deleteNotifications,
    updateNotification,
    deleteNotification,
    getExchangeInfos,
    ping,
    getMetrics,
  };
}
