// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";
import type {
  HealthHealthGetError,
  HealthHealthGetResponse,
  HeartbeatHeartbeatPostData,
  HeartbeatHeartbeatPostError,
  HeartbeatHeartbeatPostResponse,
  GetFuturesBalanceData,
  GetFuturesBalanceError,
  GetFuturesBalanceResponse,
  GetFuturesLedgerData,
  GetFuturesLedgerError,
  GetFuturesLedgerResponse,
  GetHistoricalFuturesOrdersData,
  GetHistoricalFuturesOrdersError,
  GetHistoricalFuturesOrdersResponse,
  PlaceFuturesOrderData,
  PlaceFuturesOrderError,
  PlaceFuturesOrderResponse,
  CancelFuturesOrderData,
  CancelFuturesOrderError,
  CancelFuturesOrderResponse,
  GetOrdersData,
  GetOrdersError,
  GetOrdersResponse,
  GetBotsData,
  GetBotsError,
  GetBotsResponse,
  CreateBotData,
  CreateBotError,
  CreateBotResponse,
  DeleteBotData,
  DeleteBotError,
  DeleteBotResponse,
  UpdateBotData,
  UpdateBotError,
  UpdateBotResponse,
  GetApiKeysData,
  GetApiKeysError,
  GetApiKeysResponse,
  CreateApiKeyData,
  CreateApiKeyError,
  CreateApiKeyResponse,
  DeleteApiKeyData,
  DeleteApiKeyError,
  DeleteApiKeyResponse,
  UpdateApiKeyData,
  UpdateApiKeyError,
  UpdateApiKeyResponse,
  GetStrategiesError,
  GetStrategiesResponse,
  PostFuturesActionActionsFuturesPostData,
  PostFuturesActionActionsFuturesPostError,
  PostFuturesActionActionsFuturesPostResponse,
  PostSpotActionActionsSpotPostData,
  PostSpotActionActionsSpotPostError,
  PostSpotActionActionsSpotPostResponse,
  GetActionsData,
  GetActionsError,
  GetActionsResponse,
} from "./types.gen";
export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  /**
   * Health
   */
  const healthHealthGet = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      HealthHealthGetResponse,
      HealthHealthGetError,
      ThrowOnError
    >({
      ...options,
      url: "/health",
    });
  };

  /**
   * Heartbeat
   */
  const heartbeatHeartbeatPost = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<HeartbeatHeartbeatPostData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      HeartbeatHeartbeatPostResponse,
      HeartbeatHeartbeatPostError,
      ThrowOnError
    >({
      ...options,
      url: "/heartbeat",
    });
  };

  /**
   * Get Futures Balance
   */
  const getFuturesBalance = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetFuturesBalanceData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetFuturesBalanceResponse,
      GetFuturesBalanceError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/balance",
    });
  };

  /**
   * Get Futures Ledger
   */
  const getFuturesLedger = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetFuturesLedgerData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetFuturesLedgerResponse,
      GetFuturesLedgerError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/ledger",
    });
  };

  /**
   * Get Historical Futures Orders
   */
  const getHistoricalFuturesOrders = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetHistoricalFuturesOrdersData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetHistoricalFuturesOrdersResponse,
      GetHistoricalFuturesOrdersError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/historical-orders",
    });
  };

  /**
   * Place Order
   */
  const placeFuturesOrder = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<PlaceFuturesOrderData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      PlaceFuturesOrderResponse,
      PlaceFuturesOrderError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/place-order",
    });
  };

  /**
   * Cancel Order
   */
  const cancelFuturesOrder = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CancelFuturesOrderData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      CancelFuturesOrderResponse,
      CancelFuturesOrderError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/cancel-order",
    });
  };

  /**
   * App Get Orders
   */
  const getOrders = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetOrdersData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetOrdersResponse,
      GetOrdersError,
      ThrowOnError
    >({
      ...options,
      url: "/orders",
    });
  };

  /**
   * Get Bots
   */
  const getBots = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsResponse,
      GetBotsError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Create Bot
   */
  const createBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateBotResponse,
      CreateBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Delete Bot
   */
  const deleteBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteBotResponse,
      DeleteBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Update Bot
   */
  const updateBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateBotResponse,
      UpdateBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * App Get Api Keys
   */
  const getApiKeys = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetApiKeysData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetApiKeysResponse,
      GetApiKeysError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys",
    });
  };

  /**
   * App Post Api Key
   */
  const createApiKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateApiKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateApiKeyResponse,
      CreateApiKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-key",
    });
  };

  /**
   * App Delete Api Key
   */
  const deleteApiKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteApiKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteApiKeyResponse,
      DeleteApiKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-key",
    });
  };

  /**
   * App Put Api Key
   */
  const updateApiKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateApiKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateApiKeyResponse,
      UpdateApiKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-key",
    });
  };

  /**
   * Get Strategies
   */
  const getStrategies = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetStrategiesResponse,
      GetStrategiesError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies",
    });
  };

  /**
   * Post Futures Action
   */
  const postFuturesActionActionsFuturesPost = <
    ThrowOnError extends boolean = false,
  >(
    options: OptionsLegacyParser<
      PostFuturesActionActionsFuturesPostData,
      ThrowOnError
    >,
  ) => {
    return (options?.client ?? client).post<
      PostFuturesActionActionsFuturesPostResponse,
      PostFuturesActionActionsFuturesPostError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/futures",
    });
  };

  /**
   * Post Spot Action
   */
  const postSpotActionActionsSpotPost = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<
      PostSpotActionActionsSpotPostData,
      ThrowOnError
    >,
  ) => {
    return (options?.client ?? client).post<
      PostSpotActionActionsSpotPostResponse,
      PostSpotActionActionsSpotPostError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/spot",
    });
  };

  /**
   * Get Actions
   */
  const getActions = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetActionsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetActionsResponse,
      GetActionsError,
      ThrowOnError
    >({
      ...options,
      url: "/actions",
    });
  };

  return {
    healthHealthGet,
    heartbeatHeartbeatPost,
    getFuturesBalance,
    getFuturesLedger,
    getHistoricalFuturesOrders,
    placeFuturesOrder,
    cancelFuturesOrder,
    getOrders,
    getBots,
    createBot,
    deleteBot,
    updateBot,
    getApiKeys,
    createApiKey,
    deleteApiKey,
    updateApiKey,
    getStrategies,
    postFuturesActionActionsFuturesPost,
    postSpotActionActionsSpotPost,
    getActions,
  };
}
