import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  PingError,
  PingResponse,
  GetTimeData,
  GetTimeError,
  GetTimeResponse,
  GetBotsData,
  GetBotsError,
  GetBotsResponse,
  CreateBotData,
  CreateBotError,
  CreateBotResponse,
  GetBotData,
  GetBotError,
  GetBotResponse,
  UpdateBotData,
  UpdateBotError,
  UpdateBotResponse,
  DeleteBotData,
  DeleteBotError,
  DeleteBotResponse,
  GetExchangeKeysData,
  GetExchangeKeysError,
  GetExchangeKeysResponse,
  CreateExchangeKeyData,
  CreateExchangeKeyError,
  CreateExchangeKeyResponse,
  GetExchangeKeyByIdData,
  GetExchangeKeyByIdError,
  GetExchangeKeyByIdResponse,
  DeleteExchangeKeyData,
  DeleteExchangeKeyError,
  DeleteExchangeKeyResponse,
  UpdateExchangeKeyData,
  UpdateExchangeKeyError,
  UpdateExchangeKeyResponse,
  PostFuturesActionData,
  PostFuturesActionError,
  PostFuturesActionResponse,
  PostSpotActionData,
  PostSpotActionError,
  PostSpotActionResponse,
  GetActionsData,
  GetActionsError,
  GetActionsResponse,
  GetOrdersData,
  GetOrdersError,
  GetOrdersResponse,
  GetFuturesBalanceError,
  GetFuturesBalanceResponse,
  GetFuturesLedgerData,
  GetFuturesLedgerError,
  GetFuturesLedgerResponse,
  GetHistoricalFuturesOrdersData,
  GetHistoricalFuturesOrdersError,
  GetHistoricalFuturesOrdersResponse,
  PlaceFuturesOrderData,
  PlaceFuturesOrderError,
  PlaceFuturesOrderResponse,
  CancelFuturesOrderData,
  CancelFuturesOrderError,
  CancelFuturesOrderResponse,
  GetStrategiesData,
  GetStrategiesError,
  GetStrategiesResponse,
  CreateStrategyData,
  CreateStrategyError,
  CreateStrategyResponse,
  KillStrategyData,
  KillStrategyError,
  KillStrategyResponse,
  UpdateStrategyData,
  UpdateStrategyError,
  UpdateStrategyResponse,
  GetNotificationsData,
  GetNotificationsError,
  GetNotificationsResponse,
  CreateNotificationData,
  CreateNotificationError,
  CreateNotificationResponse,
  UpdateNotificationsData,
  UpdateNotificationsError,
  UpdateNotificationsResponse,
  DeleteNotificationsError,
  DeleteNotificationsResponse,
  UpdateNotificationData,
  UpdateNotificationError,
  UpdateNotificationResponse,
  DeleteNotificationData,
  DeleteNotificationError,
  DeleteNotificationResponse,
  GetTradeableExchangesError,
  GetTradeableExchangesResponse,
  GetPlannedExchangesError,
  GetPlannedExchangesResponse,
  GetAllExchangesError,
  GetAllExchangesResponse,
  GetLogLevelError,
  GetLogLevelResponse,
  GetUptimeData,
  GetUptimeError,
  GetUptimeResponse,
  GetMemoryUsageError,
  GetMemoryUsageResponse,
  GetThreadsError,
  GetThreadsResponse,
  GetContainerLimitsError,
  GetContainerLimitsResponse,
  GetDependenciesData,
  GetDependenciesError,
  GetDependenciesResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Time
   * Returns the current time in either ISO or Unix timestamp (seconds) format.
   */
  const getTime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetTimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTimeResponse,
      GetTimeError,
      ThrowOnError
    >({
      ...options,
      url: "/time",
    });
  };

  /**
   * Get Bots
   */
  const getBots = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetBotsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotsResponse,
      GetBotsError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Create Bot
   * Creates a new bot.
   */
  const createBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateBotResponse,
      CreateBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots",
    });
  };

  /**
   * Get Bot
   */
  const getBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetBotResponse,
      GetBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}",
    });
  };

  /**
   * Update Bot
   * Updates a bot.
   */
  const updateBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateBotResponse,
      UpdateBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}",
    });
  };

  /**
   * Delete Bot
   * Soft deletes a bot by cancelling all orders and closing all positions.
   */
  const deleteBot = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteBotData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteBotResponse,
      DeleteBotError,
      ThrowOnError
    >({
      ...options,
      url: "/bots/{id}",
    });
  };

  /**
   * Get Exchange Keys
   */
  const getExchangeKeys = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetExchangeKeysData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetExchangeKeysResponse,
      GetExchangeKeysError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys",
    });
  };

  /**
   * Post Exchange Key
   */
  const createExchangeKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateExchangeKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateExchangeKeyResponse,
      CreateExchangeKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys",
    });
  };

  /**
   * Get Exchange Key By Id
   */
  const getExchangeKeyById = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetExchangeKeyByIdData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetExchangeKeyByIdResponse,
      GetExchangeKeyByIdError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/{id}",
    });
  };

  /**
   * Delete Exchange Key
   */
  const deleteExchangeKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteExchangeKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteExchangeKeyResponse,
      DeleteExchangeKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/{id}",
    });
  };

  /**
   * Put Exchange Key
   */
  const updateExchangeKey = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateExchangeKeyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateExchangeKeyResponse,
      UpdateExchangeKeyError,
      ThrowOnError
    >({
      ...options,
      url: "/api-keys/{id}",
    });
  };

  /**
   * Post Futures Action
   * Endpoint to receive futures trading actions from the trading strategy
   */
  const postFuturesAction = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<PostFuturesActionData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      PostFuturesActionResponse,
      PostFuturesActionError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/futures",
    });
  };

  /**
   * Post Spot Action
   */
  const postSpotAction = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<PostSpotActionData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      PostSpotActionResponse,
      PostSpotActionError,
      ThrowOnError
    >({
      ...options,
      url: "/actions/spot",
    });
  };

  /**
   * Get Actions
   */
  const getActions = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetActionsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetActionsResponse,
      GetActionsError,
      ThrowOnError
    >({
      ...options,
      url: "/actions",
    });
  };

  /**
   * Get Orders
   */
  const getOrders = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetOrdersData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetOrdersResponse,
      GetOrdersError,
      ThrowOnError
    >({
      ...options,
      url: "/orders",
    });
  };

  /**
   * Get Futures Balance
   */
  const getFuturesBalance = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetFuturesBalanceResponse,
      GetFuturesBalanceError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/balance",
    });
  };

  /**
   * Get Futures Ledger
   */
  const getFuturesLedger = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetFuturesLedgerData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetFuturesLedgerResponse,
      GetFuturesLedgerError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/ledger",
    });
  };

  /**
   * Get Historical Futures Orders
   */
  const getHistoricalFuturesOrders = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetHistoricalFuturesOrdersData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetHistoricalFuturesOrdersResponse,
      GetHistoricalFuturesOrdersError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/orders",
    });
  };

  /**
   * Place Order
   */
  const placeFuturesOrder = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<PlaceFuturesOrderData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      PlaceFuturesOrderResponse,
      PlaceFuturesOrderError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/orders",
    });
  };

  /**
   * Cancel Order
   */
  const cancelFuturesOrder = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CancelFuturesOrderData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      CancelFuturesOrderResponse,
      CancelFuturesOrderError,
      ThrowOnError
    >({
      ...options,
      url: "/futures/orders",
    });
  };

  /**
   * Get Strategies
   */
  const getStrategies = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetStrategiesData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetStrategiesResponse,
      GetStrategiesError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies",
    });
  };

  /**
   * Create Strategy
   */
  const createStrategy = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateStrategyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateStrategyResponse,
      CreateStrategyError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies",
    });
  };

  /**
   * Kill Strategy
   * Kills a strategy by disabling it and deleting all bots associated with it.
   */
  const killStrategy = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<KillStrategyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      KillStrategyResponse,
      KillStrategyError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies/{id}",
    });
  };

  /**
   * Update Strategy
   * Updates a strategy. If the strategy is being disabled, all bots associated with it will be set to stopping.
   */
  const updateStrategy = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateStrategyData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateStrategyResponse,
      UpdateStrategyError,
      ThrowOnError
    >({
      ...options,
      url: "/strategies/{id}",
    });
  };

  /**
   * Get Notifications
   * Get all notifications for the authenticated user
   */
  const getNotifications = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetNotificationsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetNotificationsResponse,
      GetNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Create Notification
   * Create a new notification
   */
  const createNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateNotificationResponse,
      CreateNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Update Notifications
   * Bulk update notifications
   */
  const updateNotifications = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateNotificationsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateNotificationsResponse,
      UpdateNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Delete Notifications
   * Delete all notifications for the authenticated user
   */
  const deleteNotifications = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteNotificationsResponse,
      DeleteNotificationsError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications",
    });
  };

  /**
   * Update Notification
   * Update a notification's viewed status
   */
  const updateNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateNotificationResponse,
      UpdateNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications/{id}",
    });
  };

  /**
   * Delete Notification
   */
  const deleteNotification = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteNotificationData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteNotificationResponse,
      DeleteNotificationError,
      ThrowOnError
    >({
      ...options,
      url: "/notifications/{id}",
    });
  };

  /**
   * Get Tradeable Exchanges
   * Returns a list of exchanges that are tradeable.
   */
  const getTradeableExchanges = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTradeableExchangesResponse,
      GetTradeableExchangesError,
      ThrowOnError
    >({
      ...options,
      url: "/exchanges/tradeable",
    });
  };

  /**
   * Get Planned Exchanges
   * Returns a list of exchanges that are planned to be added for trading.
   */
  const getPlannedExchanges = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetPlannedExchangesResponse,
      GetPlannedExchangesError,
      ThrowOnError
    >({
      ...options,
      url: "/exchanges/planned",
    });
  };

  /**
   * Get All Exchanges
   * Returns a list of all exchanges.
   */
  const getAllExchanges = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetAllExchangesResponse,
      GetAllExchangesError,
      ThrowOnError
    >({
      ...options,
      url: "/exchanges",
    });
  };

  /**
   * @deprecated
   * Get Logging Level
   * Get the log level of the server logger. Will be removed in a future release.
   */
  const getLogLevel = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetLogLevelResponse,
      GetLogLevelError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/log-level",
    });
  };

  /**
   * Get Uptime
   * Return the server uptime in seconds or human-readable form.
   */
  const getUptime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetUptimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetUptimeResponse,
      GetUptimeError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/uptime",
    });
  };

  /**
   * Get Memory Usage
   * Resident Set Size (RSS) in MB — the actual memory used by the process in RAM.
   * Represents the physical memory footprint. Important for monitoring real usage.
   */
  const getMemoryUsage = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetMemoryUsageResponse,
      GetMemoryUsageError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/memory",
    });
  };

  /**
   * Get Threads
   * Return count and names of active threads.
   */
  const getThreads = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetThreadsResponse,
      GetThreadsError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/threads",
    });
  };

  /**
   * Get Container Limits
   * Return container resource limits from cgroup.
   */
  const getContainerLimits = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetContainerLimitsResponse,
      GetContainerLimitsError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/limits",
    });
  };

  /**
   * List Installed Packages
   * Return a list of installed packages and versions.
   *
   * The include parameter accepts regex patterns to match against package names.
   * For example:
   * - crypticorn.* will match all packages starting with 'crypticorn'
   * - .*tic.* will match all packages containing 'tic' in their name
   */
  const getDependencies = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetDependenciesData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetDependenciesResponse,
      GetDependenciesError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/dependencies",
    });
  };

  return {
    ping,
    getTime,
    getBots,
    createBot,
    getBot,
    updateBot,
    deleteBot,
    getExchangeKeys,
    createExchangeKey,
    getExchangeKeyById,
    deleteExchangeKey,
    updateExchangeKey,
    postFuturesAction,
    postSpotAction,
    getActions,
    getOrders,
    getFuturesBalance,
    getFuturesLedger,
    getHistoricalFuturesOrders,
    placeFuturesOrder,
    cancelFuturesOrder,
    getStrategies,
    createStrategy,
    killStrategy,
    updateStrategy,
    getNotifications,
    createNotification,
    updateNotifications,
    deleteNotifications,
    updateNotification,
    deleteNotification,
    getTradeableExchanges,
    getPlannedExchanges,
    getAllExchanges,
    getLogLevel,
    getUptime,
    getMemoryUsage,
    getThreads,
    getContainerLimits,
    getDependencies,
  };
}
