// This file is auto-generated by @hey-api/openapi-ts

export type ActionModel = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * Placeholder for the id of the trading action. Will be added by the system, therefore leave empty.
   */
  id?: string | null;
  /**
   * UID for the execution of the order. Leave empty for open actions. Required on close actions if you have placed a TP/SL before. A specific TP/SL execution ID of the opening order. The allocation should match the TP/SL allocation you set.
   */
  execution_id?: string | null;
  /**
   * UID for the order to close. Leave empty for open actions. Required on close actions. The main execution ID of the opening order.
   */
  open_order_execution_id?: string | null;
  /**
   * UID for the client order. Leave empty.
   */
  client_order_id?: string | null;
  /**
   * The type of action.
   */
  action_type: TradingActionType;
  /**
   * The type of market the action is for.
   */
  market_type: MarketType;
  /**
   * UID for the strategy.
   */
  strategy_id: string;
  /**
   * Trading symbol or asset pair in format: 'symbol/quote_currency' (see market service for valid symbols)
   */
  symbol: string;
  /**
   * Whether this is a limit order.
   */
  is_limit?: boolean | null;
  /**
   * The limit price for limit orders. If not set, the market price will be used.
   */
  limit_price?: number | null;
  /**
   * How much of bot's balance to use for the order (for open actions). How much of the reference open order (open_order_execution_id) to close (for close actions). 0=0%, 1=100%.
   */
  allocation?: number;
  /**
   * Take profit targets. Can be set for open actions only. Multiple can be set.
   */
  take_profit?: Array<TPSL> | null;
  /**
   * Stop loss values. Can be set for open actions only. Multiple can be set.
   */
  stop_loss?: Array<TPSL> | null;
  /**
   * Timestamp of when the order will expire. If not set, the order will not expire. Applied on each bot individually.
   */
  expiry_timestamp?: number | null;
  /**
   * Extra Field. UID for the position to close. Leave empty.
   */
  position_id?: string | null;
  /**
   * Leverage to use for futures trades.
   */
  leverage: number | null;
  /**
   * Margin mode for futures trades.
   */
  margin_mode?: MarginMode | null;
};

/**
 * API error identifiers
 */
export type ApiErrorIdentifier = string;

/**
 * API error levels
 */
export type ApiErrorLevel = string;

/**
 * Type of API error
 */
export type ApiErrorType = string;

export type BotModel = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * UID, used as a placeholder in the response body
   */
  id?: string | null;
  /**
   * Name of the bot
   */
  name: string;
  /**
   * UID for the trading strategy used by the bot
   */
  strategy_id: string;
  /**
   * UID for the API key
   */
  api_key_id: string;
  /**
   * Initial allocation for the bot
   */
  allocation: number;
  /**
   * Status of the bot
   */
  status: BotStatus;
  /**
   * Status code of the bot. Set if the bot is stopped by an error.
   */
  status_code?: ApiErrorIdentifier | null;
  /**
   * UID for the user
   */
  user_id?: string | null;
  /**
   * Initial allocation for the bot + accumulated PnL of the orders after the last allocation change
   */
  current_allocation?: number | null;
  /**
   * Current exposure of the bot, aka. the sum of the absolute values of the open positions
   */
  current_exposure?: number | null;
};

export type BotStatus = "running" | "stopping" | "stopped" | "deleted";

/**
 * This is the detail of the exception. It is used to enrich the exception with additional information by unwrapping the ApiError into its components.
 */
export type ExceptionDetail = {
  /**
   * An additional error message
   */
  message?: string | null;
  /**
   * The unique error code
   */
  code: ApiErrorIdentifier;
  /**
   * The type of error
   */
  type: ApiErrorType;
  /**
   * The level of the error
   */
  level: ApiErrorLevel;
  /**
   * The HTTP status code
   */
  status_code: number;
  /**
   * Additional details about the error
   */
  details?: unknown;
};

/**
 * Supported exchanges for trading
 */
export type Exchange = string;

export type ExchangeKeyModel = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * UID, used as a placeholder in the response body
   */
  id?: string | null;
  /**
   * Exchange name
   */
  exchange: Exchange;
  /**
   * API key
   */
  api_key?: string | null;
  /**
   * API secret
   */
  secret?: string | null;
  /**
   * API passphrase
   */
  passphrase?: string | null;
  /**
   * Label for the API key
   */
  label: string;
  /**
   * UID for the user
   */
  user_id?: string | null;
};

export type ExecutionIds = {
  /**
   * Main execution ID.
   */
  main: string;
  /**
   * Stop loss execution IDs. List with multiple items ordered by the next stop loss, e.g. price = 10000 => SLs: ['900', '700', '500'].
   */
  sl: Array<string>;
  /**
   * Take profit execution IDs. List with multiple items ordered by the next take profit, e.g. price = 10000 => TPs: ['1100', '1300', '1500'].
   */
  tp: Array<string>;
};

/**
 * Model for futures balance
 */
export type FuturesBalance = {
  /**
   * API key ID
   */
  apiKeyId: string;
  /**
   * Asset/Currency code
   */
  asset: string;
  /**
   * Total balance/equity
   */
  balance: number;
  /**
   * Available balance for trading/withdrawal
   */
  available: number;
  /**
   * Unrealized profit and loss
   */
  unrealizedPnl: number;
  /**
   * Used/Position margin
   */
  usedMargin?: number | null;
  /**
   * Frozen/Hold funds
   */
  frozenAmount?: number | null;
};

/**
 * Model for futures trading actions
 */
export type FuturesTradingAction = {
  /**
   * Placeholder for the id of the trading action. Will be added by the system, therefore leave empty.
   */
  id?: string | null;
  /**
   * UID for the execution of the order. Leave empty for open actions. Required on close actions if you have placed a TP/SL before. A specific TP/SL execution ID of the opening order. The allocation should match the TP/SL allocation you set.
   */
  execution_id?: string | null;
  /**
   * UID for the order to close. Leave empty for open actions. Required on close actions. The main execution ID of the opening order.
   */
  open_order_execution_id?: string | null;
  /**
   * UID for the client order. Leave empty.
   */
  client_order_id?: string | null;
  /**
   * The type of action.
   */
  action_type: TradingActionType;
  /**
   * The type of market the action is for.
   */
  market_type: MarketType;
  /**
   * UID for the strategy.
   */
  strategy_id: string;
  /**
   * Trading symbol or asset pair in format: 'symbol/quote_currency' (see market service for valid symbols)
   */
  symbol: string;
  /**
   * Whether this is a limit order.
   */
  is_limit?: boolean | null;
  /**
   * The limit price for limit orders. If not set, the market price will be used.
   */
  limit_price?: number | null;
  /**
   * How much of bot's balance to use for the order (for open actions). How much of the reference open order (open_order_execution_id) to close (for close actions). 0=0%, 1=100%.
   */
  allocation?: number;
  /**
   * Take profit targets. Can be set for open actions only. Multiple can be set.
   */
  take_profit?: Array<TPSL> | null;
  /**
   * Stop loss values. Can be set for open actions only. Multiple can be set.
   */
  stop_loss?: Array<TPSL> | null;
  /**
   * Timestamp of when the order will expire. If not set, the order will not expire. Applied on each bot individually.
   */
  expiry_timestamp?: number | null;
  /**
   * Extra Field. UID for the position to close. Leave empty.
   */
  position_id?: string | null;
  /**
   * Leverage to use for futures trades.
   */
  leverage: number | null;
  /**
   * Margin mode for futures trades.
   */
  margin_mode?: MarginMode | null;
};

/**
 * Margin mode for futures trades
 */
export type MarginMode = "isolated" | "cross";

/**
 * Market types
 */
export type MarketType = string;

export type NotificationModel = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * UID, used as a placeholder in the response body
   */
  id?: string | null;
  /**
   * Identifier string. Must match the mapping key in the frontend.
   */
  identifier: ApiErrorIdentifier;
  /**
   * Level of the notification. Of type ApiErrorLevel
   */
  level: ApiErrorLevel;
  /**
   * Type of the notification. Of type ApiErrorType
   */
  type: ApiErrorType;
  /**
   * UID for the user. None for all users.
   */
  user_id?: string | null;
  /**
   * Whether the notification has been marked as seen
   */
  viewed?: boolean;
  /**
   * Whether the notification has been sent as an email
   */
  sent?: boolean;
};

/**
 * Response model for orders. All optional as the model is built step by step.
 */
export type OrderModel = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * UID, used as a placeholder in the response body
   */
  id?: string | null;
  /**
   * UID for the trading action that placed the order
   */
  trading_action_id?: string | null;
  /**
   * UID for the execution (not unique to the bot)
   */
  execution_id?: string | null;
  /**
   * UID for the order on the exchange
   */
  exchange_order_id?: string | null;
  /**
   * UID for the position on the exchange
   */
  position_id?: string | null;
  /**
   * UID for the API key
   */
  api_key_id?: string | null;
  /**
   * UID for the user
   */
  user_id?: string | null;
  /**
   * UID for the bot
   */
  bot_id?: string | null;
  /**
   * Client order ID
   */
  client_order_id?: string | null;
  /**
   * Exchange name. Of type Exchange
   */
  exchange?: Exchange | null;
  /**
   * Trading symbol on exchange
   */
  symbol?: string | null;
  /**
   * Common trading symbol
   */
  common_symbol?: string | null;
  /**
   * Price of the order
   */
  price?: number | null;
  /**
   * Type of trading action. Of type TradingActionType
   */
  action_type?: TradingActionType | null;
  /**
   * Market type of the order. Of type MarketType
   */
  market_type?: MarketType | null;
  /**
   * Margin mode of the order. Of type MarginMode
   */
  margin_mode?: MarginMode | null;
  /**
   * API error identifier. Of type ApiErrorIdentifier
   */
  status_code?: ApiErrorIdentifier | null;
  /**
   * Trade status of the order. Of type OrderStatus
   */
  status?: OrderStatus | null;
  /**
   * Percentage of the order filled
   */
  filled_perc?: number | null;
  /**
   * Quantity filled. Needed for pnl calculation. In the symbol's base currency.
   */
  filled_qty?: number | null;
  /**
   * Fees for the order
   */
  fee?: number | null;
  /**
   * Leverage for the order
   */
  leverage?: number | null;
  /**
   * Exchange specific details of the order
   */
  order_details?: unknown | null;
  /**
   * Profit and loss for the order
   */
  pnl?: number | null;
  /**
   * Timestamp of order creation on the exchange.
   */
  order_time?: number | null;
};

/**
 * Status of the order
 */
export type OrderStatus =
  | "new"
  | "filled"
  | "partially_filled"
  | "cancelled"
  | "failed";

export type PostFuturesAction = {
  /**
   * Action ID.
   */
  id: string;
  /**
   * Execution IDs for the action.
   */
  execution_ids: ExecutionIds;
};

/**
 * Model for spot trading actions
 */
export type SpotTradingAction = {
  /**
   * Placeholder for the id of the trading action. Will be added by the system, therefore leave empty.
   */
  id?: string | null;
  /**
   * UID for the execution of the order. Leave empty for open actions. Required on close actions if you have placed a TP/SL before. A specific TP/SL execution ID of the opening order. The allocation should match the TP/SL allocation you set.
   */
  execution_id?: string | null;
  /**
   * UID for the order to close. Leave empty for open actions. Required on close actions. The main execution ID of the opening order.
   */
  open_order_execution_id?: string | null;
  /**
   * UID for the client order. Leave empty.
   */
  client_order_id?: string | null;
  /**
   * The type of action.
   */
  action_type: TradingActionType;
  /**
   * The type of market the action is for.
   */
  market_type: MarketType;
  /**
   * UID for the strategy.
   */
  strategy_id: string;
  /**
   * Trading symbol or asset pair in format: 'symbol/quote_currency' (see market service for valid symbols)
   */
  symbol: string;
  /**
   * Whether this is a limit order.
   */
  is_limit?: boolean | null;
  /**
   * The limit price for limit orders. If not set, the market price will be used.
   */
  limit_price?: number | null;
  /**
   * How much of bot's balance to use for the order (for open actions). How much of the reference open order (open_order_execution_id) to close (for close actions). 0=0%, 1=100%.
   */
  allocation?: number;
  /**
   * Take profit targets. Can be set for open actions only. Multiple can be set.
   */
  take_profit?: Array<TPSL> | null;
  /**
   * Stop loss values. Can be set for open actions only. Multiple can be set.
   */
  stop_loss?: Array<TPSL> | null;
  /**
   * Timestamp of when the order will expire. If not set, the order will not expire. Applied on each bot individually.
   */
  expiry_timestamp?: number | null;
  /**
   * Extra Field. UID for the position to close. Leave empty.
   */
  position_id?: string | null;
};

export type StrategyExchangeInfo = {
  /**
   * Exchange name. Of type Exchange
   */
  exchange: Exchange;
  /**
   * Minimum amount for the strategy on the exchange
   */
  min_amount: number;
};

export type StrategyModel_Input = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * UID, used as a placeholder in the response body
   */
  id?: string | null;
  /**
   * Unique human readable identifier for the strategy e.g. 'daily_trend_momentum'
   */
  identifier: string;
  /**
   * Name of the strategy
   */
  name: string;
  /**
   * Description of the strategy
   */
  description: string;
  /**
   * Exchanges supported by the strategy.
   */
  exchanges: Array<StrategyExchangeInfo>;
  /**
   * Whether the strategy is enabled. If false, no bots will be created or updated for this strategy, open trades will be rejected. Existing bots will be marked as stopping.
   */
  enabled: boolean;
  /**
   * Leverage for the strategy
   */
  leverage: number;
  /**
   * Performance fee for the strategy
   */
  performance_fee: number;
  /**
   * Market of operation of the strategy
   */
  market_type: MarketType;
};

export type StrategyModel_Output = {
  /**
   * Timestamp of creation
   */
  created_at?: number | null;
  /**
   * Timestamp of last update
   */
  updated_at?: number | null;
  /**
   * UID, used as a placeholder in the response body
   */
  id?: string | null;
  /**
   * Unique human readable identifier for the strategy e.g. 'daily_trend_momentum'
   */
  identifier: string;
  /**
   * Name of the strategy
   */
  name: string;
  /**
   * Description of the strategy
   */
  description: string;
  /**
   * Exchanges supported by the strategy.
   */
  exchanges: Array<StrategyExchangeInfo>;
  /**
   * Whether the strategy is enabled. If false, no bots will be created or updated for this strategy, open trades will be rejected. Existing bots will be marked as stopping.
   */
  enabled: boolean;
  /**
   * Leverage for the strategy
   */
  leverage: number;
  /**
   * Performance fee for the strategy
   */
  performance_fee: number;
  /**
   * Market of operation of the strategy
   */
  market_type: MarketType;
};

/**
 * Model for take profit and stop loss targets
 */
export type TPSL = {
  /**
   * The price delta to calculate the limit price from the current market price, e.g. for a SL of 1% the it would be 0.99
   */
  price_delta?: number | null;
  /**
   * The limit price to set the target at. If not set, the limit price will be calculated from the current market price.
   */
  price?: number | null;
  /**
   * Percentage of the open order to sell. All allocations must sum up to 1.
   */
  allocation: number;
  /**
   * Execution ID of the order. Leave empty.
   */
  execution_id?: string | null;
  /**
   * Client order ID of the order. Leave empty.
   */
  client_order_id?: string | null;
};

/**
 * Type of trading action
 */
export type TradingActionType =
  | "open_long"
  | "open_short"
  | "close_long"
  | "close_short";

export type PingResponse = string;

export type PingError = ExceptionDetail;

export type GetTimeData = {
  query?: {
    type?: "iso" | "unix";
  };
};

export type GetTimeResponse = string;

export type GetTimeError = ExceptionDetail;

export type GetConfigResponse = {
  [key: string]: unknown;
};

export type GetConfigError = ExceptionDetail;

export type GetBotsData = {
  query?: {
    include_deleted?: boolean;
    limit?: number;
    offset?: number;
  };
};

export type GetBotsResponse = Array<BotModel>;

export type GetBotsError = ExceptionDetail;

export type CreateBotData = {
  body: BotModel;
};

export type CreateBotResponse = unknown;

export type CreateBotError = ExceptionDetail;

export type UpdateBotData = {
  body: BotModel;
  path: {
    id: string;
  };
};

export type UpdateBotResponse = unknown;

export type UpdateBotError = ExceptionDetail;

export type DeleteBotData = {
  path: {
    id: string;
  };
};

export type DeleteBotResponse = void;

export type DeleteBotError = ExceptionDetail;

export type GetExchangeKeysData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetExchangeKeysResponse = Array<ExchangeKeyModel>;

export type GetExchangeKeysError = ExceptionDetail;

export type CreateExchangeKeyData = {
  body: ExchangeKeyModel;
};

export type CreateExchangeKeyResponse = unknown;

export type CreateExchangeKeyError = ExceptionDetail;

export type GetExchangeKeyByIdData = {
  path: {
    id: string;
  };
};

export type GetExchangeKeyByIdResponse = ExchangeKeyModel;

export type GetExchangeKeyByIdError = ExceptionDetail;

export type DeleteExchangeKeyData = {
  path: {
    id: string;
  };
};

export type DeleteExchangeKeyResponse = unknown;

export type DeleteExchangeKeyError = ExceptionDetail;

export type UpdateExchangeKeyData = {
  body: ExchangeKeyModel;
  path: {
    id: string;
  };
};

export type UpdateExchangeKeyResponse = unknown;

export type UpdateExchangeKeyError = ExceptionDetail;

export type PostFuturesActionData = {
  body: FuturesTradingAction;
};

export type PostFuturesActionResponse = PostFuturesAction;

export type PostFuturesActionError = ExceptionDetail;

export type PostSpotActionData = {
  body: SpotTradingAction;
};

export type PostSpotActionResponse = unknown;

export type PostSpotActionError = ExceptionDetail;

export type GetActionsData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetActionsResponse = Array<ActionModel>;

export type GetActionsError = ExceptionDetail;

export type GetOrdersData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetOrdersResponse = Array<OrderModel>;

export type GetOrdersError = ExceptionDetail;

export type GetFuturesBalanceResponse = Array<FuturesBalance>;

export type GetFuturesBalanceError = ExceptionDetail;

export type GetFuturesLedgerData = {
  query: {
    key: string;
  };
};

export type GetFuturesLedgerResponse = unknown;

export type GetFuturesLedgerError = ExceptionDetail;

export type GetHistoricalFuturesOrdersData = {
  query: {
    key: string;
  };
};

export type GetHistoricalFuturesOrdersResponse = unknown;

export type GetHistoricalFuturesOrdersError = ExceptionDetail;

export type PlaceFuturesOrderData = {
  body: {
    [key: string]: unknown;
  };
  query: {
    key: string;
  };
};

export type PlaceFuturesOrderResponse = unknown;

export type PlaceFuturesOrderError = ExceptionDetail;

export type CancelFuturesOrderData = {
  query: {
    key: string;
    orderId: string;
    symbol: string;
  };
};

export type CancelFuturesOrderResponse = void;

export type CancelFuturesOrderError = ExceptionDetail;

export type GetStrategiesData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetStrategiesResponse = Array<StrategyModel_Output>;

export type GetStrategiesError = ExceptionDetail;

export type CreateStrategyData = {
  body: StrategyModel_Input;
};

export type CreateStrategyResponse = unknown;

export type CreateStrategyError = ExceptionDetail;

export type KillStrategyData = {
  path: {
    id: string;
  };
};

export type KillStrategyResponse = unknown;

export type KillStrategyError = ExceptionDetail;

export type UpdateStrategyData = {
  body: StrategyModel_Input;
  path: {
    id: string;
  };
};

export type UpdateStrategyResponse = unknown;

export type UpdateStrategyError = ExceptionDetail;

export type GetNotificationsData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetNotificationsResponse = Array<NotificationModel>;

export type GetNotificationsError = ExceptionDetail;

export type CreateNotificationData = {
  body: NotificationModel;
};

export type CreateNotificationResponse = unknown;

export type CreateNotificationError = ExceptionDetail;

export type UpdateNotificationsData = {
  query: {
    sent: boolean;
    viewed: boolean;
  };
};

export type UpdateNotificationsResponse = unknown;

export type UpdateNotificationsError = ExceptionDetail;

export type DeleteNotificationsResponse = unknown;

export type DeleteNotificationsError = ExceptionDetail;

export type UpdateNotificationData = {
  path: {
    id: string;
  };
  query: {
    sent: boolean;
    viewed: boolean;
  };
};

export type UpdateNotificationResponse = unknown;

export type UpdateNotificationError = ExceptionDetail;

export type DeleteNotificationData = {
  path: {
    id: string;
  };
};

export type DeleteNotificationResponse = void;

export type DeleteNotificationError = ExceptionDetail;

export type GetExchangesResponse = Array<Exchange>;

export type GetExchangesError = ExceptionDetail;
