// This file is auto-generated by @hey-api/openapi-ts

/**
 * API error codes
 */
export type ApiError = unknown[];

export type APIKeyModel = {
  /**
   * Unique identifier for the API key
   */
  id?: string | null;
  /**
   * Exchange name
   */
  exchange: string;
  /**
   * API key
   */
  api_key: string;
  /**
   * API secret
   */
  secret: string;
  /**
   * API passphrase
   */
  passphrase?: string | null;
  /**
   * Label for the API key
   */
  label: string;
  /**
   * Status of the API key
   */
  enabled?: boolean;
  /**
   * Timestamp of creation
   */
  created_at?: number;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
};

export type BotModel = {
  /**
   * Name of the bot
   */
  name: string;
  /**
   * Name of the strategy used by the bot
   */
  strategy_name: string;
  /**
   * Unique identifier for the API key
   */
  api_key_id: string;
  /**
   * Allocation for the bot
   */
  allocation: number;
  /**
   * Status of the bot
   */
  enabled: boolean;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
};

export type DeleteAPIKey = {
  /**
   * Unique identifier for the API key
   */
  id: string;
};

/**
 * Model for futures trading actions
 */
export type FuturesTradingAction = {
  /**
   * Unique identifier for the trading action in our system
   */
  id: string;
  /**
   * Unique identifier for the trade in our system. This is the same for the opening and closing trading action.
   */
  trade_id: string;
  /**
   * The type of action: buy, sell, etc.
   */
  action_type: TradingActionType;
  /**
   * Market type: either spot or futures
   */
  market_type: MarketType;
  /**
   * Unique identifier for the strategy
   */
  strategy_id: string;
  /**
   * Timestamp of when the action was created on the client side
   */
  client_timestamp: number;
  /**
   * Trading symbol or asset pair (e.g., 'BTC/USDT')
   */
  symbol: string;
  /**
   * Current price of the symbol at the time of action creation
   */
  symbol_price: number;
  /**
   * Whether this is a limit order
   */
  is_limit?: boolean | null;
  /**
   * The limit price for limit orders
   */
  limit_price?: number | null;
  /**
   * Allocation for the order
   */
  allocation?: number;
  /**
   * Whether the order has a stop loss
   */
  has_stop_loss?: boolean;
  /**
   * Whether the order has a take profit
   */
  has_take_profit?: boolean;
  /**
   * Take profit targets: buy/sell
   */
  take_profit_targets?: Array<{
    [key: string]: number;
  }> | null;
  /**
   * Stop loss values: buy/sell
   */
  stop_loss_values?: Array<{
    [key: string]: number;
  }> | null;
  /**
   * Leverage to use for futures trades, optional for spot
   */
  leverage: number | null;
  /**
   * Margin mode for futures trades: either isolated or cross, default is isolated
   */
  margin_mode?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * Type of market
 */
export type MarketType = "spot" | "futures";

/**
 * Response model for orders. Inherits ids from OrderInfo
 */
export type OrderModel = {
  /**
   * Unique identifier for the order in the exchange
   */
  order_id: string;
  /**
   * Unique identifier for the order in our system
   */
  client_order_id: string;
  /**
   * Unique identifier for the trade in our system
   */
  trade_id: string;
  /**
   * Unique identifier for the API key
   */
  api_key_id: string;
  /**
   * Unique identifier for the user
   */
  user_id: string;
  /**
   * Unique identifier for the bot
   */
  bot_id: string;
  /**
   * Unique identifier for the trading action
   */
  trading_action_id: string;
  /**
   * Exchange name
   */
  exchange: string;
  /**
   * Trading symbol
   */
  symbol: string;
  /**
   * Timestamp of the order
   */
  timestamp: number;
  /**
   * Price of the order
   */
  price: number;
  action_type: TradingActionType;
  order_tpye: OrderType;
  /**
   * Result status of the order
   */
  status: OrderResult;
  /**
   * API error code
   */
  status_code: ApiError;
  /**
   * Trade status of the order
   */
  trade_status: OrderStatus;
  /**
   * Percentage of the order filled
   */
  filled_perc: number;
  /**
   * Details of the order
   */
  order_details: {
    [key: string]: unknown;
  };
};

/**
 * Result of the order
 */
export type OrderResult = "success" | "failure" | "error";

/**
 * Status of the order
 */
export type OrderStatus = "new" | "filled" | "partially_filled" | "cancelled";

/**
 * Type of order
 */
export type OrderType = "open" | "close" | "stop_loss" | "take_profit";

/**
 * Type of trading action
 */
export type TradingActionType =
  | "buy"
  | "sell"
  | "buy_close"
  | "sell_close"
  | "cancel_order";

export type UpdateAPIKey = {
  /**
   * Unique identifier for the API key
   */
  id: string;
  /**
   * Status of the API key
   */
  enabled: boolean;
  /**
   * Label for the API key
   */
  label: string;
};

export type UpdateBot = {
  /**
   * Name of the bot
   */
  name: string;
  /**
   * Name of the strategy used by the bot
   */
  strategy_name: string;
  /**
   * Unique identifier for the API key
   */
  api_key_id: string;
  /**
   * Allocation for the bot
   */
  allocation: number;
  /**
   * Status of the bot
   */
  enabled: boolean;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
  /**
   * Unique identifier for the bot
   */
  id: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type HealthHealthGetResponse = unknown;

export type HealthHealthGetError = unknown;

export type HeartbeatHeartbeatPostData = {
  body: {
    [key: string]: unknown;
  };
};

export type HeartbeatHeartbeatPostResponse = unknown;

export type HeartbeatHeartbeatPostError = HTTPValidationError;

export type GetFuturesBalanceFuturesBalanceGetData = unknown;

export type GetFuturesBalanceFuturesBalanceGetResponse = unknown;

export type GetFuturesBalanceFuturesBalanceGetError = HTTPValidationError;

export type GetFuturesLedgerFuturesLedgerGetData = {
  query: {
    key: string;
  };
};

export type GetFuturesLedgerFuturesLedgerGetResponse = unknown;

export type GetFuturesLedgerFuturesLedgerGetError = HTTPValidationError;

export type GetHistoricalFuturesOrdersFuturesHistoricalOrdersGetData = {
  query: {
    key: string;
  };
};

export type GetHistoricalFuturesOrdersFuturesHistoricalOrdersGetResponse =
  unknown;

export type GetHistoricalFuturesOrdersFuturesHistoricalOrdersGetError =
  HTTPValidationError;

export type PlaceOrderFuturesPlaceOrderPostData = {
  body: {
    [key: string]: unknown;
  };
  query: {
    key: string;
  };
};

export type PlaceOrderFuturesPlaceOrderPostResponse = unknown;

export type PlaceOrderFuturesPlaceOrderPostError = HTTPValidationError;

export type CancelOrderFuturesCancelOrderDeleteData = {
  query: {
    key: string;
    orderId: string;
    symbol: string;
  };
};

export type CancelOrderFuturesCancelOrderDeleteResponse = unknown;

export type CancelOrderFuturesCancelOrderDeleteError = HTTPValidationError;

export type AppGetOrdersOrdersGetData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type AppGetOrdersOrdersGetResponse = unknown;

export type AppGetOrdersOrdersGetError = HTTPValidationError;

export type AppPostOrdersOrdersPostData = {
  body: OrderModel;
};

export type AppPostOrdersOrdersPostResponse = unknown;

export type AppPostOrdersOrdersPostError = HTTPValidationError;

export type GetBotsBotsGetData = unknown;

export type GetBotsBotsGetResponse = unknown;

export type GetBotsBotsGetError = HTTPValidationError;

export type CreateBotBotsPostData = {
  body: BotModel;
};

export type CreateBotBotsPostResponse = unknown;

export type CreateBotBotsPostError = HTTPValidationError;

export type DeleteBotBotsDeleteData = {
  query: {
    id: string;
  };
};

export type DeleteBotBotsDeleteResponse = unknown;

export type DeleteBotBotsDeleteError = HTTPValidationError;

export type UpdateBotBotsPutData = {
  body: UpdateBot;
};

export type UpdateBotBotsPutResponse = unknown;

export type UpdateBotBotsPutError = HTTPValidationError;

export type AppGetApiKeysApiKeysGetData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type AppGetApiKeysApiKeysGetResponse = unknown;

export type AppGetApiKeysApiKeysGetError = HTTPValidationError;

export type AppGetApiKeysApiKeysEnabledGetData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type AppGetApiKeysApiKeysEnabledGetResponse = unknown;

export type AppGetApiKeysApiKeysEnabledGetError = HTTPValidationError;

export type AppPostApiKeyApiKeyPostData = {
  body: APIKeyModel;
};

export type AppPostApiKeyApiKeyPostResponse = unknown;

export type AppPostApiKeyApiKeyPostError = HTTPValidationError;

export type AppDeleteApiKeyApiKeyDeleteData = {
  body: DeleteAPIKey;
};

export type AppDeleteApiKeyApiKeyDeleteResponse = unknown;

export type AppDeleteApiKeyApiKeyDeleteError = HTTPValidationError;

export type AppPutApiKeyApiKeyPutData = {
  body: UpdateAPIKey;
};

export type AppPutApiKeyApiKeyPutResponse = unknown;

export type AppPutApiKeyApiKeyPutError = HTTPValidationError;

export type PostManualActionActionsManualPostData = {
  body: FuturesTradingAction;
};

export type PostManualActionActionsManualPostResponse = unknown;

export type PostManualActionActionsManualPostError = HTTPValidationError;

export type PostFuturesActionActionsFuturesPostData = {
  body: FuturesTradingAction;
};

export type PostFuturesActionActionsFuturesPostResponse = unknown;

export type PostFuturesActionActionsFuturesPostError = HTTPValidationError;

export type PostSpotActionActionsSpotPostData = {
  body: FuturesTradingAction;
};

export type PostSpotActionActionsSpotPostResponse = unknown;

export type PostSpotActionActionsSpotPostError = HTTPValidationError;

export type GetActionsActionsGetData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetActionsActionsGetResponse = unknown;

export type GetActionsActionsGetError = HTTPValidationError;
