// This file is auto-generated by @hey-api/openapi-ts

/**
 * API error codes
 */
export type ApiError = unknown[];

export type APIKeyModel = {
  /**
   * Unique identifier for the API key
   */
  id?: string | null;
  /**
   * Exchange name
   */
  exchange: string;
  /**
   * API key
   */
  api_key?: string | null;
  /**
   * API secret
   */
  secret?: string | null;
  /**
   * API passphrase
   */
  passphrase?: string | null;
  /**
   * Label for the API key
   */
  label: string;
  /**
   * Status of the API key
   */
  enabled?: boolean;
  /**
   * Timestamp of creation
   */
  created_at?: number;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
};

export type BotModel = {
  /**
   * Unique identifier for the bot
   */
  id?: string | null;
  /**
   * Name of the bot
   */
  name: string;
  /**
   * Unique identifier for the trading strategy used by the bot
   */
  strategy_id: Strategy;
  /**
   * Unique identifier for the API key
   */
  api_key_id: string;
  /**
   * Allocation for the bot
   */
  allocation: number;
  /**
   * Status of the bot
   */
  enabled: boolean;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
};

export type CreateAPIKeyResponse = {
  /**
   * Unique identifier for the API key
   */
  id?: string | null;
  /**
   * Error message
   */
  error?: string | null;
};

export type DeleteAPIKey = {
  /**
   * Unique identifier for the API key
   */
  id: string;
};

/**
 * Supported exchanges
 */
export type Exchange = "kucoin" | "bingx";

/**
 * Model for futures balance
 */
export type FuturesBalance = {
  /**
   * API key ID
   */
  apiKeyId: string;
  /**
   * Asset/Currency code
   */
  asset: string;
  /**
   * Total balance/equity
   */
  balance: number;
  /**
   * Available balance for trading/withdrawal
   */
  available: number;
  /**
   * Unrealized profit and loss
   */
  unrealizedPnl: number;
  /**
   * Used/Position margin
   */
  usedMargin?: number | null;
  /**
   * Frozen/Hold funds
   */
  frozenAmount?: number | null;
};

/**
 * Model for futures balance error response
 */
export type FuturesBalanceError = {
  /**
   * API key ID
   */
  apiKeyId: string;
  /**
   * Error message
   */
  error: string;
};

/**
 * Model for futures trading actions
 */
export type FuturesTradingAction = {
  /**
   * Unique identifier for the trading action in our system. Added by the system, therefore optional.
   */
  id?: string | null;
  /**
   * Unique identifier for the execution of the order. Added by the system, therefore optional.
   */
  execution_id?: string | null;
  /**
   * Unique identifier for the order to close. Required on close actions to match with the open order
   */
  open_order_execution_id?: string | null;
  /**
   * The type of action: buy, sell, etc.
   */
  action_type: TradingActionType;
  /**
   * Market type: either spot or futures
   */
  market_type: MarketType;
  /**
   * Unique identifier for the strategy
   */
  strategy_id: string;
  /**
   * Timestamp of when the action was created on the client side
   */
  client_timestamp: number;
  /**
   * Trading symbol or asset pair (e.g., 'BTC/USDT'). Needs to be separated by '/'
   */
  symbol: string;
  /**
   * Whether this is a limit order
   */
  is_limit?: boolean | null;
  /**
   * The limit price for limit orders
   */
  limit_price?: number | null;
  /**
   * Allocation for the order
   */
  allocation?: number;
  /**
   * Take profit targets: buy/sell
   */
  take_profit_targets?: Array<TP_SL_Dict> | null;
  /**
   * Stop loss values: buy/sell
   */
  stop_loss_values?: Array<TP_SL_Dict> | null;
  /**
   * Whether the system should mark the remaining unfilled orders with the same open order id CANCELLED if e.g. the last take profit is hit, cancel the remaining stop losses
   */
  cancel_leftover?: boolean | null;
  /**
   * Leverage to use for futures trades. Limited to 10 to avoid misuse.
   */
  leverage: number | null;
  /**
   * Margin mode for futures trades: either isolated or cross, default is isolated
   */
  margin_mode?: MarginMode | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * Margin mode for futures trades
 */
export type MarginMode = "isolated" | "cross";

/**
 * Type of market
 */
export type MarketType = "spot" | "futures";

/**
 * Response model for orders. All optional as the model is built step by step.
 */
export type OrderModel = {
  /**
   * Unique identifier for the order (unique to the bot)
   */
  id?: string | null;
  /**
   * Unique identifier for the trading action that placed the order
   */
  open_trading_action_id?: string | null;
  /**
   * Unique identifier for the trading action that closed the order
   */
  close_trading_action_id?: string | null;
  /**
   * Unique identifier for the execution (not unique to the bot)
   */
  execution_id?: string | null;
  /**
   * Unique identifier for the open order execution. Needed for closing the order
   */
  open_order_execution_id?: string | null;
  /**
   * Unique identifier for the API key
   */
  api_key_id?: string | null;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
  /**
   * Unique identifier for the bot
   */
  bot_id?: string | null;
  /**
   * Exchange name. Of type Exchange
   */
  exchange?: Exchange | null;
  /**
   * Trading symbol on exchange
   */
  symbol?: string | null;
  /**
   * Common trading symbol
   */
  common_symbol?: string | null;
  /**
   * Timestamp of the order
   */
  timestamp?: number | null;
  /**
   * Price of the order
   */
  price?: number | null;
  /**
   * Type of trading action. Of type TradingActionType
   */
  action_type?: TradingActionType | null;
  /**
   * API error code. Of type ApiError
   */
  status_code?: ApiError | null;
  /**
   * Trade status of the order. Of type OrderStatus
   */
  status?: OrderStatus | null;
  /**
   * Percentage of the order filled
   */
  filled_perc?: number | null;
  /**
   * Quantity filled. Needed for pnl calculation
   */
  filled_qty?: number | null;
  /**
   * Fees for the order
   */
  fee?: number | null;
  /**
   * Leverage for the order
   */
  leverage?: number | null;
  /**
   * Exchange specific details of the order
   */
  order_details?: {
    [key: string]: unknown;
  } | null;
  /**
   * Comment for the order
   */
  comment?: string | null;
};

/**
 * Status of the order
 */
export type OrderStatus =
  | "new"
  | "filled"
  | "partially_filled"
  | "cancelled"
  | "failed";

export type Strategy = "daily_trend_momentum";

/**
 * Model for take profit and stop loss targets
 */
export type TP_SL_Dict = {
  /**
   * Price to set the target at
   */
  price: number;
  /**
   * Percentage of the order to sell
   */
  percentage: number;
  /**
   * Execution ID of the order. Will be added by the system
   */
  execution_id?: string;
};

/**
 * Type of trading action
 */
export type TradingActionType =
  | "buy"
  | "sell"
  | "buy_close"
  | "sell_close"
  | "cancel_order";

export type UpdateAPIKey = {
  /**
   * Unique identifier for the API key
   */
  id: string;
  /**
   * Status of the API key
   */
  enabled: boolean;
  /**
   * Label for the API key
   */
  label: string;
};

export type UpdateBot = {
  /**
   * Unique identifier for the bot
   */
  id: string;
  /**
   * Name of the bot
   */
  name: string;
  /**
   * Unique identifier for the trading strategy used by the bot
   */
  strategy_id: Strategy;
  /**
   * Unique identifier for the API key
   */
  api_key_id: string;
  /**
   * Allocation for the bot
   */
  allocation: number;
  /**
   * Status of the bot
   */
  enabled: boolean;
  /**
   * Unique identifier for the user
   */
  user_id?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type HealthHealthGetResponse = unknown;

export type HealthHealthGetError = unknown;

export type HeartbeatHeartbeatPostData = {
  body: {
    [key: string]: unknown;
  };
};

export type HeartbeatHeartbeatPostResponse = unknown;

export type HeartbeatHeartbeatPostError = HTTPValidationError;

export type GetFuturesBalanceData = unknown;

export type GetFuturesBalanceResponse = Array<
  FuturesBalance | FuturesBalanceError
>;

export type GetFuturesBalanceError = HTTPValidationError;

export type GetFuturesLedgerData = {
  query: {
    key: string;
  };
};

export type GetFuturesLedgerResponse = unknown;

export type GetFuturesLedgerError = HTTPValidationError;

export type GetHistoricalFuturesOrdersData = {
  query: {
    key: string;
  };
};

export type GetHistoricalFuturesOrdersResponse = unknown;

export type GetHistoricalFuturesOrdersError = HTTPValidationError;

export type PlaceFuturesOrderData = {
  body: {
    [key: string]: unknown;
  };
  query: {
    key: string;
  };
};

export type PlaceFuturesOrderResponse = unknown;

export type PlaceFuturesOrderError = HTTPValidationError;

export type CancelFuturesOrderData = {
  query: {
    key: string;
    orderId: string;
    symbol: string;
  };
};

export type CancelFuturesOrderResponse = unknown;

export type CancelFuturesOrderError = HTTPValidationError;

export type GetOrdersData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetOrdersResponse = Array<OrderModel>;

export type GetOrdersError = HTTPValidationError;

export type GetBotsData = unknown;

export type GetBotsResponse = Array<BotModel>;

export type GetBotsError = HTTPValidationError;

export type CreateBotData = {
  body: BotModel;
};

export type CreateBotResponse = unknown;

export type CreateBotError = HTTPValidationError;

export type DeleteBotData = {
  query: {
    id: string;
  };
};

export type DeleteBotResponse = unknown;

export type DeleteBotError = HTTPValidationError;

export type UpdateBotData = {
  body: UpdateBot;
};

export type UpdateBotResponse = unknown;

export type UpdateBotError = HTTPValidationError;

export type GetApiKeysData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetApiKeysResponse = Array<APIKeyModel>;

export type GetApiKeysError = HTTPValidationError;

export type CreateApiKeyData = {
  body: APIKeyModel;
};

export type CreateApiKeyResponse = CreateAPIKeyResponse;

export type CreateApiKeyError = HTTPValidationError;

export type DeleteApiKeyData = {
  body: DeleteAPIKey;
};

export type DeleteApiKeyResponse = unknown;

export type DeleteApiKeyError = HTTPValidationError;

export type UpdateApiKeyData = {
  body: UpdateAPIKey;
};

export type UpdateApiKeyResponse = unknown;

export type UpdateApiKeyError = HTTPValidationError;

export type GetStrategiesResponse = unknown;

export type GetStrategiesError = unknown;

export type PostFuturesActionActionsFuturesPostData = {
  body: FuturesTradingAction;
};

export type PostFuturesActionActionsFuturesPostResponse = unknown;

export type PostFuturesActionActionsFuturesPostError = HTTPValidationError;

export type PostSpotActionActionsSpotPostData = {
  body: FuturesTradingAction;
};

export type PostSpotActionActionsSpotPostResponse = unknown;

export type PostSpotActionActionsSpotPostError = HTTPValidationError;

export type GetActionsData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetActionsResponse = Array<FuturesTradingAction>;

export type GetActionsError = HTTPValidationError;
