// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorIdentifierSchema = {
  type: "string",
  enum: [
    "allocation_below_current_exposure",
    "allocation_below_min_amount",
    "allocation_limit_exceeded",
    "black_swan",
    "bot_already_deleted",
    "bot_stopping_completed",
    "bot_stopping_started",
    "cancelled_open_order",
    "client_order_id_already_exists",
    "invalid_content_type",
    "delete_bot_error",
    "exchange_http_request_error",
    "exchange_invalid_parameter",
    "exchange_invalid_signature",
    "exchange_invalid_timestamp",
    "exchange_ip_address_is_not_authorized",
    "exchange_key_already_exists",
    "exchange_key_in_use",
    "exchange_system_under_maintenance",
    "exchange_rate_limit_exceeded",
    "insufficient_permissions_spot_and_futures_required",
    "exchange_service_temporarily_unavailable",
    "exchange_system_is_busy",
    "exchange_system_configuration_error",
    "exchange_internal_system_error",
    "exchange_user_account_is_frozen",
    "api_key_expired",
    "bearer_token_expired",
    "failed_open_order",
    "forbidden",
    "hedge_mode_not_active",
    "insufficient_balance",
    "insufficient_margin",
    "insufficient_scopes",
    "invalid_api_key",
    "invalid_bearer",
    "invalid_data",
    "invalid_data_response",
    "invalid_exchange_key",
    "invalid_model_name",
    "leverage_limit_exceeded",
    "order_violates_liquidation_price_constraints",
    "margin_mode_clash",
    "name_not_unique",
    "no_api_key",
    "no_bearer",
    "no_credentials",
    "now_api_down",
    "object_already_exists",
    "object_created",
    "object_deleted",
    "object_locked",
    "object_not_found",
    "object_updated",
    "order_is_already_filled",
    "order_is_being_processed",
    "order_quantity_limit_exceeded",
    "order_does_not_exist",
    "order_price_is_invalid",
    "order_size_too_large",
    "order_size_too_small",
    "orphan_open_order",
    "orphan_close_order",
    "position_limit_exceeded",
    "position_does_not_exist",
    "position_opening_temporarily_suspended",
    "post_only_order_would_immediately_match",
    "request_scope_limit_exceeded",
    "risk_limit_exceeded",
    "rpc_timeout",
    "system_settlement_in_process",
    "strategy_disabled",
    "strategy_leverage_mismatch",
    "strategy_not_supporting_exchange",
    "success",
    "symbol_does_not_exist",
    "trading_action_expired",
    "trading_action_skipped_bot_stopping",
    "trading_has_been_locked",
    "trading_is_suspended",
    "unknown_error_occurred",
    "requested_resource_not_found",
  ],
  title: "ApiErrorIdentifier",
  description: "Unique identifier of the API error.",
} as const;

export const ApiErrorLevelSchema = {
  type: "string",
  enum: ["error", "info", "success", "warning"],
  title: "ApiErrorLevel",
  description: "Level of the API error.",
} as const;

export const ApiErrorTypeSchema = {
  type: "string",
  enum: ["user error", "exchange error", "server error", "no error"],
  title: "ApiErrorType",
  description: "Type of the API error.",
} as const;

export const ExceptionDetailSchema = {
  properties: {
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
      description: "An additional error message",
    },
    code: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description: "The unique error code",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "The type of error",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "The level of the error",
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      description: "The HTTP status code",
    },
    details: {
      title: "Details",
      description: "Additional details about the error",
    },
  },
  type: "object",
  required: ["code", "type", "level", "status_code"],
  title: "ExceptionDetail",
  description: "Exception details returned to the client.",
} as const;

export const LogLevelSchema = {
  type: "string",
  enum: ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
  title: "LogLevel",
} as const;

export const PaginatedResponse_SignalWithToken_Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/SignalWithToken",
      },
      type: "array",
      title: "Data",
    },
    total: {
      type: "integer",
      title: "Total",
      description: "The total number of items",
    },
    page: {
      type: "integer",
      title: "Page",
      description: "The current page number",
    },
    page_size: {
      type: "integer",
      title: "Page Size",
      description: "The number of items per page",
    },
    prev: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Prev",
      description: "The previous page number",
    },
    next: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Next",
      description: "The next page number",
    },
    last: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Last",
      description: "The last page number",
    },
  },
  type: "object",
  required: ["data", "total", "page", "page_size"],
  title: "PaginatedResponse[SignalWithToken]",
} as const;

export const RiskSchema = {
  properties: {
    rugged: {
      type: "boolean",
      title: "Rugged",
      description: "Is token rugged",
    },
    score: {
      type: "integer",
      title: "Score",
      description: "Overall risk score",
    },
  },
  type: "object",
  required: ["rugged", "score"],
  title: "Risk",
  description: "Model for risk assessment",
} as const;

export const SignalOverviewStatsSchema = {
  properties: {
    timestamp: {
      type: "integer",
      title: "Timestamp",
      description: "The timestamp of the stats",
    },
    total: {
      type: "integer",
      title: "Total",
      description: "Total number of tokens analyzed",
    },
    win_rate: {
      type: "number",
      title: "Win Rate",
      description: "Overall win rate as a percentage",
    },
    avg_performance: {
      type: "number",
      title: "Avg Performance",
      description: "Average performance as a percentage",
    },
    median_performance: {
      type: "number",
      title: "Median Performance",
      description: "Median performance as a percentage",
    },
    best_risk_category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Best Risk Category",
      description: "Best performing risk category",
    },
    best_month: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Best Month",
      description: "Best performing month",
    },
    best_holding_period: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Best Holding Period",
      description: "Best holding period",
    },
    best_launch_hour: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Best Launch Hour",
      description: "Best launch hour (UTC)",
    },
    best_launch_day: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Best Launch Day",
      description: "Best launch day of the week",
    },
  },
  type: "object",
  required: [
    "timestamp",
    "total",
    "win_rate",
    "avg_performance",
    "median_performance",
  ],
  title: "SignalOverviewStats",
  description: "Model for signal statistics response",
} as const;

export const SignalVolumeSchema = {
  properties: {
    day: {
      type: "string",
      title: "Day",
    },
    hour: {
      type: "string",
      title: "Hour",
    },
  },
  type: "object",
  required: ["day", "hour"],
  title: "SignalVolume",
  description: "Model for the volume of the signal",
} as const;

export const SignalWithTokenSchema = {
  properties: {
    ca: {
      type: "string",
      title: "Ca",
      description: "The contract address of the token",
    },
    name: {
      type: "string",
      title: "Name",
      description: "The name of the token",
    },
    type: {
      type: "string",
      title: "Type",
      description: "The type of the signal",
    },
    risk: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Risk",
      description: "The risk level of the signal",
    },
    performance: {
      type: "string",
      title: "Performance",
      description: "The performance in percent as a string. e.g. +100%",
    },
    price: {
      type: "string",
      title: "Price",
      description: "The price of the signal",
    },
    volume: {
      $ref: "#/components/schemas/SignalVolume",
      description: "The volume of the signal",
    },
    liquidity: {
      type: "string",
      title: "Liquidity",
      description: "The liquidity of the signal",
    },
    mcap: {
      type: "string",
      title: "Mcap",
      description: "The market cap of the signal",
    },
    called_at: {
      type: "integer",
      title: "Called At",
      description: "The timestamp of the call",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "The timestamp of the last update",
    },
    tg_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tg Id",
      description: "The telegram id of the signal",
    },
    data: {
      $ref: "#/components/schemas/TokenData",
      description: "The token info",
    },
    performance_float: {
      type: "number",
      title: "Performance Float",
      description: "The performance in float. e.g. +100% -> 2.0",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "ca",
    "name",
    "type",
    "performance",
    "price",
    "volume",
    "liquidity",
    "mcap",
    "called_at",
    "updated_at",
    "tg_id",
    "data",
    "performance_float",
  ],
  title: "SignalWithToken",
  description: "Model for the signal with the token info",
} as const;

export const TokenDataSchema = {
  properties: {
    token: {
      $ref: "#/components/schemas/TokenDetail",
      description: "Token details",
    },
    mcap: {
      type: "string",
      title: "Mcap",
      description: "Market cap",
    },
    price: {
      type: "string",
      title: "Price",
      description: "Price",
    },
    liquidity: {
      type: "string",
      title: "Liquidity",
      description: "The liquidity of the token in USD",
    },
    risk: {
      $ref: "#/components/schemas/Risk",
      description: "Risk assessment",
    },
    buys: {
      type: "integer",
      title: "Buys",
      description: "Number of buys",
    },
    sells: {
      type: "integer",
      title: "Sells",
      description: "Number of sells",
    },
    txns: {
      type: "integer",
      title: "Txns",
      description: "Total transactions",
    },
    holders: {
      type: "integer",
      title: "Holders",
      description: "Number of holders",
    },
  },
  type: "object",
  required: [
    "token",
    "mcap",
    "price",
    "liquidity",
    "risk",
    "buys",
    "sells",
    "txns",
    "holders",
  ],
  title: "TokenData",
  description: "Main model for complete token data",
} as const;

export const TokenDetailSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Token name",
    },
    symbol: {
      type: "string",
      title: "Symbol",
      description: "Token symbol",
    },
    mint: {
      type: "string",
      title: "Mint",
      description: "Token mint address (aka contract address)",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Token description",
    },
    image: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Image",
      description: "Token image URL",
    },
    strictSocials: {
      additionalProperties: true,
      type: "object",
      title: "Strictsocials",
      description: "Social media links",
      default: {},
    },
  },
  type: "object",
  required: ["name", "symbol", "mint"],
  title: "TokenDetail",
  description: "Model for detailed token information",
} as const;
