// This file is auto-generated by @hey-api/openapi-ts

export const ErrorResponseSchema = {
  properties: {
    detail: {
      type: 'string',
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'ErrorResponse',
  description: 'Error response schema.',
} as const;

export const PaginatedResponse_SignalWithToken_Schema = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/SignalWithToken',
      },
      type: 'array',
      title: 'Data',
    },
    total: {
      type: 'integer',
      title: 'Total',
      description: 'The total number of items',
    },
    page: {
      type: 'integer',
      title: 'Page',
      description: 'The current page number',
    },
    page_size: {
      type: 'integer',
      title: 'Page Size',
      description: 'The number of items per page',
    },
    prev: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Prev',
      description: 'The previous page number',
    },
    next: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next',
      description: 'The next page number',
    },
    last: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Last',
      description: 'The last page number',
    },
  },
  type: 'object',
  required: ['data', 'total', 'page', 'page_size'],
  title: 'PaginatedResponse[SignalWithToken]',
} as const;

export const RugCheckReportSchema = {
  properties: {
    lp_locked_pct: {
      type: 'number',
      title: 'Lp Locked Pct',
      description: 'Percentage of LP locked',
    },
    risks: {
      items: {
        $ref: '#/components/schemas/_Risk',
      },
      type: 'array',
      title: 'Risks',
      description: 'Risk items reported by RugCheck',
    },
    score: {
      type: 'integer',
      title: 'Score',
      description: 'RugCheck overall security score',
    },
    score_normalised: {
      type: 'integer',
      title: 'Score Normalised',
      description: 'Normalised security score',
    },
  },
  type: 'object',
  required: ['lp_locked_pct', 'score', 'score_normalised'],
  title: 'RugCheckReport',
} as const;

export const SignalOverviewStatsSchema = {
  properties: {
    timestamp: {
      type: 'integer',
      title: 'Timestamp',
      description: 'The unix timestamp of the stats calculation',
    },
    total: {
      type: 'integer',
      title: 'Total',
      description: 'Total number of tokens analyzed',
    },
    win_rate: {
      type: 'number',
      title: 'Win Rate',
      description: 'Overall win rate as a decimal',
    },
  },
  type: 'object',
  required: ['timestamp', 'total', 'win_rate'],
  title: 'SignalOverviewStats',
  description: 'Model for signal statistics response',
} as const;

export const SignalWithTokenSchema = {
  properties: {
    stage: {
      type: 'string',
      title: 'Stage',
      description: 'Lifecycle stage',
    },
    address: {
      type: 'string',
      title: 'Address',
      description: 'Token contract address',
    },
    pair_address: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pair Address',
      description: 'Pair address',
    },
    chain: {
      type: 'string',
      enum: [
        'solana',
        'ethereum',
        'bsc',
        'base',
        'arbitrum',
        'polygon',
        'avalanche',
      ],
      title: 'Chain',
      description: 'Chain',
    },
    first_call_time: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'First Call Time',
      description: 'First call time (tracker entry)',
    },
    mc_at_call: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mc At Call',
      description: 'Baseline MC for X calculations',
    },
    ath_mc: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Ath Mc',
      description: 'All-time-high MC',
    },
    last_x: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Last X',
      description: 'Last milestone announced',
    },
    call_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Call Id',
      description: 'The ID of the call message from the notification service',
    },
    called_at: {
      type: 'string',
      format: 'date-time',
      title: 'Called At',
      description: 'Time of the first call',
    },
    updated_at: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updated At',
      description: 'Last update time',
    },
    data: {
      anyOf: [
        {
          $ref: '#/components/schemas/TokenData',
        },
        {
          type: 'null',
        },
      ],
      description: 'The token info',
    },
    security: {
      anyOf: [
        {
          $ref: '#/components/schemas/RugCheckReport',
        },
        {
          type: 'null',
        },
      ],
      description: 'The security report',
    },
    performance: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Performance',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['stage', 'address', 'chain', 'called_at', 'performance'],
  title: 'SignalWithToken',
  description:
    'Trading signal enriched with comprehensive token metadata and information.',
} as const;

export const TokenDataSchema = {
  properties: {
    chain_id: {
      type: 'string',
      title: 'Chain Id',
      description: 'Blockchain identifier',
    },
    dex_id: {
      type: 'string',
      title: 'Dex Id',
      description: 'DEX identifier',
    },
    url: {
      type: 'string',
      title: 'Url',
      description: 'DexScreener pair URL',
    },
    pair_address: {
      type: 'string',
      title: 'Pair Address',
      description: 'Pair/pool address',
    },
    base_token: {
      $ref: '#/components/schemas/_Token',
      description: 'Base token metadata',
    },
    quote_token: {
      $ref: '#/components/schemas/_Token',
      description: 'Quote token metadata',
    },
    price_native: {
      type: 'number',
      title: 'Price Native',
      description: 'Token price in native chain currency',
    },
    price_usd: {
      type: 'number',
      title: 'Price Usd',
      description: 'Token price in USD',
    },
    txns: {
      $ref: '#/components/schemas/_Txns',
      description: 'Buy/sell transaction counts over multiple time windows',
    },
    volume: {
      $ref: '#/components/schemas/_Volume',
      description: 'Trading volume over multiple time windows',
    },
    price_change: {
      $ref: '#/components/schemas/_PriceChange',
      description: 'Price change percentages over multiple time windows',
    },
    liquidity: {
      $ref: '#/components/schemas/_Liquidity',
      description: 'Liquidity breakdown for the pair',
    },
    fdv: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Fdv',
      description: 'Fully diluted valuation in USD',
    },
    market_cap: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Market Cap',
      description: 'Market capitalization in USD',
    },
    pair_created_at: {
      type: 'integer',
      title: 'Pair Created At',
      description: 'Pair creation timestamp (milliseconds since epoch)',
    },
    info: {
      anyOf: [
        {
          $ref: '#/components/schemas/_Info',
        },
        {
          type: 'null',
        },
      ],
      description: 'Additional token and pair metadata',
    },
  },
  type: 'object',
  required: [
    'chain_id',
    'dex_id',
    'url',
    'pair_address',
    'base_token',
    'quote_token',
    'price_native',
    'price_usd',
    'txns',
    'volume',
    'price_change',
    'pair_created_at',
  ],
  title: 'TokenData',
} as const;

export const _InfoSchema = {
  properties: {
    image_url: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Image Url',
      description: 'Token image URL',
    },
    header: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Header',
      description: 'Header image URL',
    },
    open_graph: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Open Graph',
      description: 'OpenGraph image URL',
    },
    websites: {
      items: {
        $ref: '#/components/schemas/_Website',
      },
      type: 'array',
      title: 'Websites',
      description: 'List of related websites',
    },
  },
  type: 'object',
  title: '_Info',
} as const;

export const _LiquiditySchema = {
  properties: {
    usd: {
      type: 'number',
      title: 'Usd',
      description: 'Liquidity in USD',
      default: 0,
    },
    base: {
      type: 'number',
      title: 'Base',
      description: 'Amount of base token in the pool',
      default: 0,
    },
    quote: {
      type: 'number',
      title: 'Quote',
      description: 'Amount of quote token in the pool',
      default: 0,
    },
  },
  type: 'object',
  title: '_Liquidity',
} as const;

export const _PriceChangeSchema = {
  properties: {
    h24: {
      type: 'number',
      title: 'H24',
      description: '24-hour price change percentage',
      default: 0,
    },
    h6: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'H6',
      description: '6-hour price change percentage',
    },
    h1: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'H1',
      description: '1-hour price change percentage',
    },
    m5: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'M5',
      description: '5-minute price change percentage',
    },
  },
  type: 'object',
  title: '_PriceChange',
} as const;

export const _RiskSchema = {
  properties: {
    description: {
      type: 'string',
      title: 'Description',
      description: 'Risk description',
    },
    level: {
      type: 'string',
      title: 'Level',
      description: 'Risk level',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Human-readable risk name',
    },
    score: {
      type: 'integer',
      title: 'Score',
      description: 'Risk score',
    },
    value: {
      type: 'string',
      title: 'Value',
      description: 'Risk value',
    },
  },
  type: 'object',
  required: ['description', 'level', 'name', 'score', 'value'],
  title: '_Risk',
} as const;

export const _TokenSchema = {
  properties: {
    address: {
      type: 'string',
      title: 'Address',
      description: 'Token contract address',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Token name',
    },
    symbol: {
      type: 'string',
      title: 'Symbol',
      description: 'Token symbol',
    },
  },
  type: 'object',
  required: ['address', 'name', 'symbol'],
  title: '_Token',
} as const;

export const _TxnCountsSchema = {
  properties: {
    buys: {
      type: 'integer',
      title: 'Buys',
      description: 'Number of buy transactions in this window',
      default: 0,
    },
    sells: {
      type: 'integer',
      title: 'Sells',
      description: 'Number of sell transactions in this window',
      default: 0,
    },
    ratio: {
      type: 'number',
      title: 'Ratio',
      description: `Buy/sell ratio (BSR) where:
- ratio = buys / (buys + sells)
- 0.5 = neutral when there are no transactions.`,
      readOnly: true,
    },
  },
  type: 'object',
  required: ['ratio'],
  title: '_TxnCounts',
} as const;

export const _TxnsSchema = {
  properties: {
    m5: {
      $ref: '#/components/schemas/_TxnCounts',
      description: 'Buy/sell transaction counts over the last 5 minutes',
    },
    h1: {
      $ref: '#/components/schemas/_TxnCounts',
      description: 'Buy/sell transaction counts over the last hour',
    },
    h6: {
      $ref: '#/components/schemas/_TxnCounts',
      description: 'Buy/sell transaction counts over the last 6 hours',
    },
    h24: {
      $ref: '#/components/schemas/_TxnCounts',
      description: 'Buy/sell transaction counts over the last 24 hours',
    },
  },
  type: 'object',
  required: ['m5', 'h1', 'h6', 'h24'],
  title: '_Txns',
} as const;

export const _VolumeSchema = {
  properties: {
    h24: {
      type: 'number',
      title: 'H24',
      description: '24-hour trading volume',
      default: 0,
    },
    h6: {
      type: 'number',
      title: 'H6',
      description: '6-hour trading volume',
      default: 0,
    },
    h1: {
      type: 'number',
      title: 'H1',
      description: '1-hour trading volume',
      default: 0,
    },
    m5: {
      type: 'number',
      title: 'M5',
      description: '5-minute trading volume',
      default: 0,
    },
  },
  type: 'object',
  title: '_Volume',
} as const;

export const _WebsiteSchema = {
  properties: {
    url: {
      type: 'string',
      title: 'Url',
      description: 'Website URL',
    },
    label: {
      type: 'string',
      title: 'Label',
      description: 'Website label or type',
    },
  },
  type: 'object',
  required: ['url', 'label'],
  title: '_Website',
} as const;
