import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  GetSignalsData,
  GetSignalsError,
  GetSignalsResponse,
  GetTopSignalsData,
  GetTopSignalsError,
  GetTopSignalsResponse,
  GetSignalStatsError,
  GetSignalStatsResponse,
  PingError,
  PingResponse,
  GetMetricsError,
  GetMetricsResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Get Signals
   * Retrieve all trading signals with pagination, filtering, and sorting support.
   *
   * Returns signals enriched with token metadata. Default sort is by call time (newest first).
   * If the user is not authenticated, signals from the last 24 hours are excluded from the results.
   */
  const getSignals = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetSignalsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSignalsResponse,
      GetSignalsError,
      ThrowOnError
    >({
      ...options,
      url: "/signals",
    });
  };

  /**
   * Get Top Signals
   * Retrieve top-performing signals ranked by performance within a specified time window.
   *
   * Returns the highest-performing signals from the last X hours (default: 24 hours).
   */
  const getTopSignals = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetTopSignalsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTopSignalsResponse,
      GetTopSignalsError,
      ThrowOnError
    >({
      ...options,
      url: "/signals/top",
    });
  };

  /**
   * Get Stats
   * Retrieve comprehensive statistics and analytics for all trading signals.
   *
   * Returns hourly-updated aggregated metrics including performance summaries and trading volumes.
   */
  const getSignalStats = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSignalStatsResponse,
      GetSignalStatsError,
      ThrowOnError
    >({
      ...options,
      url: "/signals/stats",
    });
  };

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Metrics
   * Get Prometheus metrics for the application. Returns plain text.
   */
  const getMetrics = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetMetricsResponse,
      GetMetricsError,
      ThrowOnError
    >({
      ...options,
      url: "/metrics",
    });
  };

  return {
    getSignals,
    getTopSignals,
    getSignalStats,
    ping,
    getMetrics,
  };
}
