// This file is auto-generated by @hey-api/openapi-ts

/**
 * Unique identifier of the API error.
 */
export type ApiErrorIdentifier =
  | "allocation_below_current_exposure"
  | "allocation_below_min_amount"
  | "allocation_limit_exceeded"
  | "black_swan"
  | "bot_already_deleted"
  | "bot_stopping_completed"
  | "bot_stopping_started"
  | "cancelled_open_order"
  | "client_order_id_already_exists"
  | "invalid_content_type"
  | "delete_bot_error"
  | "exchange_http_request_error"
  | "exchange_invalid_parameter"
  | "exchange_invalid_signature"
  | "exchange_invalid_timestamp"
  | "exchange_ip_address_is_not_authorized"
  | "exchange_key_already_exists"
  | "exchange_key_in_use"
  | "exchange_system_under_maintenance"
  | "exchange_rate_limit_exceeded"
  | "insufficient_permissions_spot_and_futures_required"
  | "exchange_service_temporarily_unavailable"
  | "exchange_system_is_busy"
  | "exchange_system_configuration_error"
  | "exchange_internal_system_error"
  | "exchange_user_account_is_frozen"
  | "api_key_expired"
  | "bearer_token_expired"
  | "failed_open_order"
  | "forbidden"
  | "hedge_mode_not_active"
  | "insufficient_balance"
  | "insufficient_margin"
  | "insufficient_scopes"
  | "invalid_api_key"
  | "invalid_basic_auth"
  | "invalid_bearer"
  | "invalid_data"
  | "invalid_data_response"
  | "invalid_exchange_key"
  | "invalid_model_name"
  | "leverage_limit_exceeded"
  | "order_violates_liquidation_price_constraints"
  | "margin_mode_clash"
  | "name_not_unique"
  | "no_credentials"
  | "now_api_down"
  | "object_already_exists"
  | "object_created"
  | "object_deleted"
  | "object_locked"
  | "object_not_found"
  | "object_updated"
  | "order_is_already_filled"
  | "order_is_being_processed"
  | "order_quantity_limit_exceeded"
  | "order_does_not_exist"
  | "order_price_is_invalid"
  | "order_size_too_large"
  | "order_size_too_small"
  | "orphan_open_order"
  | "orphan_close_order"
  | "position_limit_exceeded"
  | "position_does_not_exist"
  | "position_opening_temporarily_suspended"
  | "post_only_order_would_immediately_match"
  | "request_scope_limit_exceeded"
  | "risk_limit_exceeded"
  | "rpc_timeout"
  | "system_settlement_in_process"
  | "strategy_disabled"
  | "strategy_leverage_mismatch"
  | "strategy_not_supporting_exchange"
  | "success"
  | "symbol_does_not_exist"
  | "trading_action_expired"
  | "trading_action_skipped_bot_stopping"
  | "trading_has_been_locked"
  | "trading_is_suspended"
  | "unknown_error_occurred"
  | "requested_resource_not_found";

/**
 * Level of the API error.
 */
export type ApiErrorLevel = "error" | "info" | "success" | "warning";

/**
 * Type of the API error.
 */
export type ApiErrorType =
  | "user error"
  | "exchange error"
  | "server error"
  | "no error";

/**
 * Exception details returned to the client.
 */
export type ExceptionDetail = {
  /**
   * An additional error message
   */
  message?: string | null;
  /**
   * The unique error code
   */
  code: ApiErrorIdentifier;
  /**
   * The type of error
   */
  type: ApiErrorType;
  /**
   * The level of the error
   */
  level: ApiErrorLevel;
  /**
   * The HTTP status code
   */
  status_code: number;
  /**
   * Additional details about the error
   */
  details?: unknown;
};

export type LogLevel = "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL";

export type PaginatedResponse_SignalWithToken_ = {
  data: Array<SignalWithToken>;
  /**
   * The total number of items
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of items per page
   */
  page_size: number;
  /**
   * The previous page number
   */
  prev?: number | null;
  /**
   * The next page number
   */
  next?: number | null;
  /**
   * The last page number
   */
  last?: number | null;
};

/**
 * Model for risk assessment
 */
export type Risk = {
  /**
   * Is token rugged
   */
  rugged: boolean;
  /**
   * Overall risk score
   */
  score: number;
};

/**
 * Model for signal statistics response
 */
export type SignalOverviewStats = {
  /**
   * The unix timestamp of the stats calculation
   */
  timestamp: number;
  /**
   * Total number of tokens analyzed
   */
  total: number;
  /**
   * Overall win rate as a percentage
   */
  win_rate: number;
  /**
   * Average performance as a percentage
   */
  avg_performance: number;
  /**
   * Median performance as a percentage
   */
  median_performance: number;
  /**
   * Best performing risk category
   */
  best_risk_category?: string | null;
  /**
   * Best performing month
   */
  best_month?: string | null;
  /**
   * Best holding period
   */
  best_holding_period?: string | null;
  /**
   * Best launch hour (UTC)
   */
  best_launch_hour?: number | null;
  /**
   * Best launch day of the week
   */
  best_launch_day?: string | null;
};

/**
 * Trading volume data for a signal over different time periods.
 */
export type SignalVolume = {
  /**
   * 24-hour trading volume
   */
  day: string;
  /**
   * 1-hour trading volume
   */
  hour: string;
};

/**
 * Trading signal enriched with comprehensive token metadata and information.
 */
export type SignalWithToken = {
  /**
   * The contract address of the token
   */
  ca: string;
  /**
   * The name of the token
   */
  name: string;
  /**
   * The type of the signal
   */
  type: string;
  /**
   * The risk level of the signal
   */
  risk?: string | null;
  /**
   * The performance in percent as a string. e.g. +100%
   */
  performance: string;
  /**
   * The price of the signal
   */
  price: string;
  /**
   * The volume of the signal
   */
  volume: SignalVolume;
  /**
   * The liquidity of the signal
   */
  liquidity: string;
  /**
   * The market cap of the signal
   */
  mcap: string;
  /**
   * The timestamp of the call
   */
  called_at: number;
  /**
   * The timestamp of the last update
   */
  updated_at: number;
  /**
   * The telegram id of the signal
   */
  tg_id: string | null;
  /**
   * The token info
   */
  data: TokenData;
  /**
   * The performance in float. e.g. +100% -> 2.0
   */
  readonly performance_float: number;
};

/**
 * Main model for complete token data
 */
export type TokenData = {
  /**
   * Token details
   */
  token: TokenDetail;
  /**
   * Market cap
   */
  mcap: string;
  /**
   * Price
   */
  price: string;
  /**
   * The liquidity of the token in USD
   */
  liquidity: string;
  /**
   * Risk assessment
   */
  risk: Risk;
  /**
   * Number of buys
   */
  buys: number;
  /**
   * Number of sells
   */
  sells: number;
  /**
   * Total transactions
   */
  txns: number;
  /**
   * Number of holders
   */
  holders: number;
};

/**
 * Model for detailed token information
 */
export type TokenDetail = {
  /**
   * Token name
   */
  name: string;
  /**
   * Token symbol
   */
  symbol: string;
  /**
   * Token mint address (aka contract address)
   */
  mint: string;
  /**
   * Token description
   */
  description?: string | null;
  /**
   * Token image URL
   */
  image?: string | null;
  /**
   * Social media links
   */
  strictSocials?: {
    [key: string]: unknown;
  };
};

export type GetSignalsData = {
  query?: {
    /**
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * The current page number
     */
    page?: number | null;
    /**
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * The order to sort by
     */
    sort_order?: "asc" | "desc" | null;
  };
};

export type GetSignalsResponse = PaginatedResponse_SignalWithToken_;

export type GetSignalsError = ExceptionDetail;

export type GetTopSignalsData = {
  query?: {
    /**
     * The current page number
     */
    page?: number | null;
    /**
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * Include signals from the last X hours. Default is 24 hours.
     */
    since?: number;
  };
};

export type GetTopSignalsResponse = PaginatedResponse_SignalWithToken_;

export type GetTopSignalsError = ExceptionDetail;

export type GetSignalStatsResponse = SignalOverviewStats;

export type GetSignalStatsError = ExceptionDetail;

export type PingResponse = string;

export type PingError = ExceptionDetail;

export type GetTimeData = {
  query?: {
    type?: "iso" | "unix";
  };
};

export type GetTimeResponse = string;

export type GetTimeError = ExceptionDetail;

export type GetLogLevelResponse = LogLevel;

export type GetLogLevelError = ExceptionDetail;

export type GetUptimeData = {
  query?: {
    type?: "seconds" | "human";
  };
};

export type GetUptimeResponse = string;

export type GetUptimeError = ExceptionDetail;

export type GetMemoryUsageResponse = number;

export type GetMemoryUsageError = ExceptionDetail;

export type GetThreadsResponse = {
  [key: string]: unknown;
};

export type GetThreadsError = ExceptionDetail;

export type GetContainerLimitsResponse = {
  [key: string]: unknown;
};

export type GetContainerLimitsError = ExceptionDetail;

export type GetDependenciesData = {
  query?: {
    /**
     * List of regex patterns to match against package names. If not provided, all installed packages will be returned.
     */
    include?: Array<string>;
  };
};

export type GetDependenciesResponse = {
  [key: string]: string;
};

export type GetDependenciesError = ExceptionDetail;

export type GetMetricsResponse = unknown;

export type GetMetricsError = ExceptionDetail;
