// This file is auto-generated by @hey-api/openapi-ts

export type _Info = {
  /**
   * Token image URL
   */
  image_url?: string | null;
  /**
   * Header image URL
   */
  header?: string | null;
  /**
   * OpenGraph image URL
   */
  open_graph?: string | null;
  /**
   * List of related websites
   */
  websites?: Array<_Website>;
};

export type _Liquidity = {
  /**
   * Liquidity in USD
   */
  usd?: number;
  /**
   * Amount of base token in the pool
   */
  base?: number;
  /**
   * Amount of quote token in the pool
   */
  quote?: number;
};

export type _PriceChange = {
  /**
   * 24-hour price change percentage
   */
  h24?: number;
  /**
   * 6-hour price change percentage
   */
  h6?: number | null;
  /**
   * 1-hour price change percentage
   */
  h1?: number | null;
  /**
   * 5-minute price change percentage
   */
  m5?: number | null;
};

export type _Token = {
  /**
   * Token contract address
   */
  address: string;
  /**
   * Token name
   */
  name: string;
  /**
   * Token symbol
   */
  symbol: string;
};

export type _TxnCounts = {
  /**
   * Number of buy transactions in this window
   */
  buys?: number;
  /**
   * Number of sell transactions in this window
   */
  sells?: number;
  /**
   * Buy/sell ratio (BSR) where:
   * - ratio = buys / (buys + sells)
   * - 0.5 = neutral when there are no transactions.
   */
  readonly ratio: number;
};

export type _Txns = {
  /**
   * Buy/sell transaction counts over the last 5 minutes
   */
  m5: _TxnCounts;
  /**
   * Buy/sell transaction counts over the last hour
   */
  h1: _TxnCounts;
  /**
   * Buy/sell transaction counts over the last 6 hours
   */
  h6: _TxnCounts;
  /**
   * Buy/sell transaction counts over the last 24 hours
   */
  h24: _TxnCounts;
};

export type _Volume = {
  /**
   * 24-hour trading volume
   */
  h24?: number;
  /**
   * 6-hour trading volume
   */
  h6?: number;
  /**
   * 1-hour trading volume
   */
  h1?: number;
  /**
   * 5-minute trading volume
   */
  m5?: number;
};

export type _Website = {
  /**
   * Website URL
   */
  url: string;
  /**
   * Website label or type
   */
  label: string;
};

/**
 * Error response schema.
 */
export type ErrorResponse = {
  detail: string;
};

export type PaginatedResponse_SignalWithToken_ = {
  data: Array<SignalWithToken>;
  /**
   * The total number of items
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of items per page
   */
  page_size: number;
  /**
   * The previous page number
   */
  prev?: number | null;
  /**
   * The next page number
   */
  next?: number | null;
  /**
   * The last page number
   */
  last?: number | null;
};

/**
 * Model for signal statistics response
 */
export type SignalOverviewStats = {
  /**
   * The unix timestamp of the stats calculation
   */
  timestamp: number;
  /**
   * Total number of tokens analyzed
   */
  total: number;
  /**
   * Overall win rate as a decimal
   */
  win_rate: number;
};

/**
 * Trading signal enriched with comprehensive token metadata and information.
 */
export type SignalWithToken = {
  /**
   * Lifecycle stage
   */
  stage: string;
  /**
   * Token contract address
   */
  address: string;
  /**
   * Pair address
   */
  pair_address?: string | null;
  /**
   * Chain
   */
  chain:
    | 'solana'
    | 'ethereum'
    | 'bsc'
    | 'base'
    | 'arbitrum'
    | 'polygon'
    | 'avalanche';
  /**
   * First call time (tracker entry)
   */
  first_call_time?: string | null;
  /**
   * Baseline MC for X calculations
   */
  mc_at_call?: string | null;
  /**
   * All-time-high MC
   */
  ath_mc?: string | null;
  /**
   * Last milestone announced
   */
  last_x?: number | null;
  /**
   * The ID of the call message from the notification service
   */
  call_id?: string | null;
  /**
   * Time of the first call
   */
  called_at: string;
  /**
   * Last update time
   */
  updated_at?: string | null;
  /**
   * The token info
   */
  data?: TokenData | null;
  readonly performance: number | null;
};

/**
 * Chain
 */
export type chain =
  | 'solana'
  | 'ethereum'
  | 'bsc'
  | 'base'
  | 'arbitrum'
  | 'polygon'
  | 'avalanche';

export type TokenData = {
  /**
   * Blockchain identifier
   */
  chain_id: string;
  /**
   * DEX identifier
   */
  dex_id: string;
  /**
   * DexScreener pair URL
   */
  url: string;
  /**
   * Pair/pool address
   */
  pair_address: string;
  /**
   * Base token metadata
   */
  base_token: _Token;
  /**
   * Quote token metadata
   */
  quote_token: _Token;
  /**
   * Token price in native chain currency
   */
  price_native: number;
  /**
   * Token price in USD
   */
  price_usd: number;
  /**
   * Buy/sell transaction counts over multiple time windows
   */
  txns: _Txns;
  /**
   * Trading volume over multiple time windows
   */
  volume: _Volume;
  /**
   * Price change percentages over multiple time windows
   */
  price_change: _PriceChange;
  /**
   * Liquidity breakdown for the pair
   */
  liquidity?: _Liquidity;
  /**
   * Fully diluted valuation in USD
   */
  fdv: number;
  /**
   * Market capitalization in USD
   */
  market_cap: number;
  /**
   * Pair creation timestamp (milliseconds since epoch)
   */
  pair_created_at: number;
  /**
   * Additional token and pair metadata
   */
  info?: _Info | null;
};

export type GetSignalsData = {
  query?: {
    /**
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * The current page number
     */
    page?: number;
    /**
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * The order to sort by
     */
    sort_order?: 'asc' | 'desc' | null;
  };
};

export type GetSignalsResponse = PaginatedResponse_SignalWithToken_;

export type GetSignalsError = ErrorResponse;

export type GetTopSignalsData = {
  query?: {
    /**
     * The current page number
     */
    page?: number;
    /**
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * Include signals from the last X hours. Default is 24 hours.
     */
    since?: number;
  };
};

export type GetTopSignalsResponse = PaginatedResponse_SignalWithToken_;

export type GetTopSignalsError = ErrorResponse;

export type GetSignalStatsResponse = SignalOverviewStats;

export type GetSignalStatsError = ErrorResponse;

export type PingResponse = string;

export type PingError = ErrorResponse;

export type GetMetricsResponse = unknown;

export type GetMetricsError = ErrorResponse;
