// This file is auto-generated by @hey-api/openapi-ts

/**
 * Error response schema.
 */
export type ErrorResponse = {
  detail: string;
};

export type PaginatedResponse_SignalWithToken_ = {
  data: Array<SignalWithToken>;
  /**
   * The total number of items
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of items per page
   */
  page_size: number;
  /**
   * The previous page number
   */
  prev?: number | null;
  /**
   * The next page number
   */
  next?: number | null;
  /**
   * The last page number
   */
  last?: number | null;
};

/**
 * Model for risk assessment
 */
export type Risk = {
  /**
   * Is token rugged
   */
  rugged: boolean;
  /**
   * Overall risk score
   */
  score: number;
};

/**
 * Model for signal statistics response
 */
export type SignalOverviewStats = {
  /**
   * The unix timestamp of the stats calculation
   */
  timestamp: number;
  /**
   * Total number of tokens analyzed
   */
  total: number;
  /**
   * Overall win rate as a percentage
   */
  win_rate: number;
  /**
   * Average performance as a percentage
   */
  avg_performance: number;
  /**
   * Median performance as a percentage
   */
  median_performance: number;
  /**
   * Best performing risk category
   */
  best_risk_category?: string | null;
  /**
   * Best performing month
   */
  best_month?: string | null;
  /**
   * Best holding period
   */
  best_holding_period?: string | null;
  /**
   * Best launch hour (UTC)
   */
  best_launch_hour?: number | null;
  /**
   * Best launch day of the week
   */
  best_launch_day?: string | null;
};

/**
 * Trading volume data for a signal over different time periods.
 */
export type SignalVolume = {
  /**
   * 24-hour trading volume
   */
  day: string;
  /**
   * 1-hour trading volume
   */
  hour: string;
};

/**
 * Trading signal enriched with comprehensive token metadata and information.
 */
export type SignalWithToken = {
  /**
   * The contract address of the token
   */
  ca: string;
  /**
   * The name of the token
   */
  name: string;
  /**
   * The type of the signal
   */
  type: string;
  /**
   * The risk level of the signal
   */
  risk?: string | null;
  /**
   * The performance in percent as a string. e.g. +100%
   */
  performance: string;
  /**
   * The price of the signal
   */
  price: string;
  /**
   * The volume of the signal
   */
  volume: SignalVolume;
  /**
   * The liquidity of the signal
   */
  liquidity: string;
  /**
   * The market cap of the signal
   */
  mcap: string;
  /**
   * The timestamp of the call
   */
  called_at: number;
  /**
   * The timestamp of the last update
   */
  updated_at: number;
  /**
   * The telegram id of the signal
   */
  tg_id: string | null;
  /**
   * The token info
   */
  data: TokenData;
  /**
   * The performance in float. e.g. +100% -> 2.0
   */
  readonly performance_float: number;
};

/**
 * Main model for complete token data
 */
export type TokenData = {
  /**
   * Token details
   */
  token: TokenDetail;
  /**
   * Market cap
   */
  mcap: string;
  /**
   * Price
   */
  price: string;
  /**
   * The liquidity of the token in USD
   */
  liquidity: string;
  /**
   * Risk assessment
   */
  risk: Risk;
  /**
   * Number of buys
   */
  buys: number;
  /**
   * Number of sells
   */
  sells: number;
  /**
   * Total transactions
   */
  txns: number;
  /**
   * Number of holders
   */
  holders: number;
};

/**
 * Model for detailed token information
 */
export type TokenDetail = {
  /**
   * Token name
   */
  name: string;
  /**
   * Token symbol
   */
  symbol: string;
  /**
   * Token mint address (aka contract address)
   */
  mint: string;
  /**
   * Token description
   */
  description?: string | null;
  /**
   * Token image URL
   */
  image?: string | null;
  /**
   * Social media links
   */
  strictSocials?: {
    [key: string]: unknown;
  };
};

export type GetSignalsData = {
  query?: {
    /**
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * The current page number
     */
    page?: number;
    /**
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * The order to sort by
     */
    sort_order?: "asc" | "desc" | null;
  };
};

export type GetSignalsResponse = PaginatedResponse_SignalWithToken_;

export type GetSignalsError = ErrorResponse;

export type GetTopSignalsData = {
  query?: {
    /**
     * The current page number
     */
    page?: number;
    /**
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * Include signals from the last X hours. Default is 24 hours.
     */
    since?: number;
  };
};

export type GetTopSignalsResponse = PaginatedResponse_SignalWithToken_;

export type GetTopSignalsError = ErrorResponse;

export type GetSignalStatsResponse = SignalOverviewStats;

export type GetSignalStatsError = ErrorResponse;

export type PingResponse = string;

export type PingError = ErrorResponse;

export type GetMetricsResponse = unknown;

export type GetMetricsError = ErrorResponse;
