// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorIdentifierSchema = {
  type: "string",
  title: "ApiErrorIdentifier",
  description: "API error identifiers",
} as const;

export const ApiErrorLevelSchema = {
  type: "string",
  title: "ApiErrorLevel",
  description: "API error levels",
} as const;

export const ApiErrorTypeSchema = {
  type: "string",
  title: "ApiErrorType",
  description: "Type of API error",
} as const;

export const CoinsSchema = {
  type: "string",
  enum: ["BTC", "ETH", "XRP", "SOL", "LINK", "BCH", "LTC", "BNB"],
  title: "Coins",
} as const;

export const ExceptionDetailSchema = {
  properties: {
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
      description: "An additional error message",
    },
    code: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description: "The unique error code",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "The type of error",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "The level of the error",
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      description: "The HTTP status code",
    },
    details: {
      title: "Details",
      description: "Additional details about the error",
    },
  },
  type: "object",
  required: ["code", "type", "level", "status_code"],
  title: "ExceptionDetail",
  description:
    "This is the detail of the exception. It is used to enrich the exception with additional information by unwrapping the ApiError into its components.",
} as const;

export const HistoricalSentimentCoinSchema = {
  properties: {
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
      description: "The timestamp of the entry",
    },
    symbol: {
      type: "string",
      title: "Symbol",
      description: "The symbol of the coin",
    },
    open: {
      type: "number",
      title: "Open",
      description: "The opening price of the coin",
    },
    close: {
      type: "number",
      title: "Close",
      description: "The closing price of the coin",
    },
    high: {
      type: "number",
      title: "High",
      description: "The highest price of the coin",
    },
    low: {
      type: "number",
      title: "Low",
      description: "The lowest price of the coin",
    },
    volume_24h: {
      type: "integer",
      title: "Volume 24H",
      description: "The volume of the coin in the last 24 hours",
    },
    market_cap: {
      type: "integer",
      title: "Market Cap",
      description: "The market cap of the coin",
    },
    circulating_supply: {
      type: "integer",
      title: "Circulating Supply",
      description: "The circulating supply of the coin",
    },
    sentiment: {
      type: "integer",
      title: "Sentiment",
      description: "The sentiment value",
    },
    spam: {
      type: "integer",
      title: "Spam",
      description: "The spam rating",
    },
    galaxy_score: {
      type: "integer",
      title: "Galaxy Score",
      description: "The galaxy score",
    },
    volatility: {
      type: "integer",
      title: "Volatility",
      description: "The volatility",
    },
    alt_rank: {
      type: "integer",
      title: "Alt Rank",
      description: "The alt rank",
    },
    contributors_active: {
      type: "integer",
      title: "Contributors Active",
      description: "The number of active contributors",
    },
    contributors_created: {
      type: "integer",
      title: "Contributors Created",
      description: "The number of contributors created",
    },
    posts_active: {
      type: "integer",
      title: "Posts Active",
      description: "The number of active posts",
    },
    posts_created: {
      type: "integer",
      title: "Posts Created",
      description: "The number of posts created",
    },
    interactions: {
      type: "integer",
      title: "Interactions",
      description: "The number of interactions",
    },
    social_dominance: {
      type: "number",
      title: "Social Dominance",
      description: "The social dominance percentage",
    },
  },
  type: "object",
  required: [
    "timestamp",
    "symbol",
    "open",
    "close",
    "high",
    "low",
    "volume_24h",
    "market_cap",
    "circulating_supply",
    "sentiment",
    "spam",
    "galaxy_score",
    "volatility",
    "alt_rank",
    "contributors_active",
    "contributors_created",
    "posts_active",
    "posts_created",
    "interactions",
    "social_dominance",
  ],
  title: "HistoricalSentimentCoin",
} as const;

export const OrderEnumSchema = {
  type: "string",
  enum: ["DESC", "ASC"],
  title: "OrderEnum",
} as const;

export const PaginationSchema = {
  properties: {
    currentPage: {
      type: "integer",
      title: "Currentpage",
    },
    totalPages: {
      type: "integer",
      title: "Totalpages",
    },
    totalItems: {
      type: "integer",
      title: "Totalitems",
    },
    itemsPerPage: {
      type: "integer",
      title: "Itemsperpage",
    },
  },
  type: "object",
  required: ["currentPage", "totalPages", "totalItems", "itemsPerPage"],
  title: "Pagination",
} as const;

export const SentimentCoinResponseSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/HistoricalSentimentCoin",
      },
      type: "array",
      title: "Data",
    },
    pagination: {
      $ref: "#/components/schemas/Pagination",
    },
  },
  type: "object",
  required: ["data", "pagination"],
  title: "SentimentCoinResponse",
} as const;

export const VITimeframeEnumSchema = {
  type: "string",
  enum: ["1h", "1d"],
  title: "VITimeframeEnum",
} as const;

export const VolatilityIndexSchema = {
  properties: {
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
    symbol: {
      type: "string",
      title: "Symbol",
    },
    timeframe: {
      type: "string",
      title: "Timeframe",
    },
    open: {
      type: "number",
      title: "Open",
    },
    high: {
      type: "number",
      title: "High",
    },
    low: {
      type: "number",
      title: "Low",
    },
    close: {
      type: "number",
      title: "Close",
    },
  },
  type: "object",
  required: [
    "timestamp",
    "symbol",
    "timeframe",
    "open",
    "high",
    "low",
    "close",
  ],
  title: "VolatilityIndex",
} as const;

export const VolatilityIndexResponseSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/VolatilityIndex",
      },
      type: "array",
      title: "Data",
    },
    pagination: {
      $ref: "#/components/schemas/Pagination",
    },
  },
  type: "object",
  required: ["data", "pagination"],
  title: "VolatilityIndexResponse",
} as const;
