import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  PingError,
  PingResponse,
  GetTimeData,
  GetTimeError,
  GetTimeResponse,
  GetConfigError,
  GetConfigResponse,
  GetSymbolsError,
  GetSymbolsResponse,
  GetSentimentData,
  GetSentimentError,
  GetSentimentResponse,
  GetVolatilityIndexSymbolsError,
  GetVolatilityIndexSymbolsResponse,
  GetVolatilityIndexData,
  GetVolatilityIndexError,
  GetVolatilityIndexResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Time
   * Returns the current time in the specified format.
   */
  const getTime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetTimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTimeResponse,
      GetTimeError,
      ThrowOnError
    >({
      ...options,
      url: "/time",
    });
  };

  /**
   * Config
   * Returns the version of the crypticorn library and the environment.
   */
  const getConfig = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetConfigResponse,
      GetConfigError,
      ThrowOnError
    >({
      ...options,
      url: "/config",
    });
  };

  /**
   * Get Symbols
   * Retrieve a list of unique symbols.
   */
  const getSymbols = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSymbolsResponse,
      GetSymbolsError,
      ThrowOnError
    >({
      ...options,
      url: "/symbols",
    });
  };

  /**
   * Get Sentiment Coin
   * Retrieve sentiment data for a specific coin with pagination.
   */
  const getSentiment = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetSentimentData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSentimentResponse,
      GetSentimentError,
      ThrowOnError
    >({
      ...options,
      url: "/{coin}",
    });
  };

  /**
   * Get Volatility Index Symbols
   * Retrieve a list of unique volatility index symbols.
   */
  const getVolatilityIndexSymbols = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetVolatilityIndexSymbolsResponse,
      GetVolatilityIndexSymbolsError,
      ThrowOnError
    >({
      ...options,
      url: "/volatility_index/symbols",
    });
  };

  /**
   * Get Volatility Index
   * Retrieve volatility index data for a specific symbol and timeframe with pagination.
   */
  const getVolatilityIndex = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetVolatilityIndexData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetVolatilityIndexResponse,
      GetVolatilityIndexError,
      ThrowOnError
    >({
      ...options,
      url: "/volatility_index/{symbol}",
    });
  };

  return {
    ping,
    getTime,
    getConfig,
    getSymbols,
    getSentiment,
    getVolatilityIndexSymbols,
    getVolatilityIndex,
  };
}
