// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorIdentifierSchema = {
  type: "string",
  enum: [
    "allocation_below_current_exposure",
    "allocation_below_min_amount",
    "allocation_limit_exceeded",
    "black_swan",
    "bot_already_deleted",
    "bot_stopping_completed",
    "bot_stopping_started",
    "cancelled_open_order",
    "client_order_id_already_exists",
    "invalid_content_type",
    "delete_bot_error",
    "exchange_http_request_error",
    "exchange_invalid_parameter",
    "exchange_invalid_signature",
    "exchange_invalid_timestamp",
    "exchange_ip_address_is_not_authorized",
    "exchange_key_already_exists",
    "exchange_key_in_use",
    "exchange_system_under_maintenance",
    "exchange_rate_limit_exceeded",
    "insufficient_permissions_spot_and_futures_required",
    "exchange_service_temporarily_unavailable",
    "exchange_system_is_busy",
    "exchange_system_configuration_error",
    "exchange_internal_system_error",
    "exchange_user_account_is_frozen",
    "api_key_expired",
    "bearer_token_expired",
    "failed_open_order",
    "forbidden",
    "hedge_mode_not_active",
    "insufficient_balance",
    "insufficient_margin",
    "insufficient_scopes",
    "invalid_api_key",
    "invalid_basic_auth",
    "invalid_bearer",
    "invalid_data",
    "invalid_data_response",
    "invalid_exchange_key",
    "invalid_model_name",
    "leverage_limit_exceeded",
    "order_violates_liquidation_price_constraints",
    "margin_mode_clash",
    "name_not_unique",
    "no_credentials",
    "now_api_down",
    "object_already_exists",
    "object_created",
    "object_deleted",
    "object_locked",
    "object_not_found",
    "object_updated",
    "order_is_already_filled",
    "order_is_being_processed",
    "order_quantity_limit_exceeded",
    "order_does_not_exist",
    "order_price_is_invalid",
    "order_size_too_large",
    "order_size_too_small",
    "orphan_open_order",
    "orphan_close_order",
    "position_limit_exceeded",
    "position_does_not_exist",
    "position_opening_temporarily_suspended",
    "post_only_order_would_immediately_match",
    "request_scope_limit_exceeded",
    "risk_limit_exceeded",
    "rpc_timeout",
    "system_settlement_in_process",
    "strategy_disabled",
    "strategy_leverage_mismatch",
    "strategy_not_supporting_exchange",
    "success",
    "symbol_does_not_exist",
    "trading_action_expired",
    "trading_action_skipped_bot_stopping",
    "trading_has_been_locked",
    "trading_is_suspended",
    "unknown_error_occurred",
    "requested_resource_not_found",
  ],
  title: "ApiErrorIdentifier",
  description: "Unique identifier of the API error.",
} as const;

export const ApiErrorLevelSchema = {
  type: "string",
  enum: ["error", "info", "success", "warning"],
  title: "ApiErrorLevel",
  description: "Level of the API error.",
} as const;

export const ApiErrorTypeSchema = {
  type: "string",
  enum: ["user error", "exchange error", "server error", "no error"],
  title: "ApiErrorType",
  description: "Type of the API error.",
} as const;

export const ChangeInTimeframeSchema = {
  properties: {
    pair: {
      type: "string",
      title: "Pair",
    },
    change: {
      type: "number",
      title: "Change",
    },
  },
  type: "object",
  required: ["pair", "change"],
  title: "ChangeInTimeframe",
  description:
    "Price change data for a trading pair over a specific timeframe.",
} as const;

export const ExceptionDetailSchema = {
  properties: {
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
      description: "An additional error message",
    },
    code: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description: "The unique error code",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "The type of error",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "The level of the error",
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      description: "The HTTP status code",
    },
    details: {
      title: "Details",
      description: "Additional details about the error",
    },
  },
  type: "object",
  required: ["code", "type", "level", "status_code"],
  title: "ExceptionDetail",
  description: "Exception details returned to the client.",
} as const;

export const FundingRateSchema = {
  properties: {
    timestamp: {
      type: "integer",
      title: "Timestamp",
      description: "The timestamp of the funding rate",
    },
    funding_rate: {
      type: "number",
      title: "Funding Rate",
      description: "The funding rate",
    },
  },
  type: "object",
  required: ["timestamp", "funding_rate"],
  title: "FundingRate",
  description:
    "Individual funding rate entry with timestamp and rate value for futures trading.",
} as const;

export const FundingRateResponseSchema = {
  properties: {
    symbol: {
      type: "string",
      title: "Symbol",
      description: "The symbol of the funding rate",
    },
    funding_interval: {
      type: "string",
      title: "Funding Interval",
      description: "The funding interval",
    },
    funding_rates: {
      items: {
        $ref: "#/components/schemas/FundingRate",
      },
      type: "array",
      title: "Funding Rates",
      description: "The funding rates",
    },
  },
  type: "object",
  required: ["symbol", "funding_interval", "funding_rates"],
  title: "FundingRateResponse",
  description:
    "Response containing historical funding rates for a specific trading symbol.",
} as const;

export const InternalExchangeSchema = {
  type: "string",
  enum: ["kucoin", "bingx", "binance", "bybit", "hyperliquid", "bitget"],
  title: "InternalExchange",
  description: "All exchanges we are using, including public (Exchange)",
} as const;

export const LogLevelSchema = {
  type: "string",
  enum: ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
  title: "LogLevel",
} as const;

export const MarketTypeSchema = {
  type: "string",
  enum: ["spot", "futures"],
  title: "MarketType",
  description: "Market types",
} as const;

export const OHLCVSchema = {
  properties: {
    timestamp: {
      type: "integer",
      title: "Timestamp",
      description: "Timestamp in seconds",
    },
    open: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Open",
      description: "Open prices",
    },
    high: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "High",
      description: "High prices",
    },
    low: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Low",
      description: "Low prices",
    },
    close: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Close",
      description: "Close prices",
    },
    volume: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Volume",
      description: "Volume",
    },
  },
  type: "object",
  required: ["timestamp", "open", "high", "low", "close", "volume"],
  title: "OHLCV",
} as const;

export const ResolutionSchema = {
  type: "string",
  enum: ["15", "30", "60", "240", "1D"],
  title: "Resolution",
} as const;

export const SearchSymbolSchema = {
  properties: {
    symbol: {
      type: "string",
      title: "Symbol",
      description: "Symbol identifier",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Human-readable symbol description",
    },
    exchange: {
      $ref: "#/components/schemas/InternalExchange",
      description: "Exchange where symbol is traded",
    },
    type: {
      type: "string",
      title: "Type",
      description: "Symbol type classification",
    },
  },
  type: "object",
  required: ["symbol", "description", "exchange", "type"],
  title: "SearchSymbol",
  description: "Symbol search result for UDF symbol lookup functionality.",
} as const;

export const SortDirectionSchema = {
  type: "string",
  enum: ["asc", "desc"],
  title: "SortDirection",
  description:
    "Sort direction options for data ordering (ascending or descending).",
} as const;

export const SymbolGroupSchema = {
  properties: {
    symbol: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Symbol",
      description: "List of symbol identifiers in the group",
      default: [],
    },
  },
  type: "object",
  title: "SymbolGroup",
  description: "Group of symbols for batch operations in UDF requests.",
} as const;

export const SymbolInfoSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Symbol name identifier",
    },
    "exchange-traded": {
      type: "string",
      title: "Exchange-Traded",
      description: "Exchange where symbol is traded",
    },
    "exchange-listed": {
      type: "string",
      title: "Exchange-Listed",
      description: "Exchange where symbol is listed",
    },
    timezone: {
      type: "string",
      title: "Timezone",
      description: "Timezone for symbol trading hours",
    },
    minmov: {
      type: "integer",
      title: "Minmov",
      description: "Minimum price movement",
    },
    minmov2: {
      type: "integer",
      title: "Minmov2",
      description: "Secondary minimum price movement",
    },
    pointvalue: {
      type: "integer",
      title: "Pointvalue",
      description: "Point value for price calculations",
    },
    session: {
      type: "string",
      title: "Session",
      description: "Trading session hours",
    },
    has_intraday: {
      type: "boolean",
      title: "Has Intraday",
      description: "Whether intraday data is available",
    },
    has_no_volume: {
      type: "boolean",
      title: "Has No Volume",
      description: "Whether volume data is unavailable",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Human-readable symbol description",
    },
    type: {
      type: "string",
      title: "Type",
      description: "Symbol type classification",
    },
    supported_resolutions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Supported Resolutions",
      description: "List of supported time resolutions",
    },
    pricescale: {
      type: "integer",
      title: "Pricescale",
      description: "Price scale factor for decimal places",
    },
    ticker: {
      type: "string",
      title: "Ticker",
      description: "Symbol ticker identifier",
    },
  },
  type: "object",
  required: [
    "name",
    "exchange-traded",
    "exchange-listed",
    "timezone",
    "minmov",
    "minmov2",
    "pointvalue",
    "session",
    "has_intraday",
    "has_no_volume",
    "description",
    "type",
    "supported_resolutions",
    "pricescale",
    "ticker",
  ],
  title: "SymbolInfo",
  description:
    "Comprehensive symbol information for UDF charting library compatibility.",
} as const;

export const SymbolTypeSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Display name of the symbol type",
    },
    value: {
      type: "string",
      title: "Value",
      description: "Internal value identifier for the symbol type",
    },
  },
  type: "object",
  required: ["name", "value"],
  title: "SymbolType",
  description: "Symbol type definition for UDF data feed configuration.",
} as const;

export const TimeframeSchema = {
  type: "string",
  enum: ["15m", "30m", "1h", "4h", "1d"],
  title: "Timeframe",
  description:
    "Available timeframes for candlestick and technical analysis data.",
} as const;

export const UDFConfigSchema = {
  properties: {
    supported_resolutions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Supported Resolutions",
      description: "List of supported time resolutions",
    },
    supports_group_request: {
      type: "boolean",
      title: "Supports Group Request",
      description: "Whether grouped symbol requests are supported",
      default: false,
    },
    supports_marks: {
      type: "boolean",
      title: "Supports Marks",
      description: "Whether chart marks are supported",
      default: false,
    },
    supports_search: {
      type: "boolean",
      title: "Supports Search",
      description: "Whether symbol search is supported",
      default: true,
    },
    supports_timescale_marks: {
      type: "boolean",
      title: "Supports Timescale Marks",
      description: "Whether timescale marks are supported",
      default: false,
    },
    supports_time: {
      type: "boolean",
      title: "Supports Time",
      description: "Whether server time is supported",
      default: true,
    },
    exchanges: {
      items: {
        $ref: "#/components/schemas/InternalExchange",
      },
      type: "array",
      title: "Exchanges",
      description: "List of available exchanges",
    },
    symbols_types: {
      items: {
        $ref: "#/components/schemas/SymbolType",
      },
      type: "array",
      title: "Symbols Types",
      description: "List of supported symbol types",
    },
    currency_codes: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Currency Codes",
      description: "List of supported currency codes",
    },
    supported_markets: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Supported Markets",
      description: "List of supported market types",
    },
  },
  type: "object",
  required: [
    "supported_resolutions",
    "exchanges",
    "symbols_types",
    "currency_codes",
    "supported_markets",
  ],
  title: "UDFConfig",
  description:
    "Universal Data Feed configuration for charting library compatibility.",
} as const;
