// This file is auto-generated by @hey-api/openapi-ts

export const BaseResponse_HealthCheckResponse_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/HealthCheckResponse",
        },
        {
          type: "null",
        },
      ],
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
  },
  type: "object",
  title: "BaseResponse[HealthCheckResponse]",
} as const;

export const BaseResponse_List_FundingRateResponse__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
    },
    data: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/FundingRateResponse",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
  },
  type: "object",
  title: "BaseResponse[List[FundingRateResponse]]",
} as const;

export const BaseResponse_List_str__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
    },
    data: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
  },
  type: "object",
  title: "BaseResponse[List[str]]",
} as const;

export const BaseResponse_OHLCVResponse_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/OHLCVResponse",
        },
        {
          type: "null",
        },
      ],
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
  },
  type: "object",
  title: "BaseResponse[OHLCVResponse]",
} as const;

export const ErrorResponseSchema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: false,
    },
    message: {
      type: "string",
      title: "Message",
    },
    error_code: {
      type: "string",
      title: "Error Code",
    },
    details: {
      anyOf: [
        {
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Details",
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
  },
  type: "object",
  required: ["message", "error_code"],
  title: "ErrorResponse",
} as const;

export const ExchangeSchema = {
  properties: {
    value: {
      type: "string",
      title: "Value",
    },
    name: {
      type: "string",
      title: "Name",
    },
    desc: {
      type: "string",
      title: "Desc",
    },
  },
  type: "object",
  required: ["value", "name", "desc"],
  title: "Exchange",
} as const;

export const FundingRateResponseSchema = {
  properties: {
    symbol: {
      type: "string",
      title: "Symbol",
    },
    timestamp: {
      type: "string",
      format: "date-time",
      title: "Timestamp",
    },
    funding_rate: {
      type: "number",
      title: "Funding Rate",
    },
  },
  type: "object",
  required: ["symbol", "timestamp", "funding_rate"],
  title: "FundingRateResponse",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthCheckResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      default: "ok",
    },
    version: {
      type: "string",
      title: "Version",
      default: "1.0.0",
    },
  },
  type: "object",
  title: "HealthCheckResponse",
} as const;

export const HistoryErrorResponseSchema = {
  properties: {
    s: {
      type: "string",
      title: "S",
      default: "error",
    },
    errmsg: {
      type: "string",
      title: "Errmsg",
    },
  },
  type: "object",
  required: ["errmsg"],
  title: "HistoryErrorResponse",
} as const;

export const HistoryNoDataResponseSchema = {
  properties: {
    s: {
      type: "string",
      title: "S",
      default: "no_data",
    },
    t: {
      items: {
        type: "integer",
      },
      type: "array",
      title: "T",
      default: [],
    },
    o: {
      items: {
        type: "number",
      },
      type: "array",
      title: "O",
      default: [],
    },
    h: {
      items: {
        type: "number",
      },
      type: "array",
      title: "H",
      default: [],
    },
    l: {
      items: {
        type: "number",
      },
      type: "array",
      title: "L",
      default: [],
    },
    c: {
      items: {
        type: "number",
      },
      type: "array",
      title: "C",
      default: [],
    },
    v: {
      items: {
        type: "number",
      },
      type: "array",
      title: "V",
      default: [],
    },
  },
  type: "object",
  title: "HistoryNoDataResponse",
} as const;

export const HistorySuccessResponseSchema = {
  properties: {
    s: {
      type: "string",
      title: "S",
      default: "ok",
    },
    t: {
      items: {
        type: "integer",
      },
      type: "array",
      title: "T",
    },
    o: {
      items: {
        type: "number",
      },
      type: "array",
      title: "O",
    },
    h: {
      items: {
        type: "number",
      },
      type: "array",
      title: "H",
    },
    l: {
      items: {
        type: "number",
      },
      type: "array",
      title: "L",
    },
    c: {
      items: {
        type: "number",
      },
      type: "array",
      title: "C",
    },
    v: {
      items: {
        type: "number",
      },
      type: "array",
      title: "V",
    },
  },
  type: "object",
  required: ["t", "o", "h", "l", "c", "v"],
  title: "HistorySuccessResponse",
} as const;

export const MarketSchema = {
  type: "string",
  enum: ["spot", "futures"],
  title: "Market",
} as const;

export const OHLCVResponseSchema = {
  properties: {
    timestamp: {
      items: {
        type: "string",
        format: "date-time",
      },
      type: "array",
      title: "Timestamp",
    },
    open: {
      items: {
        type: "number",
      },
      type: "array",
      title: "Open",
    },
    high: {
      items: {
        type: "number",
      },
      type: "array",
      title: "High",
    },
    low: {
      items: {
        type: "number",
      },
      type: "array",
      title: "Low",
    },
    close: {
      items: {
        type: "number",
      },
      type: "array",
      title: "Close",
    },
    volume: {
      items: {
        type: "number",
      },
      type: "array",
      title: "Volume",
    },
  },
  type: "object",
  required: ["timestamp", "open", "high", "low", "close", "volume"],
  title: "OHLCVResponse",
} as const;

export const ResolutionSchema = {
  type: "string",
  enum: ["15", "30", "60", "240", "1D"],
  title: "Resolution",
} as const;

export const SearchSymbolResponseSchema = {
  properties: {
    symbol: {
      type: "string",
      title: "Symbol",
    },
    full_name: {
      type: "string",
      title: "Full Name",
    },
    description: {
      type: "string",
      title: "Description",
    },
    exchange: {
      type: "string",
      title: "Exchange",
    },
    ticker: {
      type: "string",
      title: "Ticker",
    },
    type: {
      type: "string",
      title: "Type",
    },
  },
  type: "object",
  required: [
    "symbol",
    "full_name",
    "description",
    "exchange",
    "ticker",
    "type",
  ],
  title: "SearchSymbolResponse",
} as const;

export const SortDirectionSchema = {
  type: "string",
  enum: ["asc", "desc"],
  title: "SortDirection",
} as const;

export const SymbolGroupResponseSchema = {
  properties: {
    symbol: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Symbol",
      default: [],
    },
  },
  type: "object",
  title: "SymbolGroupResponse",
} as const;

export const SymbolInfoResponseSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    "exchange-traded": {
      type: "string",
      title: "Exchange-Traded",
    },
    "exchange-listed": {
      type: "string",
      title: "Exchange-Listed",
    },
    timezone: {
      type: "string",
      title: "Timezone",
    },
    minmov: {
      type: "integer",
      title: "Minmov",
    },
    minmov2: {
      type: "integer",
      title: "Minmov2",
    },
    pointvalue: {
      type: "integer",
      title: "Pointvalue",
    },
    session: {
      type: "string",
      title: "Session",
    },
    has_intraday: {
      type: "boolean",
      title: "Has Intraday",
    },
    has_no_volume: {
      type: "boolean",
      title: "Has No Volume",
    },
    description: {
      type: "string",
      title: "Description",
    },
    type: {
      type: "string",
      title: "Type",
    },
    supported_resolutions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Supported Resolutions",
    },
    pricescale: {
      type: "integer",
      title: "Pricescale",
    },
    ticker: {
      type: "string",
      title: "Ticker",
    },
  },
  type: "object",
  required: [
    "name",
    "exchange-traded",
    "exchange-listed",
    "timezone",
    "minmov",
    "minmov2",
    "pointvalue",
    "session",
    "has_intraday",
    "has_no_volume",
    "description",
    "type",
    "supported_resolutions",
    "pricescale",
    "ticker",
  ],
  title: "SymbolInfoResponse",
} as const;

export const SymbolTypeSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    value: {
      type: "string",
      title: "Value",
    },
  },
  type: "object",
  required: ["name", "value"],
  title: "SymbolType",
} as const;

export const TimeframeSchema = {
  type: "string",
  enum: ["15m", "30m", "1h", "4h", "1d"],
  title: "Timeframe",
} as const;

export const UDFConfigResponseSchema = {
  properties: {
    supported_resolutions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Supported Resolutions",
    },
    supports_group_request: {
      type: "boolean",
      title: "Supports Group Request",
      default: false,
    },
    supports_marks: {
      type: "boolean",
      title: "Supports Marks",
      default: false,
    },
    supports_search: {
      type: "boolean",
      title: "Supports Search",
      default: true,
    },
    supports_timescale_marks: {
      type: "boolean",
      title: "Supports Timescale Marks",
      default: false,
    },
    supports_time: {
      type: "boolean",
      title: "Supports Time",
      default: true,
    },
    exchanges: {
      items: {
        $ref: "#/components/schemas/Exchange",
      },
      type: "array",
      title: "Exchanges",
    },
    symbols_types: {
      items: {
        $ref: "#/components/schemas/SymbolType",
      },
      type: "array",
      title: "Symbols Types",
    },
    currency_codes: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Currency Codes",
    },
    supported_markets: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Supported Markets",
    },
  },
  type: "object",
  required: [
    "supported_resolutions",
    "exchanges",
    "symbols_types",
    "currency_codes",
    "supported_markets",
  ],
  title: "UDFConfigResponse",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
