// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";
import type {
  GetConfigUdfConfigGetError,
  GetConfigUdfConfigGetResponse,
  SearchSymbolsUdfSearchGetData,
  SearchSymbolsUdfSearchGetError,
  SearchSymbolsUdfSearchGetResponse,
  GetSymbolUdfSymbolsGetData,
  GetSymbolUdfSymbolsGetError,
  GetSymbolUdfSymbolsGetResponse,
  GetHistoryUdfHistoryGetData,
  GetHistoryUdfHistoryGetError,
  GetHistoryUdfHistoryGetResponse,
  GetServerTimeUdfTimeGetError,
  GetServerTimeUdfTimeGetResponse,
  GetSymbolInfoUdfSymbolInfoGetData,
  GetSymbolInfoUdfSymbolInfoGetError,
  GetSymbolInfoUdfSymbolInfoGetResponse,
  OptionsHandlerUdfPathOptionsData,
  OptionsHandlerUdfPathOptionsError,
  OptionsHandlerUdfPathOptionsResponse,
  IndexGetError,
  IndexGetResponse,
  GetOhlcvMarketTimeframeSymbolGetData,
  GetOhlcvMarketTimeframeSymbolGetError,
  GetOhlcvMarketTimeframeSymbolGetResponse,
  FundingRateFundingRatesSymbolGetData,
  FundingRateFundingRatesSymbolGetError,
  FundingRateFundingRatesSymbolGetResponse,
  SymbolsSymbolsMarketGetData,
  SymbolsSymbolsMarketGetError,
  SymbolsSymbolsMarketGetResponse,
} from "./types.gen";
export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  /**
   * Get Config
   */
  const getConfigUdfConfigGet = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetConfigUdfConfigGetResponse,
      GetConfigUdfConfigGetError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/config",
    });
  };

  /**
   * Search Symbols
   * Called when a user searches for symbols in TradingView
   */
  const searchSymbolsUdfSearchGet = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<SearchSymbolsUdfSearchGetData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      SearchSymbolsUdfSearchGetResponse,
      SearchSymbolsUdfSearchGetError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/search",
    });
  };

  /**
   * Get Symbol
   */
  const getSymbolUdfSymbolsGet = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetSymbolUdfSymbolsGetData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSymbolUdfSymbolsGetResponse,
      GetSymbolUdfSymbolsGetError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/symbols",
    });
  };

  /**
   * Get History
   */
  const getHistoryUdfHistoryGet = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetHistoryUdfHistoryGetData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetHistoryUdfHistoryGetResponse,
      GetHistoryUdfHistoryGetError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/history",
    });
  };

  /**
   * Get Server Time
   */
  const getServerTimeUdfTimeGet = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetServerTimeUdfTimeGetResponse,
      GetServerTimeUdfTimeGetError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/time",
    });
  };

  /**
   * Get Symbol Info
   * Handle symbol info requests for different groups
   */
  const getSymbolInfoUdfSymbolInfoGet = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<
      GetSymbolInfoUdfSymbolInfoGetData,
      ThrowOnError
    >,
  ) => {
    return (options?.client ?? client).get<
      GetSymbolInfoUdfSymbolInfoGetResponse,
      GetSymbolInfoUdfSymbolInfoGetError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/symbol_info",
    });
  };

  /**
   * Options Handler
   * Handle OPTIONS requests for all UDF endpoints
   */
  const optionsHandlerUdfPathOptions = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<
      OptionsHandlerUdfPathOptionsData,
      ThrowOnError
    >,
  ) => {
    return (options?.client ?? client).options<
      OptionsHandlerUdfPathOptionsResponse,
      OptionsHandlerUdfPathOptionsError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/{path}",
    });
  };

  /**
   * Index
   * Health check endpoint to verify if the API is running.
   */
  const indexGet = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      IndexGetResponse,
      IndexGetError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Get Ohlcv
   * Retrieve OHLCV (Open, High, Low, Close, Volume) data for a specific market, timeframe, and symbol.
   */
  const getOhlcvMarketTimeframeSymbolGet = <
    ThrowOnError extends boolean = false,
  >(
    options: OptionsLegacyParser<
      GetOhlcvMarketTimeframeSymbolGetData,
      ThrowOnError
    >,
  ) => {
    return (options?.client ?? client).get<
      GetOhlcvMarketTimeframeSymbolGetResponse,
      GetOhlcvMarketTimeframeSymbolGetError,
      ThrowOnError
    >({
      ...options,
      url: "/{market}/{timeframe}/{symbol}",
    });
  };

  /**
   * Funding Rate
   * Retrieve funding rate data for a specific symbol in the futures market.
   */
  const fundingRateFundingRatesSymbolGet = <
    ThrowOnError extends boolean = false,
  >(
    options: OptionsLegacyParser<
      FundingRateFundingRatesSymbolGetData,
      ThrowOnError
    >,
  ) => {
    return (options?.client ?? client).get<
      FundingRateFundingRatesSymbolGetResponse,
      FundingRateFundingRatesSymbolGetError,
      ThrowOnError
    >({
      ...options,
      url: "/funding_rates/{symbol}",
    });
  };

  /**
   * Symbols
   * Retrieve a list of whitelisted symbols for a specific market.
   */
  const symbolsSymbolsMarketGet = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<SymbolsSymbolsMarketGetData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      SymbolsSymbolsMarketGetResponse,
      SymbolsSymbolsMarketGetError,
      ThrowOnError
    >({
      ...options,
      url: "/symbols/{market}",
    });
  };

  return {
    getConfigUdfConfigGet,
    searchSymbolsUdfSearchGet,
    getSymbolUdfSymbolsGet,
    getHistoryUdfHistoryGet,
    getServerTimeUdfTimeGet,
    getSymbolInfoUdfSymbolInfoGet,
    optionsHandlerUdfPathOptions,
    indexGet,
    getOhlcvMarketTimeframeSymbolGet,
    fundingRateFundingRatesSymbolGet,
    symbolsSymbolsMarketGet,
  };
}
