// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";
import type {
  GetUdfConfigError,
  GetUdfConfigResponse,
  SearchSymbolsData,
  SearchSymbolsError,
  SearchSymbolsResponse,
  GetSymbolData,
  GetSymbolError,
  GetSymbolResponse,
  GetUdfHistoryData,
  GetUdfHistoryError,
  GetUdfHistoryResponse,
  GetServerTimeError,
  GetServerTimeResponse,
  GetSymbolInfoData,
  GetSymbolInfoError,
  GetSymbolInfoResponse,
  OptionsHandlerData,
  OptionsHandlerError,
  OptionsHandlerResponse,
  IndexGetError,
  IndexGetResponse,
  GetOhlcvData,
  GetOhlcvError,
  GetOhlcvResponse,
  GetFundingRatesData,
  GetFundingRatesError,
  GetFundingRatesResponse,
  GetKlinesSymbolsData,
  GetKlinesSymbolsError,
  GetKlinesSymbolsResponse,
  GetChangeInTimeframeData,
  GetChangeInTimeframeError,
  GetChangeInTimeframeResponse,
} from "./types.gen";
export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  /**
   * Get Config
   */
  const getUdfConfig = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetUdfConfigResponse,
      GetUdfConfigError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/config",
    });
  };

  /**
   * Search Symbols
   * Called when a user searches for symbols in TradingView
   */
  const searchSymbols = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<SearchSymbolsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      SearchSymbolsResponse,
      SearchSymbolsError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/search",
    });
  };

  /**
   * Get Symbol
   */
  const getSymbol = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetSymbolData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSymbolResponse,
      GetSymbolError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/symbols",
    });
  };

  /**
   * Get History
   */
  const getUdfHistory = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetUdfHistoryData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetUdfHistoryResponse,
      GetUdfHistoryError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/history",
    });
  };

  /**
   * Get Server Time
   */
  const getServerTime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetServerTimeResponse,
      GetServerTimeError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/time",
    });
  };

  /**
   * Get Symbol Info
   * Handle symbol info requests for different groups
   */
  const getSymbolInfo = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetSymbolInfoData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSymbolInfoResponse,
      GetSymbolInfoError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/symbol_info",
    });
  };

  /**
   * Options Handler
   * Handle OPTIONS requests for all UDF endpoints
   */
  const optionsHandler = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<OptionsHandlerData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).options<
      OptionsHandlerResponse,
      OptionsHandlerError,
      ThrowOnError
    >({
      ...options,
      url: "/udf/{path}",
    });
  };

  /**
   * Index
   * Health check endpoint to verify if the API is running.
   */
  const indexGet = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      IndexGetResponse,
      IndexGetError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Get Ohlcv
   * Retrieve OHLCV (Open, High, Low, Close, Volume) data for a specific market, timeframe, and symbol.
   */
  const getOhlcv = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetOhlcvData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetOhlcvResponse,
      GetOhlcvError,
      ThrowOnError
    >({
      ...options,
      url: "/{market}/{timeframe}/{symbol}",
    });
  };

  /**
   * Funding Rate
   * Retrieve funding rate data for a specific symbol in the futures market.
   */
  const getFundingRates = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetFundingRatesData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetFundingRatesResponse,
      GetFundingRatesError,
      ThrowOnError
    >({
      ...options,
      url: "/funding_rates/{symbol}",
    });
  };

  /**
   * Symbols
   * Retrieve a list of whitelisted symbols for a specific market.
   */
  const getKlinesSymbols = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetKlinesSymbolsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetKlinesSymbolsResponse,
      GetKlinesSymbolsError,
      ThrowOnError
    >({
      ...options,
      url: "/symbols/{market}",
    });
  };

  /**
   * Get Change In Timeframe
   * Retrieve price change percentage between last two completed timestamps for all pairs.
   *
   * Valid markets: spot, futures
   * Valid timeframes: 15m, 30m, 1h, 4h, 1d
   */
  const getChangeInTimeframe = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetChangeInTimeframeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetChangeInTimeframeResponse,
      GetChangeInTimeframeError,
      ThrowOnError
    >({
      ...options,
      url: "/change",
    });
  };

  return {
    getUdfConfig,
    searchSymbols,
    getSymbol,
    getUdfHistory,
    getServerTime,
    getSymbolInfo,
    optionsHandler,
    indexGet,
    getOhlcv,
    getFundingRates,
    getKlinesSymbols,
    getChangeInTimeframe,
  };
}
