// This file is auto-generated by @hey-api/openapi-ts

/**
 * Unique identifier of the API error.
 */
export type ApiErrorIdentifier =
  | "allocation_below_current_exposure"
  | "allocation_below_min_amount"
  | "allocation_limit_exceeded"
  | "black_swan"
  | "bot_already_deleted"
  | "bot_stopping_completed"
  | "bot_stopping_started"
  | "cancelled_open_order"
  | "client_order_id_already_exists"
  | "invalid_content_type"
  | "delete_bot_error"
  | "exchange_http_request_error"
  | "exchange_invalid_parameter"
  | "exchange_invalid_signature"
  | "exchange_invalid_timestamp"
  | "exchange_ip_address_is_not_authorized"
  | "exchange_key_already_exists"
  | "exchange_key_in_use"
  | "exchange_system_under_maintenance"
  | "exchange_rate_limit_exceeded"
  | "insufficient_permissions_spot_and_futures_required"
  | "exchange_service_temporarily_unavailable"
  | "exchange_system_is_busy"
  | "exchange_system_configuration_error"
  | "exchange_internal_system_error"
  | "exchange_user_account_is_frozen"
  | "api_key_expired"
  | "bearer_token_expired"
  | "failed_open_order"
  | "forbidden"
  | "hedge_mode_not_active"
  | "insufficient_balance"
  | "insufficient_margin"
  | "insufficient_scopes"
  | "invalid_api_key"
  | "invalid_basic_auth"
  | "invalid_bearer"
  | "invalid_data"
  | "invalid_data_response"
  | "invalid_exchange_key"
  | "invalid_model_name"
  | "leverage_limit_exceeded"
  | "order_violates_liquidation_price_constraints"
  | "margin_mode_clash"
  | "name_not_unique"
  | "no_credentials"
  | "now_api_down"
  | "object_already_exists"
  | "object_created"
  | "object_deleted"
  | "object_locked"
  | "object_not_found"
  | "object_updated"
  | "order_is_already_filled"
  | "order_is_being_processed"
  | "order_quantity_limit_exceeded"
  | "order_does_not_exist"
  | "order_price_is_invalid"
  | "order_size_too_large"
  | "order_size_too_small"
  | "orphan_open_order"
  | "orphan_close_order"
  | "position_limit_exceeded"
  | "position_does_not_exist"
  | "position_opening_temporarily_suspended"
  | "post_only_order_would_immediately_match"
  | "request_scope_limit_exceeded"
  | "risk_limit_exceeded"
  | "rpc_timeout"
  | "system_settlement_in_process"
  | "strategy_disabled"
  | "strategy_leverage_mismatch"
  | "strategy_not_supporting_exchange"
  | "success"
  | "symbol_does_not_exist"
  | "trading_action_expired"
  | "trading_action_skipped_bot_stopping"
  | "trading_has_been_locked"
  | "trading_is_suspended"
  | "unknown_error_occurred"
  | "requested_resource_not_found";

/**
 * Level of the API error.
 */
export type ApiErrorLevel = "error" | "info" | "success" | "warning";

/**
 * Type of the API error.
 */
export type ApiErrorType =
  | "user error"
  | "exchange error"
  | "server error"
  | "no error";

/**
 * Price change data for a trading pair over a specific timeframe.
 */
export type ChangeInTimeframe = {
  pair: string;
  change: number;
};

/**
 * Exception details returned to the client.
 */
export type ExceptionDetail = {
  /**
   * An additional error message
   */
  message?: string | null;
  /**
   * The unique error code
   */
  code: ApiErrorIdentifier;
  /**
   * The type of error
   */
  type: ApiErrorType;
  /**
   * The level of the error
   */
  level: ApiErrorLevel;
  /**
   * The HTTP status code
   */
  status_code: number;
  /**
   * Additional details about the error
   */
  details?: unknown;
};

/**
 * Individual funding rate entry with timestamp and rate value for futures trading.
 */
export type FundingRate = {
  /**
   * The timestamp of the funding rate
   */
  timestamp: number;
  /**
   * The funding rate
   */
  funding_rate: number;
};

/**
 * Response containing historical funding rates for a specific trading symbol.
 */
export type FundingRateResponse = {
  /**
   * The symbol of the funding rate
   */
  symbol: string;
  /**
   * The funding interval
   */
  funding_interval: string;
  /**
   * The funding rates
   */
  funding_rates: Array<FundingRate>;
};

/**
 * All exchanges we are using, including public (Exchange)
 */
export type InternalExchange =
  | "kucoin"
  | "bingx"
  | "binance"
  | "bybit"
  | "hyperliquid"
  | "bitget";

export type LogLevel = "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL";

/**
 * Market types
 */
export type MarketType = "spot" | "futures";

export type OHLCV = {
  /**
   * Timestamp in seconds
   */
  timestamp: number;
  /**
   * Open prices
   */
  open: number | null;
  /**
   * High prices
   */
  high: number | null;
  /**
   * Low prices
   */
  low: number | null;
  /**
   * Close prices
   */
  close: number | null;
  /**
   * Volume
   */
  volume: number | null;
};

export type Resolution = "15" | "30" | "60" | "240" | "1D";

/**
 * Symbol search result for UDF symbol lookup functionality.
 */
export type SearchSymbol = {
  /**
   * Symbol identifier
   */
  symbol: string;
  /**
   * Human-readable symbol description
   */
  description: string;
  /**
   * Exchange where symbol is traded
   */
  exchange: InternalExchange;
  /**
   * Symbol type classification
   */
  type: string;
};

/**
 * Sort direction options for data ordering (ascending or descending).
 */
export type SortDirection = "asc" | "desc";

/**
 * Group of symbols for batch operations in UDF requests.
 */
export type SymbolGroup = {
  /**
   * List of symbol identifiers in the group
   */
  symbol?: Array<string>;
};

/**
 * Comprehensive symbol information for UDF charting library compatibility.
 */
export type SymbolInfo = {
  /**
   * Symbol name identifier
   */
  name: string;
  /**
   * Exchange where symbol is traded
   */
  "exchange-traded": string;
  /**
   * Exchange where symbol is listed
   */
  "exchange-listed": string;
  /**
   * Timezone for symbol trading hours
   */
  timezone: string;
  /**
   * Minimum price movement
   */
  minmov: number;
  /**
   * Secondary minimum price movement
   */
  minmov2: number;
  /**
   * Point value for price calculations
   */
  pointvalue: number;
  /**
   * Trading session hours
   */
  session: string;
  /**
   * Whether intraday data is available
   */
  has_intraday: boolean;
  /**
   * Whether volume data is unavailable
   */
  has_no_volume: boolean;
  /**
   * Human-readable symbol description
   */
  description: string;
  /**
   * Symbol type classification
   */
  type: string;
  /**
   * List of supported time resolutions
   */
  supported_resolutions: Array<string>;
  /**
   * Price scale factor for decimal places
   */
  pricescale: number;
  /**
   * Symbol ticker identifier
   */
  ticker: string;
};

/**
 * Symbol type definition for UDF data feed configuration.
 */
export type SymbolType = {
  /**
   * Display name of the symbol type
   */
  name: string;
  /**
   * Internal value identifier for the symbol type
   */
  value: string;
};

/**
 * Available timeframes for candlestick and technical analysis data.
 */
export type Timeframe = "15m" | "30m" | "1h" | "4h" | "1d";

/**
 * Universal Data Feed configuration for charting library compatibility.
 */
export type UDFConfig = {
  /**
   * List of supported time resolutions
   */
  supported_resolutions: Array<string>;
  /**
   * Whether grouped symbol requests are supported
   */
  supports_group_request?: boolean;
  /**
   * Whether chart marks are supported
   */
  supports_marks?: boolean;
  /**
   * Whether symbol search is supported
   */
  supports_search?: boolean;
  /**
   * Whether timescale marks are supported
   */
  supports_timescale_marks?: boolean;
  /**
   * Whether server time is supported
   */
  supports_time?: boolean;
  /**
   * List of available exchanges
   */
  exchanges: Array<InternalExchange>;
  /**
   * List of supported symbol types
   */
  symbols_types: Array<SymbolType>;
  /**
   * List of supported currency codes
   */
  currency_codes: Array<string>;
  /**
   * List of supported market types
   */
  supported_markets: Array<string>;
};

export type PingResponse = string;

export type PingError = ExceptionDetail;

export type GetTimeData = {
  query?: {
    type?: "iso" | "unix";
  };
};

export type GetTimeResponse = string;

export type GetTimeError = ExceptionDetail;

export type GetLogLevelResponse = LogLevel;

export type GetLogLevelError = ExceptionDetail;

export type GetUptimeData = {
  query?: {
    type?: "seconds" | "human";
  };
};

export type GetUptimeResponse = string;

export type GetUptimeError = ExceptionDetail;

export type GetMemoryUsageResponse = number;

export type GetMemoryUsageError = ExceptionDetail;

export type GetThreadsResponse = {
  [key: string]: unknown;
};

export type GetThreadsError = ExceptionDetail;

export type GetContainerLimitsResponse = {
  [key: string]: unknown;
};

export type GetContainerLimitsError = ExceptionDetail;

export type GetDependenciesData = {
  query?: {
    /**
     * List of regex patterns to match against package names. If not provided, all installed packages will be returned.
     */
    include?: Array<string>;
  };
};

export type GetDependenciesResponse = {
  [key: string]: string;
};

export type GetDependenciesError = ExceptionDetail;

export type GetMetricsResponse = unknown;

export type GetMetricsError = ExceptionDetail;

export type GetUdfConfigResponse = UDFConfig;

export type GetUdfConfigError = ExceptionDetail;

export type SearchSymbolsData = {
  query: {
    limit?: number;
    query: string;
  };
};

export type SearchSymbolsResponse = Array<SearchSymbol>;

export type SearchSymbolsError = ExceptionDetail;

export type GetSymbolData = {
  query: {
    symbol: string;
  };
};

export type GetSymbolResponse = SymbolInfo;

export type GetSymbolError = ExceptionDetail;

export type GetUdfHistoryData = {
  query: {
    countback?: number | null;
    from: number;
    resolution: Resolution;
    symbol: string;
    to: number;
  };
};

export type GetUdfHistoryResponse = OHLCV;

export type GetUdfHistoryError = ExceptionDetail;

export type GetSymbolInfoData = {
  query: {
    group: string;
  };
};

export type GetSymbolInfoResponse = SymbolGroup;

export type GetSymbolInfoError = ExceptionDetail;

export type OptionsHandlerData = {
  path: {
    path: string;
  };
};

export type OptionsHandlerResponse = unknown;

export type OptionsHandlerError = ExceptionDetail;

export type GetOhlcvData = {
  query: {
    /**
     * End timestamp in milliseconds
     */
    end?: number | null;
    /**
     * Number of candles to return
     */
    limit?: number | null;
    /**
     * Market type
     */
    market: MarketType;
    /**
     * Sort by timestamp in ascending or descending order. Default is descending.
     */
    sort_direction?: SortDirection;
    /**
     * Start timestamp in milliseconds
     */
    start?: number | null;
    /**
     * Trading pair symbol (e.g., BTCUSDT)
     */
    symbol: string;
    /**
     * Timeframe for the candles
     */
    timeframe: Timeframe;
  };
};

export type GetOhlcvResponse = Array<OHLCV>;

export type GetOhlcvError = ExceptionDetail;

export type GetFundingRatesData = {
  query: {
    /**
     * End timestamp in milliseconds
     */
    end?: number | null;
    /**
     * Number of funding rates to return
     */
    limit?: number | null;
    /**
     * Start timestamp in milliseconds
     */
    start?: number | null;
    /**
     * Trading pair symbol (e.g., BTCUSDT)
     */
    symbol: string;
  };
};

export type GetFundingRatesResponse = FundingRateResponse;

export type GetFundingRatesError = ExceptionDetail;

export type GetKlinesSymbolsData = {
  query: {
    /**
     * Market type
     */
    market: MarketType;
  };
};

export type GetKlinesSymbolsResponse = Array<string>;

export type GetKlinesSymbolsError = ExceptionDetail;

export type GetChangeInTimeframeData = {
  query?: {
    /**
     * The market to calculate the change in
     */
    market?: MarketType;
    /**
     * The timeframe to calculate the change in
     */
    timeframe?: Timeframe;
  };
};

export type GetChangeInTimeframeResponse = Array<ChangeInTimeframe>;

export type GetChangeInTimeframeError = ExceptionDetail;
