// This file is auto-generated by @hey-api/openapi-ts

export const AccessScopeSchema = {
  type: 'string',
  enum: ['read:predictions', 'read:dex:signals'],
  title: 'AccessScope',
  description: 'Access scopes',
} as const;

export const AccessThresholdSchema = {
  properties: {
    usd_amount: {
      type: 'number',
      title: 'Usd Amount',
      description: 'Amount of USD',
    },
    scope: {
      $ref: '#/components/schemas/AccessScope',
      description: 'Scope that is granted with this threshold',
    },
  },
  type: 'object',
  required: ['usd_amount', 'scope'],
  title: 'AccessThreshold',
  description: 'Model for an access threshold for lifetime access',
} as const;

export const CouponSchema = {
  properties: {
    created_at: {
      type: 'integer',
      title: 'Created At',
      description: 'Timestamp of creation',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
      description: 'Timestamp of last update',
    },
    id: {
      type: 'string',
      title: 'Id',
      description: 'Unique identifier for the resource',
    },
    code: {
      type: 'string',
      maxLength: 32,
      minLength: 4,
      pattern: '^[A-Z0-9]+$',
      title: 'Code',
      description: 'Coupon code. If not specified, a random code is generated.',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: "A name for the coupon, e.g. 'Black Friday 2025'",
    },
    discount: {
      type: 'number',
      maximum: 1,
      minimum: 0,
      title: 'Discount',
      description: 'Discount percentage as a decimal',
    },
    valid_until: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Valid Until',
      description:
        'Coupon valid until timestamp in seconds. If not specified, the coupon does not expire.',
    },
    valid_from: {
      type: 'integer',
      title: 'Valid From',
      description:
        'Coupon valid from timestamp in seconds. If not specified, the coupon is valid from the current time.',
    },
    usage_limit: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Usage Limit',
      description:
        'Coupon usage limit. If not specified, the coupon can be used unlimited times.',
    },
    products: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Products',
      description:
        'Products that the coupon can be used on. If not specified, the coupon can be used on all products.',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      description: 'Coupon is active',
      default: true,
    },
    usage_count: {
      type: 'integer',
      title: 'Usage Count',
      description: 'Coupon usage count',
    },
    payment_required: {
      type: 'boolean',
      title: 'Payment Required',
      description:
        'Whether the coupon requires a payment. If the discount is not 100%, the coupon requires a payment.',
      readOnly: true,
    },
    is_valid: {
      type: 'boolean',
      title: 'Is Valid',
      description:
        'Coupon is valid if it is active, not expired, and has not reached the usage limit',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'created_at',
    'updated_at',
    'id',
    'name',
    'discount',
    'usage_count',
    'payment_required',
    'is_valid',
  ],
  title: 'Coupon',
  description: 'Model for reading a coupon',
} as const;

export const CouponCreateSchema = {
  properties: {
    code: {
      type: 'string',
      maxLength: 32,
      minLength: 4,
      pattern: '^[A-Z0-9]+$',
      title: 'Code',
      description: 'Coupon code. If not specified, a random code is generated.',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: "A name for the coupon, e.g. 'Black Friday 2025'",
    },
    discount: {
      type: 'number',
      maximum: 1,
      minimum: 0,
      title: 'Discount',
      description: 'Discount percentage as a decimal',
    },
    valid_until: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Valid Until',
      description:
        'Coupon valid until timestamp in seconds. If not specified, the coupon does not expire.',
    },
    valid_from: {
      type: 'integer',
      title: 'Valid From',
      description:
        'Coupon valid from timestamp in seconds. If not specified, the coupon is valid from the current time.',
    },
    usage_limit: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Usage Limit',
      description:
        'Coupon usage limit. If not specified, the coupon can be used unlimited times.',
    },
    products: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Products',
      description:
        'Products that the coupon can be used on. If not specified, the coupon can be used on all products.',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      description: 'Coupon is active',
      default: true,
    },
  },
  type: 'object',
  required: ['name', 'discount'],
  title: 'CouponCreate',
  description: 'Model for creating a coupon',
} as const;

export const CouponUpdateSchema = {
  properties: {
    valid_until: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Valid Until',
      description:
        'Coupon valid until timestamp in seconds. If not specified, the valid until is not changed.',
    },
    usage_limit: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Usage Limit',
      description:
        'Coupon usage limit. If not specified, the usage limit is not changed.',
    },
    products: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Products',
      description:
        'Products that the coupon can be used on. If empty, the products are not changed.',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
      description: 'Coupon name. If not specified, the name is not changed.',
    },
  },
  type: 'object',
  title: 'CouponUpdate',
  description: 'Model for updating a coupon',
} as const;

export const ErrorResponseSchema = {
  properties: {
    detail: {
      type: 'string',
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'ErrorResponse',
  description: 'Error response schema.',
} as const;

export const InvoiceSchema = {
  properties: {
    created_at: {
      type: 'integer',
      title: 'Created At',
      description: 'Timestamp of creation',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
      description: 'Timestamp of last update',
    },
    id: {
      type: 'string',
      title: 'Id',
      description: 'Unique identifier for the resource',
    },
    product_id: {
      type: 'string',
      title: 'Product Id',
      description: 'The ID of the product',
    },
    coupon_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Coupon Id',
      description: 'The ID of the coupon',
    },
    provider: {
      type: 'string',
      enum: ['now', 'staking', 'stripe'],
      title: 'Provider',
      description: 'The provider the invoice is created with',
    },
    address: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Address',
      description: 'The address of the user. Only used for staking invoices.',
    },
    oob: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Oob',
      description:
        'The oob code for the invoice. Only used for signup invoices.',
    },
    user_id: {
      type: 'string',
      title: 'User Id',
      description: 'The ID of the user',
    },
    usd_amount: {
      type: 'number',
      title: 'Usd Amount',
      description: 'The amount of the invoice in USD',
    },
    url: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Url',
      description: 'Invoice URL. If None, no external payment is required.',
    },
  },
  type: 'object',
  required: [
    'created_at',
    'updated_at',
    'id',
    'product_id',
    'provider',
    'user_id',
    'usd_amount',
  ],
  title: 'Invoice',
  description: 'Model for reading an invoice',
} as const;

export const InvoiceCreateSchema = {
  properties: {
    product_id: {
      type: 'string',
      title: 'Product Id',
      description: 'The ID of the product',
    },
    coupon_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Coupon Id',
      description: 'The ID of the coupon',
    },
    provider: {
      type: 'string',
      enum: ['now', 'staking', 'stripe'],
      title: 'Provider',
      description: 'The provider the invoice is created with',
    },
    address: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Address',
      description: 'The address of the user. Only used for staking invoices.',
    },
    oob: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Oob',
      description:
        'The oob code for the invoice. Only used for signup invoices.',
    },
    user_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'User Id',
      description:
        'The ID of the user. Overrides the authenticated user if provided and the user is an admin.',
    },
  },
  type: 'object',
  required: ['product_id', 'provider'],
  title: 'InvoiceCreate',
  description: 'Model for creating an invoice',
} as const;

export const PaginatedResponse_Coupon_Schema = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/Coupon',
      },
      type: 'array',
      title: 'Data',
    },
    total: {
      type: 'integer',
      title: 'Total',
      description: 'The total number of items',
    },
    page: {
      type: 'integer',
      title: 'Page',
      description: 'The current page number',
    },
    page_size: {
      type: 'integer',
      title: 'Page Size',
      description: 'The number of items per page',
    },
    prev: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Prev',
      description: 'The previous page number',
    },
    next: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next',
      description: 'The next page number',
    },
    last: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Last',
      description: 'The last page number',
    },
  },
  type: 'object',
  required: ['data', 'total', 'page', 'page_size'],
  title: 'PaginatedResponse[Coupon]',
} as const;

export const PaginatedResponse_Payment_Schema = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/Payment',
      },
      type: 'array',
      title: 'Data',
    },
    total: {
      type: 'integer',
      title: 'Total',
      description: 'The total number of items',
    },
    page: {
      type: 'integer',
      title: 'Page',
      description: 'The current page number',
    },
    page_size: {
      type: 'integer',
      title: 'Page Size',
      description: 'The number of items per page',
    },
    prev: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Prev',
      description: 'The previous page number',
    },
    next: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next',
      description: 'The next page number',
    },
    last: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Last',
      description: 'The last page number',
    },
  },
  type: 'object',
  required: ['data', 'total', 'page', 'page_size'],
  title: 'PaginatedResponse[Payment]',
} as const;

export const PaymentSchema = {
  properties: {
    id: {
      type: 'string',
      title: 'Id',
      description: 'Payment ID',
    },
    product_id: {
      type: 'string',
      title: 'Product Id',
      description: 'Product purchased',
    },
    coupon_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Coupon Id',
      description: 'Coupon used for the payment',
    },
    user_id: {
      type: 'string',
      title: 'User Id',
      description: 'User ID the payment is for',
    },
    invoice_id: {
      type: 'string',
      title: 'Invoice Id',
      description: 'Invoice ID',
    },
    amount: {
      type: 'number',
      title: 'Amount',
      description: 'Payment amount',
    },
    currency: {
      type: 'string',
      title: 'Currency',
      description: 'Payment currency',
    },
    status: {
      type: 'string',
      enum: [
        'waiting',
        'processing',
        'paid',
        'partially_paid',
        'refunded',
        'failed',
        'cancelled',
      ],
      title: 'Status',
      description: 'Payment status',
    },
    provider: {
      type: 'string',
      enum: ['now', 'staking', 'stripe'],
      title: 'Provider',
      description: 'Payment provider',
    },
    market: {
      type: 'string',
      enum: ['crypto', 'fiat'],
      title: 'Market',
      description: 'Payment market',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
      description: 'Payment updated at timestamp in seconds',
    },
    created_at: {
      type: 'integer',
      title: 'Created At',
      description: 'Payment created at timestamp in seconds',
    },
    details: {
      additionalProperties: true,
      type: 'object',
      title: 'Details',
      description: 'Payment details specific to the provider',
      default: {},
    },
  },
  type: 'object',
  required: [
    'id',
    'product_id',
    'user_id',
    'invoice_id',
    'amount',
    'currency',
    'status',
    'provider',
    'market',
    'updated_at',
    'created_at',
  ],
  title: 'Payment',
  description: 'Combined payment model across all services',
} as const;

export const ProductSchema = {
  properties: {
    created_at: {
      type: 'integer',
      title: 'Created At',
      description: 'Timestamp of creation',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
      description: 'Timestamp of last update',
    },
    id: {
      type: 'string',
      title: 'Id',
      description: 'Unique identifier for the resource',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Product name',
    },
    price: {
      type: 'number',
      title: 'Price',
      description: 'Product price',
    },
    scopes: {
      items: {
        $ref: '#/components/schemas/AccessScope',
      },
      type: 'array',
      title: 'Scopes',
      description: 'Scopes that product provides',
    },
    duration: {
      type: 'integer',
      title: 'Duration',
      description: 'Product duration in days. 0 means forever.',
    },
    description: {
      type: 'string',
      title: 'Description',
      description: 'Product description',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      description: 'Product is active',
    },
    images: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Images',
      description: 'Product images as hosted URLs',
    },
    original_price: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Original Price',
      description:
        'Original product price. This is the price before the coupon is applied. None if no coupon is applied.',
    },
  },
  type: 'object',
  required: [
    'created_at',
    'updated_at',
    'id',
    'name',
    'price',
    'scopes',
    'duration',
    'description',
    'is_active',
  ],
  title: 'Product',
  description: 'Model for reading a product',
} as const;

export const ProductCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
      description: 'Product name',
    },
    price: {
      type: 'number',
      title: 'Price',
      description: 'Product price',
    },
    scopes: {
      items: {
        $ref: '#/components/schemas/AccessScope',
      },
      type: 'array',
      title: 'Scopes',
      description: 'Scopes that product provides',
    },
    duration: {
      type: 'integer',
      title: 'Duration',
      description: 'Product duration in days. 0 means forever.',
    },
    description: {
      type: 'string',
      title: 'Description',
      description: 'Product description',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      description: 'Product is active',
    },
    images: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Images',
      description: 'Product images as hosted URLs',
    },
  },
  type: 'object',
  required: ['name', 'price', 'scopes', 'duration', 'description', 'is_active'],
  title: 'ProductCreate',
  description: 'Model for creating a product',
} as const;

export const ProductUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
      description: 'Product name',
    },
    price: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Price',
      description: 'Product price',
    },
    scopes: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/AccessScope',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Scopes',
      description: 'Scopes that product provides',
    },
    duration: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Duration',
      description: 'Product duration in days. 0 means forever.',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
      description: 'Product description',
    },
    is_active: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Active',
      description: 'Product is active',
    },
    images: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Images',
      description: 'Product images as hosted URLs',
    },
  },
  type: 'object',
  title: 'ProductUpdate',
  description: 'Model for updating a product',
} as const;

export const ScopeInfoSchema = {
  properties: {
    scope: {
      $ref: '#/components/schemas/AccessScope',
      description: 'The scope affected',
    },
    expires_at: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Expires At',
      description:
        'Expiry timestamp in seconds, or None if not applicable (e.g. balance-based)',
    },
    has_expired: {
      type: 'boolean',
      title: 'Has Expired',
      description: 'Whether the scope has expired or not',
    },
    reason: {
      type: 'string',
      enum: ['allowlist', 'subscription', 'balance'],
      title: 'Reason',
      description: 'Reason for access (allowlist, subscription, balance, etc.)',
    },
  },
  type: 'object',
  required: ['scope', 'has_expired', 'reason'],
  title: 'ScopeInfo',
  description:
    'Model for detailed scope access info for a user, for each access method.',
} as const;

export const ScopesInfoSchema = {
  properties: {
    scopes: {
      items: {
        $ref: '#/components/schemas/AccessScope',
      },
      type: 'array',
      title: 'Scopes',
      description: 'List of scopes',
    },
    info: {
      items: {
        $ref: '#/components/schemas/ScopeInfo',
      },
      type: 'array',
      title: 'Info',
      description:
        'List of scope access info. Contains one entry for each scope, for each access method (allowlist, subscription, balance) if the user has (or had in the last 7 days) access to the scope.',
    },
  },
  type: 'object',
  required: ['scopes', 'info'],
  title: 'ScopesInfo',
  description:
    'Model containing all scopes the user has access to, and detailed info for each access method (allowlist, subscription, balance).',
} as const;

export const StakeDetailsSchema = {
  properties: {
    pool_id: {
      type: 'integer',
      enum: [1, 2, 3, 4],
      title: 'Pool Id',
      description: 'The ID of the staking pool.',
    },
    reward_base: {
      type: 'string',
      title: 'Reward Base',
      description:
        'The base reward amount accumulated so far, in wei (1 ETH = 1e18 wei).',
    },
    current_stake: {
      type: 'string',
      title: 'Current Stake',
      description: 'The amount currently staked by the user, in wei.',
    },
    start_time: {
      type: 'string',
      title: 'Start Time',
      description:
        'The Unix timestamp (in seconds) when the stake was created.',
    },
    lock_period: {
      type: 'string',
      title: 'Lock Period',
      description:
        'The duration the stake is locked for, in seconds (e.g., 5184000 = 60 days).',
    },
    apy: {
      type: 'string',
      title: 'Apy',
      description:
        'The annual percentage yield (APY), represented in wei format (e.g., 1e18 = 100%).',
    },
    pending_reward: {
      type: 'string',
      title: 'Pending Reward',
      description: 'The reward currently available to claim, in wei.',
    },
    pending_withdrawal: {
      type: 'string',
      title: 'Pending Withdrawal',
      description: 'The amount currently pending to withdraw, in wei.',
    },
  },
  type: 'object',
  required: [
    'pool_id',
    'reward_base',
    'current_stake',
    'start_time',
    'lock_period',
    'apy',
    'pending_reward',
    'pending_withdrawal',
  ],
  title: 'StakeDetails',
  description: 'Details of a staking pool',
} as const;

export const SubscriptionSchema = {
  properties: {
    created_at: {
      type: 'integer',
      title: 'Created At',
      description: 'Timestamp of creation',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
      description: 'Timestamp of last update',
    },
    id: {
      type: 'string',
      title: 'Id',
      description: 'Unique identifier for the resource',
    },
    user_id: {
      type: 'string',
      title: 'User Id',
      description: 'User ID',
    },
    product_id: {
      type: 'string',
      title: 'Product Id',
      description: 'Product ID',
    },
    access_from: {
      type: 'integer',
      title: 'Access From',
      description: 'Access from timestamp in seconds',
    },
    access_until: {
      type: 'integer',
      title: 'Access Until',
      description: 'Access until timestamp in seconds.',
    },
  },
  type: 'object',
  required: [
    'created_at',
    'updated_at',
    'id',
    'user_id',
    'product_id',
    'access_from',
    'access_until',
  ],
  title: 'Subscription',
  description: 'Model for reading a product subscription',
} as const;

export const TotalBalanceSchema = {
  properties: {
    staked: {
      type: 'string',
      title: 'Staked',
      description: 'Total staked balance in wei of AIC',
    },
    balance: {
      type: 'string',
      title: 'Balance',
      description: 'Total balance in wei of AIC',
    },
    reward_base: {
      type: 'string',
      title: 'Reward Base',
      description: 'Total reward base in wei of AIC',
    },
    pending_reward: {
      type: 'string',
      title: 'Pending Reward',
      description: 'Total pending reward in wei of AIC',
    },
    pending_withdrawal: {
      type: 'string',
      title: 'Pending Withdrawal',
      description: 'Total pending withdrawal in wei of AIC',
    },
    average_apy: {
      type: 'string',
      title: 'Average Apy',
      description:
        'The average APY on the staked balance calculated from the pool balances and their APYs. 1e18 = 100%',
    },
  },
  type: 'object',
  required: [
    'staked',
    'balance',
    'reward_base',
    'pending_reward',
    'pending_withdrawal',
    'average_apy',
  ],
  title: 'TotalBalance',
  description: "Model for a user's total balance",
} as const;

export const TxReceiptSchema = {
  properties: {
    block_hash: {
      type: 'string',
      title: 'Block Hash',
      description: 'Hash of the block containing the transaction',
    },
    block_number: {
      type: 'integer',
      title: 'Block Number',
      description: 'Block number where this transaction was included',
    },
    contract_address: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Contract Address',
      description:
        'Address of the contract created, if the transaction was a contract creation, otherwise None',
    },
    cumulative_gas_used: {
      type: 'integer',
      title: 'Cumulative Gas Used',
      description:
        'Total gas used when this transaction was executed in the block',
    },
    effective_gas_price: {
      type: 'integer',
      title: 'Effective Gas Price',
      description: 'Effective gas price paid for this transaction',
    },
    gas_used: {
      type: 'integer',
      title: 'Gas Used',
      description: 'Gas used by this specific transaction alone',
    },
    sender_address: {
      type: 'string',
      title: 'Sender Address',
      description: 'Address sending the transaction',
    },
    logs: {
      items: {},
      type: 'array',
      title: 'Logs',
      description: 'List of log objects generated by this transaction',
    },
    logs_bloom: {
      type: 'string',
      title: 'Logs Bloom',
      description:
        'Bloom filter for light clients to quickly determine relevant logs',
    },
    root: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Root',
      description:
        'Post-transaction state root (pre-Byzantium), otherwise None',
    },
    status: {
      type: 'integer',
      title: 'Status',
      description: '1 is success, 0 is failure',
    },
    recipient_address: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Recipient Address',
      description:
        'Address receiving the transaction, or None if contract creation',
    },
    transaction_hash: {
      type: 'string',
      title: 'Transaction Hash',
      description: 'Hash of the transaction',
    },
    transaction_index: {
      type: 'integer',
      title: 'Transaction Index',
      description: 'Index position of the transaction in the block',
    },
    type: {
      type: 'integer',
      title: 'Type',
      description: 'Transaction type indicator',
    },
  },
  type: 'object',
  required: [
    'block_hash',
    'block_number',
    'cumulative_gas_used',
    'effective_gas_price',
    'gas_used',
    'sender_address',
    'logs',
    'logs_bloom',
    'status',
    'transaction_hash',
    'transaction_index',
    'type',
  ],
  title: 'TxReceipt',
  description: 'Model defining a transaction receipt.',
} as const;

export const UnstakeTokensRequestSchema = {
  properties: {
    address: {
      type: 'string',
      title: 'Address',
      description: "User's wallet address",
    },
    pool_id: {
      type: 'integer',
      enum: [1, 2, 3],
      title: 'Pool Id',
      description: 'Pool ID to unstake from',
    },
    amount_wei: {
      type: 'integer',
      exclusiveMinimum: 0,
      title: 'Amount Wei',
      description: 'Amount to unstake in wei',
    },
  },
  type: 'object',
  required: ['address', 'pool_id', 'amount_wei'],
  title: 'UnstakeTokensRequest',
  description: 'Model for unstaking tokens',
} as const;

export const UserBalanceSchema = {
  properties: {
    wallets: {
      items: {
        $ref: '#/components/schemas/WalletBalance',
      },
      type: 'array',
      title: 'Wallets',
      description: 'List of wallet balances',
    },
    updated_at: {
      type: 'integer',
      title: 'Updated At',
      description: 'Timestamp of last update',
    },
    total: {
      $ref: '#/components/schemas/TotalBalance',
      description:
        'Combined balance information computed from the wallet balances',
      readOnly: true,
    },
    pools: {
      items: {
        $ref: '#/components/schemas/StakeDetails',
      },
      type: 'array',
      title: 'Pools',
      description: 'List of pool balances computed from the wallet balances',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['wallets', 'updated_at', 'total', 'pools'],
  title: 'UserBalance',
  description: "Model for a user's balance",
} as const;

export const WalletBalanceSchema = {
  properties: {
    address: {
      type: 'string',
      title: 'Address',
      description: 'Wallet address',
    },
    balance: {
      type: 'string',
      title: 'Balance',
      description: 'Balance in wei of AIC',
    },
    staked: {
      items: {
        $ref: '#/components/schemas/StakeDetails',
      },
      type: 'array',
      title: 'Staked',
      description: 'List of stake details for each pool',
    },
  },
  type: 'object',
  required: ['address', 'balance', 'staked'],
  title: 'WalletBalance',
  description: "Model for a user's balance for a specific wallet",
} as const;
