// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const NowAPIStatusResSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
      description: "API status message",
    },
  },
  type: "object",
  required: ["message"],
  title: "NowAPIStatusRes",
  description: "Response for the API status.",
} as const;

export const NowCreateInvoiceReqSchema = {
  properties: {
    price_amount: {
      type: "number",
      title: "Price Amount",
      description: "Amount to pay in fiat currency",
    },
    price_currency: {
      type: "string",
      title: "Price Currency",
      description: "Fiat currency for the price (usd, eur, etc)",
    },
    pay_currency: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Pay Currency",
      description:
        "Specific cryptocurrency or enabled fiat currency. If not specified, can be chosen on invoice_url",
    },
    ipn_callback_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Ipn Callback Url",
      description: "URL to receive callbacks, must contain http/https",
    },
    order_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Order Id",
      description: "Internal store order ID",
    },
    order_description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Order Description",
      description: "Internal store order description",
    },
    success_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Success Url",
      description: "URL for redirect after successful payment",
    },
    cancel_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Cancel Url",
      description: "URL for redirect after failed payment",
    },
    partially_paid_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Partially Paid Url",
      description: "URL for redirect after partial payment",
    },
    is_fixed_rate: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Fixed Rate",
      description: "Enable fixed-rate exchanges (rate frozen for 20 minutes)",
    },
    is_fee_paid_by_user: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Fee Paid By User",
      description: "Enable fixed-rate exchanges with all fees paid by users",
    },
  },
  type: "object",
  required: ["price_amount", "price_currency"],
  title: "NowCreateInvoiceReq",
  description: `Request model for creating a payment invoice.

Creates a payment link where the customer can complete the payment.
With this method, the customer is required to follow the generated url to complete the payment.

https://documenter.getpostman.com/view/7907941/2s93JusNJt#f5e4e645-dce2-4b06-b2ca-2a29aaa5e845`,
} as const;

export const NowCreateInvoiceResSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Invoice ID",
    },
    token_id: {
      type: "string",
      title: "Token Id",
      description: "Internal identifier",
    },
    order_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Order Id",
      description: "Order ID specified in request",
    },
    order_description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Order Description",
      description: "Order description specified in request",
    },
    price_amount: {
      type: "string",
      title: "Price Amount",
      description: "Base price in fiat",
    },
    price_currency: {
      type: "string",
      title: "Price Currency",
      description: "Ticker of base fiat currency",
    },
    pay_currency: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Pay Currency",
      description: "Currency customer will pay with",
    },
    ipn_callback_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Ipn Callback Url",
      description: "Link to IPN notifications endpoint",
    },
    invoice_url: {
      type: "string",
      title: "Invoice Url",
      description: "Link to the payment page",
    },
    success_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Success Url",
      description: "Redirect URL for successful payment",
    },
    cancel_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Cancel Url",
      description: "Redirect URL for failed payment",
    },
    partially_paid_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Partially Paid Url",
      description: "Redirect URL for partial payment",
    },
    payout_currency: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Payout Currency",
      description: "Ticker of payout currency",
    },
    created_at: {
      type: "string",
      title: "Created At",
      description: "Time of invoice creation",
    },
    updated_at: {
      type: "string",
      title: "Updated At",
      description: "Time of latest invoice update",
    },
    is_fixed_rate: {
      type: "boolean",
      title: "Is Fixed Rate",
      description: "Fixed Rate option status",
    },
    is_fee_paid_by_user: {
      type: "boolean",
      title: "Is Fee Paid By User",
      description: "Fee Paid By User option status",
    },
  },
  type: "object",
  required: [
    "id",
    "token_id",
    "price_amount",
    "price_currency",
    "invoice_url",
    "created_at",
    "updated_at",
    "is_fixed_rate",
    "is_fee_paid_by_user",
  ],
  title: "NowCreateInvoiceRes",
  description: `Response model for created invoice.
https://documenter.getpostman.com/view/7907941/2s93JusNJt#f5e4e645-dce2-4b06-b2ca-2a29aaa5e845`,
} as const;

export const PaymentSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Payment ID",
    },
    product_id: {
      type: "string",
      title: "Product Id",
      description: "Product ID",
    },
    timestamp: {
      type: "integer",
      title: "Timestamp",
      description: "Payment timestamp in seconds",
    },
    amount: {
      type: "number",
      title: "Amount",
      description: "Payment amount",
    },
    currency: {
      type: "string",
      title: "Currency",
      description: "Payment currency",
    },
    status: {
      $ref: "#/components/schemas/PaymentStatus",
    },
    service: {
      $ref: "#/components/schemas/Services",
      description: "Payment service",
    },
    market: {
      type: "string",
      title: "Market",
      description: "Payment market",
    },
  },
  type: "object",
  required: [
    "id",
    "product_id",
    "timestamp",
    "amount",
    "currency",
    "status",
    "service",
    "market",
  ],
  title: "Payment",
  description: "Combined payment model across all services",
} as const;

export const PaymentStatusSchema = {
  type: "string",
  enum: [
    "waiting",
    "processing",
    "paid",
    "partially_paid",
    "refunded",
    "failed",
    "cancelled",
  ],
  title: "PaymentStatus",
  description: "Payment status",
} as const;

export const ProductCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Product name",
    },
    price: {
      type: "number",
      title: "Price",
      description: "Product price",
    },
    scopes: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/Scope",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Scopes",
      description: "Scopes that product provides",
    },
    duration: {
      type: "integer",
      title: "Duration",
      description: "Product duration in days. 0 means unlimited.",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Product description",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      description: "Product is active",
    },
  },
  type: "object",
  required: ["name", "price", "duration", "description", "is_active"],
  title: "ProductCreate",
  description: "Model for creating a product",
} as const;

export const ProductReadSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Product name",
    },
    price: {
      type: "number",
      title: "Price",
      description: "Product price",
    },
    scopes: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/Scope",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Scopes",
      description: "Scopes that product provides",
    },
    duration: {
      type: "integer",
      title: "Duration",
      description: "Product duration in days. 0 means unlimited.",
    },
    description: {
      type: "string",
      title: "Description",
      description: "Product description",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      description: "Product is active",
    },
    id: {
      type: "string",
      title: "Id",
      description: "UID of the product",
    },
  },
  type: "object",
  required: ["name", "price", "duration", "description", "is_active", "id"],
  title: "ProductRead",
  description: "Model for reading a product",
} as const;

export const ProductSubReadSchema = {
  properties: {
    user_id: {
      type: "string",
      title: "User Id",
      description: "User ID",
    },
    product_id: {
      type: "string",
      title: "Product Id",
      description: "Product ID",
    },
    access_from: {
      type: "integer",
      title: "Access From",
      description: "Access from timestamp in milliseconds",
    },
    access_until: {
      type: "integer",
      title: "Access Until",
      description: "Access until timestamp in milliseconds. 0 means unlimited.",
    },
    id: {
      type: "string",
      title: "Id",
      description: "UID of the product subscription",
    },
  },
  type: "object",
  required: ["user_id", "product_id", "access_from", "access_until", "id"],
  title: "ProductSubRead",
  description: "Model for reading a product subscription",
} as const;

export const ProductUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      description: "Product name",
    },
    price: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Price",
      description: "Product price",
    },
    scopes: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/Scope",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Scopes",
      description: "Scopes that product provides",
    },
    duration: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Duration",
      description: "Product duration in days. 0 means unlimited.",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Product description",
    },
    is_active: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Active",
      description: "Product is active",
    },
  },
  type: "object",
  title: "ProductUpdate",
  description: "Model for updating a product",
} as const;

export const ScopeSchema = {
  type: "string",
  enum: [
    "read:predictions",
    "read:hive:model",
    "read:hive:data",
    "write:hive:model",
    "read:trade:bots",
    "write:trade:bots",
    "read:trade:exchangekeys",
    "write:trade:exchangekeys",
    "read:trade:orders",
    "read:trade:actions",
    "write:trade:actions",
    "read:trade:exchanges",
    "read:trade:futures",
    "write:trade:futures",
    "read:trade:notifications",
    "write:trade:notifications",
    "read:trade:strategies",
    "write:trade:strategies",
    "read:pay:payments",
    "read:pay:products",
    "write:pay:products",
    "read:pay:now",
    "write:pay:now",
    "read:metrics:marketcap",
    "read:metrics:indicators",
    "read:metrics:exchanges",
    "read:metrics:tokens",
    "read:metrics:markets",
  ],
  title: "Scope",
  description: "The permission scopes for the API.",
} as const;

export const ServicesSchema = {
  type: "string",
  enum: ["now"],
  title: "Services",
  description: "Available payment services",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
