import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  PingError,
  PingResponse,
  GetTimeData,
  GetTimeError,
  GetTimeResponse,
  GetConfigError,
  GetConfigResponse,
  GetNowApiStatusError,
  GetNowApiStatusResponse,
  CreateNowInvoiceData,
  CreateNowInvoiceError,
  CreateNowInvoiceResponse,
  HandleNowWebhookError,
  HandleNowWebhookResponse,
  GetProductsData,
  GetProductsError,
  GetProductsResponse,
  CreateProductData,
  CreateProductError,
  CreateProductResponse,
  UpdateProductData,
  UpdateProductError,
  UpdateProductResponse,
  GetLatestPaymentFromInvoiceData,
  GetLatestPaymentFromInvoiceError,
  GetLatestPaymentFromInvoiceResponse,
  GetPaymentHistoryData,
  GetPaymentHistoryError,
  GetPaymentHistoryResponse,
  GetSubscriptionsData,
  GetSubscriptionsError,
  GetSubscriptionsResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Time
   * Returns the current time in the specified format.
   */
  const getTime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetTimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTimeResponse,
      GetTimeError,
      ThrowOnError
    >({
      ...options,
      url: "/time",
    });
  };

  /**
   * Config
   * Returns the version of the crypticorn library and the environment.
   */
  const getConfig = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetConfigResponse,
      GetConfigError,
      ThrowOnError
    >({
      ...options,
      url: "/config",
    });
  };

  /**
   * Get Status
   * Get the status of the NOWPayments API
   */
  const getNowApiStatus = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetNowApiStatusResponse,
      GetNowApiStatusError,
      ThrowOnError
    >({
      ...options,
      url: "/now/status",
    });
  };

  /**
   * Create Invoice
   * Create a payment invoice with a payment link for customer completion
   */
  const createNowInvoice = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateNowInvoiceData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateNowInvoiceResponse,
      CreateNowInvoiceError,
      ThrowOnError
    >({
      ...options,
      url: "/now/invoice",
    });
  };

  /**
   * Handle Webhook
   * Handle NOWPayments webhook notifications (IPN).
   * Validates the signature, updates the payment status and creates a product subscription if the payment is successful.
   */
  const handleNowWebhook = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      HandleNowWebhookResponse,
      HandleNowWebhookError,
      ThrowOnError
    >({
      ...options,
      url: "/now/webhook",
    });
  };

  /**
   * Get Products
   * Get all software products from Crypticorn
   */
  const getProducts = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetProductsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetProductsResponse,
      GetProductsError,
      ThrowOnError
    >({
      ...options,
      url: "/products",
    });
  };

  /**
   * Create Product
   * Create a new product
   */
  const createProduct = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateProductData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateProductResponse,
      CreateProductError,
      ThrowOnError
    >({
      ...options,
      url: "/products",
    });
  };

  /**
   * Update Product
   * Update an existing product
   */
  const updateProduct = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateProductData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateProductResponse,
      UpdateProductError,
      ThrowOnError
    >({
      ...options,
      url: "/products/{id}",
    });
  };

  /**
   * Get Latest Payment From Invoice
   * Get the latest payment by a user from an invoice
   */
  const getLatestPaymentFromInvoice = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetLatestPaymentFromInvoiceData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetLatestPaymentFromInvoiceResponse,
      GetLatestPaymentFromInvoiceError,
      ThrowOnError
    >({
      ...options,
      url: "/payments",
    });
  };

  /**
   * Get Payments
   * Get the combined payment history for a user across all payment services.
   */
  const getPaymentHistory = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetPaymentHistoryData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetPaymentHistoryResponse,
      GetPaymentHistoryError,
      ThrowOnError
    >({
      ...options,
      url: "/payments/history",
    });
  };

  /**
   * Get Subscriptions
   * Get all subscriptions for a user. Subscriptions are the products a user has subscribed to. Returns both active and inactive subscriptions.
   */
  const getSubscriptions = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetSubscriptionsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetSubscriptionsResponse,
      GetSubscriptionsError,
      ThrowOnError
    >({
      ...options,
      url: "/payments/subscriptions",
    });
  };

  return {
    ping,
    getTime,
    getConfig,
    getNowApiStatus,
    createNowInvoice,
    handleNowWebhook,
    getProducts,
    createProduct,
    updateProduct,
    getLatestPaymentFromInvoice,
    getPaymentHistory,
    getSubscriptions,
  };
}
