// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/v1/pay` | (string & {});
};

/**
 * AccessScope
 *
 * Access scopes
 */
export type AccessScope = 'read:predictions' | 'read:dex:signals';

/**
 * AccessThreshold
 *
 * Model for an access threshold for lifetime access
 */
export type AccessThreshold = {
  /**
   * Usd Amount
   *
   * Amount of USD
   */
  usd_amount: number;
  /**
   * Scope that is granted with this threshold
   */
  scope: AccessScope;
};

/**
 * Coupon
 *
 * Model for reading a coupon
 */
export type Coupon = {
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Id
   *
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Code
   *
   * Coupon code. If not specified, a random code is generated.
   */
  code?: string;
  /**
   * Name
   *
   * A name for the coupon, e.g. 'Black Friday 2025'
   */
  name: string;
  /**
   * Discount
   *
   * Discount percentage as a decimal
   */
  discount: number;
  /**
   * Valid Until
   *
   * Coupon valid until timestamp in seconds. If not specified, the coupon does not expire.
   */
  valid_until?: number | null;
  /**
   * Valid From
   *
   * Coupon valid from timestamp in seconds. If not specified, the coupon is valid from the current time.
   */
  valid_from?: number;
  /**
   * Usage Limit
   *
   * Coupon usage limit. If not specified, the coupon can be used unlimited times.
   */
  usage_limit?: number | null;
  /**
   * Products
   *
   * Products that the coupon can be used on. If not specified, the coupon can be used on all products.
   */
  products?: Array<string> | null;
  /**
   * Is Active
   *
   * Coupon is active
   */
  is_active?: boolean;
  /**
   * Usage Count
   *
   * Coupon usage count
   */
  usage_count: number;
  /**
   * Payment Required
   *
   * Whether the coupon requires a payment. If the discount is not 100%, the coupon requires a payment.
   */
  readonly payment_required: boolean;
  /**
   * Is Valid
   *
   * Coupon is valid if it is active, not expired, and has not reached the usage limit
   */
  readonly is_valid: boolean;
};

/**
 * CouponCreate
 *
 * Model for creating a coupon
 */
export type CouponCreate = {
  /**
   * Code
   *
   * Coupon code. If not specified, a random code is generated.
   */
  code?: string;
  /**
   * Name
   *
   * A name for the coupon, e.g. 'Black Friday 2025'
   */
  name: string;
  /**
   * Discount
   *
   * Discount percentage as a decimal
   */
  discount: number;
  /**
   * Valid Until
   *
   * Coupon valid until timestamp in seconds. If not specified, the coupon does not expire.
   */
  valid_until?: number | null;
  /**
   * Valid From
   *
   * Coupon valid from timestamp in seconds. If not specified, the coupon is valid from the current time.
   */
  valid_from?: number;
  /**
   * Usage Limit
   *
   * Coupon usage limit. If not specified, the coupon can be used unlimited times.
   */
  usage_limit?: number | null;
  /**
   * Products
   *
   * Products that the coupon can be used on. If not specified, the coupon can be used on all products.
   */
  products?: Array<string> | null;
  /**
   * Is Active
   *
   * Coupon is active
   */
  is_active?: boolean;
};

/**
 * CouponUpdate
 *
 * Model for updating a coupon
 */
export type CouponUpdate = {
  /**
   * Valid Until
   *
   * Coupon valid until timestamp in seconds. If not specified, the valid until is not changed.
   */
  valid_until?: number | null;
  /**
   * Usage Limit
   *
   * Coupon usage limit. If not specified, the usage limit is not changed.
   */
  usage_limit?: number | null;
  /**
   * Products
   *
   * Products that the coupon can be used on. If empty, the products are not changed.
   */
  products?: Array<string> | null;
  /**
   * Name
   *
   * Coupon name. If not specified, the name is not changed.
   */
  name?: string | null;
};

/**
 * ErrorResponse
 *
 * Error response schema.
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * Invoice
 *
 * Model for reading an invoice
 */
export type Invoice = {
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Id
   *
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Product Id
   *
   * The ID of the product
   */
  product_id: string;
  /**
   * Coupon Id
   *
   * The ID of the coupon
   */
  coupon_id?: string | null;
  /**
   * Provider
   *
   * The provider the invoice is created with
   */
  provider: 'now' | 'staking' | 'stripe';
  /**
   * Address
   *
   * The address of the user. Only used for staking invoices.
   */
  address?: string | null;
  /**
   * Oob
   *
   * The oob code for the invoice. Only used for signup invoices.
   */
  oob?: string | null;
  /**
   * User Id
   *
   * The ID of the user
   */
  user_id: string;
  /**
   * Usd Amount
   *
   * The amount of the invoice in USD
   */
  usd_amount: number;
  /**
   * Url
   *
   * Invoice URL. If None, no external payment is required.
   */
  url?: string | null;
};

/**
 * InvoiceCreate
 *
 * Model for creating an invoice
 */
export type InvoiceCreate = {
  /**
   * Product Id
   *
   * The ID of the product
   */
  product_id: string;
  /**
   * Coupon Id
   *
   * The ID of the coupon
   */
  coupon_id?: string | null;
  /**
   * Provider
   *
   * The provider the invoice is created with
   */
  provider: 'now' | 'staking' | 'stripe';
  /**
   * Address
   *
   * The address of the user. Only used for staking invoices.
   */
  address?: string | null;
  /**
   * Oob
   *
   * The oob code for the invoice. Only used for signup invoices.
   */
  oob?: string | null;
  /**
   * User Id
   *
   * The ID of the user. Overrides the authenticated user if provided and the user is an admin.
   */
  user_id?: string | null;
};

/**
 * PaginatedResponse[Coupon]
 */
export type PaginatedResponseCoupon = {
  /**
   * Data
   */
  data: Array<Coupon>;
  /**
   * Total
   *
   * The total number of items
   */
  total: number;
  /**
   * Page
   *
   * The current page number
   */
  page: number;
  /**
   * Page Size
   *
   * The number of items per page
   */
  page_size: number;
  /**
   * Prev
   *
   * The previous page number
   */
  prev?: number | null;
  /**
   * Next
   *
   * The next page number
   */
  next?: number | null;
  /**
   * Last
   *
   * The last page number
   */
  last?: number | null;
};

/**
 * PaginatedResponse[Payment]
 */
export type PaginatedResponsePayment = {
  /**
   * Data
   */
  data: Array<Payment>;
  /**
   * Total
   *
   * The total number of items
   */
  total: number;
  /**
   * Page
   *
   * The current page number
   */
  page: number;
  /**
   * Page Size
   *
   * The number of items per page
   */
  page_size: number;
  /**
   * Prev
   *
   * The previous page number
   */
  prev?: number | null;
  /**
   * Next
   *
   * The next page number
   */
  next?: number | null;
  /**
   * Last
   *
   * The last page number
   */
  last?: number | null;
};

/**
 * Payment
 *
 * Combined payment model across all services
 */
export type Payment = {
  /**
   * Id
   *
   * Payment ID
   */
  id: string;
  /**
   * Product Id
   *
   * Product purchased
   */
  product_id: string;
  /**
   * Coupon Id
   *
   * Coupon used for the payment
   */
  coupon_id?: string | null;
  /**
   * User Id
   *
   * User ID the payment is for
   */
  user_id: string;
  /**
   * Invoice Id
   *
   * Invoice ID
   */
  invoice_id: string;
  /**
   * Amount
   *
   * Payment amount
   */
  amount: number;
  /**
   * Currency
   *
   * Payment currency
   */
  currency: string;
  /**
   * Status
   *
   * Payment status
   */
  status:
    | 'waiting'
    | 'processing'
    | 'paid'
    | 'partially_paid'
    | 'refunded'
    | 'failed'
    | 'cancelled';
  /**
   * Provider
   *
   * Payment provider
   */
  provider: 'now' | 'staking' | 'stripe';
  /**
   * Market
   *
   * Payment market
   */
  market: 'crypto' | 'fiat';
  /**
   * Updated At
   *
   * Payment updated at timestamp in seconds
   */
  updated_at: number;
  /**
   * Created At
   *
   * Payment created at timestamp in seconds
   */
  created_at: number;
  /**
   * Details
   *
   * Payment details specific to the provider
   */
  details?: {
    [key: string]: unknown;
  };
};

/**
 * Product
 *
 * Model for reading a product
 */
export type Product = {
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Id
   *
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Name
   *
   * Product name
   */
  name: string;
  /**
   * Price
   *
   * Product price
   */
  price: number;
  /**
   * Scopes
   *
   * Scopes that product provides
   */
  scopes: Array<AccessScope>;
  /**
   * Duration
   *
   * Product duration in days. 0 means forever.
   */
  duration: number;
  /**
   * Description
   *
   * Product description
   */
  description: string;
  /**
   * Is Active
   *
   * Product is active
   */
  is_active: boolean;
  /**
   * Images
   *
   * Product images as hosted URLs
   */
  images?: Array<string> | null;
  /**
   * Original Price
   *
   * Original product price. This is the price before the coupon is applied. None if no coupon is applied.
   */
  original_price?: number | null;
};

/**
 * ProductCreate
 *
 * Model for creating a product
 */
export type ProductCreate = {
  /**
   * Name
   *
   * Product name
   */
  name: string;
  /**
   * Price
   *
   * Product price
   */
  price: number;
  /**
   * Scopes
   *
   * Scopes that product provides
   */
  scopes: Array<AccessScope>;
  /**
   * Duration
   *
   * Product duration in days. 0 means forever.
   */
  duration: number;
  /**
   * Description
   *
   * Product description
   */
  description: string;
  /**
   * Is Active
   *
   * Product is active
   */
  is_active: boolean;
  /**
   * Images
   *
   * Product images as hosted URLs
   */
  images?: Array<string> | null;
};

/**
 * ProductUpdate
 *
 * Model for updating a product
 */
export type ProductUpdate = {
  /**
   * Name
   *
   * Product name
   */
  name?: string | null;
  /**
   * Price
   *
   * Product price
   */
  price?: number | null;
  /**
   * Scopes
   *
   * Scopes that product provides
   */
  scopes?: Array<AccessScope> | null;
  /**
   * Duration
   *
   * Product duration in days. 0 means forever.
   */
  duration?: number | null;
  /**
   * Description
   *
   * Product description
   */
  description?: string | null;
  /**
   * Is Active
   *
   * Product is active
   */
  is_active?: boolean | null;
  /**
   * Images
   *
   * Product images as hosted URLs
   */
  images?: Array<string> | null;
};

/**
 * ScopeInfo
 *
 * Model for detailed scope access info for a user, for each access method.
 */
export type ScopeInfo = {
  /**
   * The scope affected
   */
  scope: AccessScope;
  /**
   * Expires At
   *
   * Expiry timestamp in seconds, or None if not applicable (e.g. balance-based)
   */
  expires_at?: number | null;
  /**
   * Has Expired
   *
   * Whether the scope has expired or not
   */
  has_expired: boolean;
  /**
   * Reason
   *
   * Reason for access (allowlist, subscription, balance, etc.)
   */
  reason: 'allowlist' | 'subscription' | 'balance';
};

/**
 * ScopesInfo
 *
 * Model containing all scopes the user has access to, and detailed info for each access method (allowlist, subscription, balance).
 */
export type ScopesInfo = {
  /**
   * Scopes
   *
   * List of scopes
   */
  scopes: Array<AccessScope>;
  /**
   * Info
   *
   * List of scope access info. Contains one entry for each scope, for each access method (allowlist, subscription, balance) if the user has (or had in the last 7 days) access to the scope.
   */
  info: Array<ScopeInfo>;
};

/**
 * StakeDetails
 *
 * Details of a staking pool
 */
export type StakeDetails = {
  /**
   * Pool Id
   *
   * The ID of the staking pool.
   */
  pool_id: 1 | 2 | 3 | 4;
  /**
   * Reward Base
   *
   * The base reward amount accumulated so far, in wei (1 ETH = 1e18 wei).
   */
  reward_base: string;
  /**
   * Current Stake
   *
   * The amount currently staked by the user, in wei.
   */
  current_stake: string;
  /**
   * Start Time
   *
   * The Unix timestamp (in seconds) when the stake was created.
   */
  start_time: string;
  /**
   * Lock Period
   *
   * The duration the stake is locked for, in seconds (e.g., 5184000 = 60 days).
   */
  lock_period: string;
  /**
   * Apy
   *
   * The annual percentage yield (APY), represented in wei format (e.g., 1e18 = 100%).
   */
  apy: string;
  /**
   * Pending Reward
   *
   * The reward currently available to claim, in wei.
   */
  pending_reward: string;
  /**
   * Pending Withdrawal
   *
   * The amount currently pending to withdraw, in wei.
   */
  pending_withdrawal: string;
};

/**
 * Subscription
 *
 * Model for reading a product subscription
 */
export type Subscription = {
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Id
   *
   * Unique identifier for the resource
   */
  id: string;
  /**
   * User Id
   *
   * User ID
   */
  user_id: string;
  /**
   * Product Id
   *
   * Product ID
   */
  product_id: string;
  /**
   * Access From
   *
   * Access from timestamp in seconds
   */
  access_from: number;
  /**
   * Access Until
   *
   * Access until timestamp in seconds.
   */
  access_until: number;
};

/**
 * TotalBalance
 *
 * Model for a user's total balance
 */
export type TotalBalance = {
  /**
   * Staked
   *
   * Total staked balance in wei of AIC
   */
  staked: string;
  /**
   * Balance
   *
   * Total balance in wei of AIC
   */
  balance: string;
  /**
   * Reward Base
   *
   * Total reward base in wei of AIC
   */
  reward_base: string;
  /**
   * Pending Reward
   *
   * Total pending reward in wei of AIC
   */
  pending_reward: string;
  /**
   * Pending Withdrawal
   *
   * Total pending withdrawal in wei of AIC
   */
  pending_withdrawal: string;
  /**
   * Average Apy
   *
   * The average APY on the staked balance calculated from the pool balances and their APYs. 1e18 = 100%
   */
  average_apy: string;
};

/**
 * UserBalance
 *
 * Model for a user's balance
 */
export type UserBalance = {
  /**
   * Wallets
   *
   * List of wallet balances
   */
  wallets: Array<WalletBalance>;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Combined balance information computed from the wallet balances
   */
  total: TotalBalance;
  /**
   * Pools
   *
   * List of pool balances computed from the wallet balances
   */
  readonly pools: Array<StakeDetails>;
};

/**
 * WalletBalance
 *
 * Model for a user's balance for a specific wallet
 */
export type WalletBalance = {
  /**
   * Address
   *
   * Wallet address
   */
  address: string;
  /**
   * Balance
   *
   * Balance in wei of AIC
   */
  balance: string;
  /**
   * Staked
   *
   * List of stake details for each pool
   */
  staked: Array<StakeDetails>;
};

/**
 * Coupon
 *
 * Model for reading a coupon
 */
export type CouponWritable = {
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at: number;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
  /**
   * Id
   *
   * Unique identifier for the resource
   */
  id: string;
  /**
   * Code
   *
   * Coupon code. If not specified, a random code is generated.
   */
  code?: string;
  /**
   * Name
   *
   * A name for the coupon, e.g. 'Black Friday 2025'
   */
  name: string;
  /**
   * Discount
   *
   * Discount percentage as a decimal
   */
  discount: number;
  /**
   * Valid Until
   *
   * Coupon valid until timestamp in seconds. If not specified, the coupon does not expire.
   */
  valid_until?: number | null;
  /**
   * Valid From
   *
   * Coupon valid from timestamp in seconds. If not specified, the coupon is valid from the current time.
   */
  valid_from?: number;
  /**
   * Usage Limit
   *
   * Coupon usage limit. If not specified, the coupon can be used unlimited times.
   */
  usage_limit?: number | null;
  /**
   * Products
   *
   * Products that the coupon can be used on. If not specified, the coupon can be used on all products.
   */
  products?: Array<string> | null;
  /**
   * Is Active
   *
   * Coupon is active
   */
  is_active?: boolean;
  /**
   * Usage Count
   *
   * Coupon usage count
   */
  usage_count: number;
};

/**
 * UserBalance
 *
 * Model for a user's balance
 */
export type UserBalanceWritable = {
  /**
   * Wallets
   *
   * List of wallet balances
   */
  wallets: Array<WalletBalance>;
  /**
   * Updated At
   *
   * Timestamp of last update
   */
  updated_at: number;
};

export type GetProductsCaptchaAuthData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Coupon
     *
     * The coupon code to apply to the products.
     */
    coupon?: string | null;
    /**
     * Captcha Token
     *
     * The captcha token to verify the request.
     */
    captcha_token?: string;
  };
  url: '/products/captcha';
};

export type GetProductsCaptchaAuthErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetProductsCaptchaAuthError =
  GetProductsCaptchaAuthErrors[keyof GetProductsCaptchaAuthErrors];

export type GetProductsCaptchaAuthResponses = {
  /**
   * Response Get Products Captcha Auth
   *
   * Successful Response
   */
  200: Array<Product>;
};

export type GetProductsCaptchaAuthResponse =
  GetProductsCaptchaAuthResponses[keyof GetProductsCaptchaAuthResponses];

export type GetProductsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter By
     *
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * Filter Value
     *
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * Sort Order
     *
     * The order to sort by
     */
    sort_order?: 'asc' | 'desc' | null;
    /**
     * Sort By
     *
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * Coupon
     *
     * The coupon code to apply to the products.
     */
    coupon?: string | null;
  };
  url: '/products';
};

export type GetProductsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
  /**
   * Response Get Products
   *
   * Successful Response
   */
  200: Array<Product>;
};

export type GetProductsResponse =
  GetProductsResponses[keyof GetProductsResponses];

export type CreateProductData = {
  /**
   * The product to create
   */
  body: ProductCreate;
  path?: never;
  query?: never;
  url: '/products';
};

export type CreateProductErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
  /**
   * Successful Response
   */
  201: Product;
};

export type CreateProductResponse =
  CreateProductResponses[keyof CreateProductResponses];

export type GetProductUsageData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/products/usage';
};

export type GetProductUsageErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetProductUsageError =
  GetProductUsageErrors[keyof GetProductUsageErrors];

export type GetProductUsageResponses = {
  /**
   * Response Get Product Usage
   *
   * Successful Response
   */
  200: Array<[string, number]>;
};

export type GetProductUsageResponse =
  GetProductUsageResponses[keyof GetProductUsageResponses];

export type UpdateProductData = {
  /**
   * The product to update
   */
  body: ProductUpdate;
  path: {
    /**
     * Id
     *
     * The ID of the product to update
     */
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type UpdateProductErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
  /**
   * Successful Response
   */
  200: Product;
};

export type UpdateProductResponse =
  UpdateProductResponses[keyof UpdateProductResponses];

export type GetPaymentHistoryData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter By
     *
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * Filter Value
     *
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * Sort Order
     *
     * The order to sort by
     */
    sort_order?: 'asc' | 'desc' | null;
    /**
     * Sort By
     *
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * Page
     *
     * The current page number
     */
    page?: number;
    /**
     * Page Size
     *
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
    /**
     * User Id
     *
     * The ID of the user. Overrides the authenticated user if provided and the user is an admin.
     */
    user_id?: string | null;
  };
  url: '/payments/history';
};

export type GetPaymentHistoryErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetPaymentHistoryError =
  GetPaymentHistoryErrors[keyof GetPaymentHistoryErrors];

export type GetPaymentHistoryResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponsePayment;
};

export type GetPaymentHistoryResponse =
  GetPaymentHistoryResponses[keyof GetPaymentHistoryResponses];

export type GetSubscriptionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * User Id
     *
     * The ID of the user to get subscriptions for. Overrides the authenticated user if provided and the user is an admin.
     */
    user_id?: string | null;
    /**
     * State
     *
     * The state of the subscriptions to get. Defaults to all states.
     */
    state?: 'active' | 'inactive' | 'both';
  };
  url: '/payments/subscriptions';
};

export type GetSubscriptionsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetSubscriptionsError =
  GetSubscriptionsErrors[keyof GetSubscriptionsErrors];

export type GetSubscriptionsResponses = {
  /**
   * Response Get Subscriptions
   *
   * Successful Response
   */
  200: Array<Subscription>;
};

export type GetSubscriptionsResponse =
  GetSubscriptionsResponses[keyof GetSubscriptionsResponses];

export type GetPaymentsByInvoiceData = {
  body?: never;
  path: {
    /**
     * Id
     *
     * The invoice ID
     */
    id: string;
  };
  query?: never;
  url: '/payments/by-invoice/{id}';
};

export type GetPaymentsByInvoiceErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetPaymentsByInvoiceError =
  GetPaymentsByInvoiceErrors[keyof GetPaymentsByInvoiceErrors];

export type GetPaymentsByInvoiceResponses = {
  /**
   * Response Get Payments By Invoice
   *
   * Successful Response
   */
  200: Array<Payment>;
};

export type GetPaymentsByInvoiceResponse =
  GetPaymentsByInvoiceResponses[keyof GetPaymentsByInvoiceResponses];

export type GetCouponByCodeCaptchaAuthData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     *
     * The coupon code to get
     */
    code: string;
    /**
     * Captcha Token
     */
    captcha_token: string;
  };
  url: '/coupons/by-code/captcha';
};

export type GetCouponByCodeCaptchaAuthErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetCouponByCodeCaptchaAuthError =
  GetCouponByCodeCaptchaAuthErrors[keyof GetCouponByCodeCaptchaAuthErrors];

export type GetCouponByCodeCaptchaAuthResponses = {
  /**
   * Successful Response
   */
  200: Coupon;
};

export type GetCouponByCodeCaptchaAuthResponse =
  GetCouponByCodeCaptchaAuthResponses[keyof GetCouponByCodeCaptchaAuthResponses];

export type GetCouponByCodeData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     *
     * The coupon code to get
     */
    code: string;
  };
  url: '/coupons/by-code';
};

export type GetCouponByCodeErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetCouponByCodeError =
  GetCouponByCodeErrors[keyof GetCouponByCodeErrors];

export type GetCouponByCodeResponses = {
  /**
   * Successful Response
   */
  200: Coupon;
};

export type GetCouponByCodeResponse =
  GetCouponByCodeResponses[keyof GetCouponByCodeResponses];

export type GetCouponsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter By
     *
     * The field to filter by
     */
    filter_by?: string | null;
    /**
     * Filter Value
     *
     * The value to filter with
     */
    filter_value?: string | null;
    /**
     * Sort Order
     *
     * The order to sort by
     */
    sort_order?: 'asc' | 'desc' | null;
    /**
     * Sort By
     *
     * The field to sort by
     */
    sort_by?: string | null;
    /**
     * Page
     *
     * The current page number
     */
    page?: number;
    /**
     * Page Size
     *
     * The number of items per page. Default is 10, max is 100.
     */
    page_size?: number;
  };
  url: '/coupons';
};

export type GetCouponsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetCouponsError = GetCouponsErrors[keyof GetCouponsErrors];

export type GetCouponsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseCoupon;
};

export type GetCouponsResponse = GetCouponsResponses[keyof GetCouponsResponses];

export type CreateCouponData = {
  /**
   * The coupon to create
   */
  body: CouponCreate;
  path?: never;
  query?: never;
  url: '/coupons';
};

export type CreateCouponErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type CreateCouponError = CreateCouponErrors[keyof CreateCouponErrors];

export type CreateCouponResponses = {
  /**
   * Successful Response
   */
  201: Coupon;
};

export type CreateCouponResponse =
  CreateCouponResponses[keyof CreateCouponResponses];

export type DeactivateCouponData = {
  body?: never;
  path: {
    /**
     * Id
     *
     * The coupon to deactivate
     */
    id: string;
  };
  query?: never;
  url: '/coupons/{id}';
};

export type DeactivateCouponErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DeactivateCouponError =
  DeactivateCouponErrors[keyof DeactivateCouponErrors];

export type DeactivateCouponResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeactivateCouponResponse =
  DeactivateCouponResponses[keyof DeactivateCouponResponses];

export type UpdateCouponData = {
  /**
   * The coupon to update
   */
  body: CouponUpdate;
  path: {
    /**
     * Id
     *
     * The coupon to update
     */
    id: string;
  };
  query?: never;
  url: '/coupons/{id}';
};

export type UpdateCouponErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UpdateCouponError = UpdateCouponErrors[keyof UpdateCouponErrors];

export type UpdateCouponResponses = {
  /**
   * Successful Response
   */
  201: Coupon;
};

export type UpdateCouponResponse =
  UpdateCouponResponses[keyof UpdateCouponResponses];

export type GetNowApiStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/now/status';
};

export type GetNowApiStatusErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetNowApiStatusError =
  GetNowApiStatusErrors[keyof GetNowApiStatusErrors];

export type GetNowApiStatusResponses = {
  /**
   * Response Get Now Api Status
   *
   * Successful Response
   */
  200: string;
};

export type GetNowApiStatusResponse =
  GetNowApiStatusResponses[keyof GetNowApiStatusResponses];

export type HandleNowWebhookData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/now/webhook';
};

export type HandleNowWebhookErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type HandleNowWebhookError =
  HandleNowWebhookErrors[keyof HandleNowWebhookErrors];

export type HandleNowWebhookResponses = {
  /**
   * Successful Response
   */
  201: unknown;
};

export type CreateInvoiceData = {
  /**
   * The invoice to create
   */
  body: InvoiceCreate;
  path?: never;
  query?: never;
  url: '/invoices';
};

export type CreateInvoiceErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type CreateInvoiceError = CreateInvoiceErrors[keyof CreateInvoiceErrors];

export type CreateInvoiceResponses = {
  /**
   * Successful Response
   */
  201: Invoice;
};

export type CreateInvoiceResponse =
  CreateInvoiceResponses[keyof CreateInvoiceResponses];

export type GetInvoiceData = {
  body?: never;
  path: {
    /**
     * Id
     *
     * The invoice ID
     */
    id: string;
  };
  query?: never;
  url: '/invoices/{id}';
};

export type GetInvoiceErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetInvoiceError = GetInvoiceErrors[keyof GetInvoiceErrors];

export type GetInvoiceResponses = {
  /**
   * Successful Response
   */
  200: Invoice;
};

export type GetInvoiceResponse = GetInvoiceResponses[keyof GetInvoiceResponses];

export type StripeWebhookStripeWebhookPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/stripe/webhook';
};

export type StripeWebhookStripeWebhookPostErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type StripeWebhookStripeWebhookPostError =
  StripeWebhookStripeWebhookPostErrors[keyof StripeWebhookStripeWebhookPostErrors];

export type StripeWebhookStripeWebhookPostResponses = {
  /**
   * Successful Response
   */
  201: unknown;
};

export type GetAicPriceData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Force
     *
     * Force live fetch and update cache.
     */
    force?: boolean;
  };
  url: '/token/price';
};

export type GetAicPriceErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetAicPriceError = GetAicPriceErrors[keyof GetAicPriceErrors];

export type GetAicPriceResponses = {
  /**
   * Response Get Aic Price
   *
   * Successful Response
   */
  200: number;
};

export type GetAicPriceResponse =
  GetAicPriceResponses[keyof GetAicPriceResponses];

export type GetBalancesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * User Id
     *
     * User ID to check balance for. Overrides the authenticated user if provided and the user is an admin.
     */
    user_id?: string | null;
    /**
     * Force
     *
     * Force live fetch and update cache.
     */
    force?: boolean;
  };
  url: '/token/balances';
};

export type GetBalancesErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetBalancesError = GetBalancesErrors[keyof GetBalancesErrors];

export type GetBalancesResponses = {
  /**
   * Successful Response
   */
  200: UserBalance;
};

export type GetBalancesResponse =
  GetBalancesResponses[keyof GetBalancesResponses];

export type GetBalances2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * User Id
     *
     * Wallet address to check balance for. Overrides the authenticated user if provided and the user is an admin.
     */
    user_id?: string | null;
    /**
     * Force
     *
     * Force live fetch and update cache.
     */
    force?: boolean;
  };
  url: '/access/balances';
};

export type GetBalances2Errors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetBalances2Error = GetBalances2Errors[keyof GetBalances2Errors];

export type GetBalances2Responses = {
  /**
   * Successful Response
   */
  200: UserBalance;
};

export type GetBalances2Response =
  GetBalances2Responses[keyof GetBalances2Responses];

export type GetScopesInfoData = {
  body?: never;
  path?: never;
  query: {
    /**
     * User Id
     *
     * User ID to get scopes for
     */
    user_id: string;
    /**
     * Force
     *
     * Force live fetch and update cache.
     */
    force?: boolean;
  };
  url: '/access/scopes/info';
};

export type GetScopesInfoErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetScopesInfoError = GetScopesInfoErrors[keyof GetScopesInfoErrors];

export type GetScopesInfoResponses = {
  /**
   * Successful Response
   */
  200: ScopesInfo;
};

export type GetScopesInfoResponse =
  GetScopesInfoResponses[keyof GetScopesInfoResponses];

export type GetThresholdsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/access/thresholds';
};

export type GetThresholdsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetThresholdsError = GetThresholdsErrors[keyof GetThresholdsErrors];

export type GetThresholdsResponses = {
  /**
   * Response Get Thresholds
   *
   * Successful Response
   */
  200: Array<AccessThreshold>;
};

export type GetThresholdsResponse =
  GetThresholdsResponses[keyof GetThresholdsResponses];

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type PingErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type PingError = PingErrors[keyof PingErrors];

export type PingResponses = {
  /**
   * Response Ping
   *
   * Successful Response
   */
  200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/metrics';
};

export type GetMetricsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetMetricsError = GetMetricsErrors[keyof GetMetricsErrors];

export type GetMetricsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
