// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorIdentifierSchema = {
  type: "string",
  title: "ApiErrorIdentifier",
  description: "API error identifiers",
} as const;

export const ApiErrorLevelSchema = {
  type: "string",
  title: "ApiErrorLevel",
  description: "API error levels",
} as const;

export const ApiErrorTypeSchema = {
  type: "string",
  title: "ApiErrorType",
  description: "Type of API error",
} as const;

export const CoinsSchema = {
  type: "string",
  enum: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
  title: "Coins",
  description: "All ever existing coins",
} as const;

export const DataDownloadResponseSchema = {
  properties: {
    coin: {
      $ref: "#/components/schemas/Coins",
    },
    feature_size: {
      $ref: "#/components/schemas/FeatureSize",
    },
    version: {
      $ref: "#/components/schemas/DataVersion",
    },
    target: {
      $ref: "#/components/schemas/Target",
    },
    links: {
      $ref: "#/components/schemas/DownloadLinks",
    },
  },
  type: "object",
  required: ["coin", "feature_size", "version", "target", "links"],
  title: "DataDownloadResponse",
} as const;

export const DataInfoSchema = {
  properties: {
    data: {
      additionalProperties: {
        additionalProperties: {
          additionalProperties: {
            items: {
              anyOf: [
                {
                  $ref: "#/components/schemas/FeatureSize",
                },
                {
                  $ref: "#/components/schemas/Target",
                },
              ],
            },
            type: "array",
          },
          propertyNames: {
            enum: ["targets", "feature_sizes"],
          },
          type: "object",
        },
        propertyNames: {
          $ref: "#/components/schemas/Coins",
        },
        type: "object",
      },
      propertyNames: {
        $ref: "#/components/schemas/DataVersion",
      },
      type: "object",
      title: "Data",
    },
    coins: {
      items: {
        $ref: "#/components/schemas/Coins",
      },
      type: "array",
      title: "Coins",
    },
    feature_sizes: {
      items: {
        $ref: "#/components/schemas/FeatureSize",
      },
      type: "array",
      title: "Feature Sizes",
    },
    targets: {
      items: {
        $ref: "#/components/schemas/TargetInfo",
      },
      type: "array",
      title: "Targets",
    },
    all_versions: {
      items: {
        $ref: "#/components/schemas/DataVersionInfo",
      },
      type: "array",
      title: "All Versions",
    },
    available_versions: {
      items: {
        $ref: "#/components/schemas/DataVersionInfo",
      },
      type: "array",
      title: "Available Versions",
    },
  },
  type: "object",
  required: [
    "data",
    "coins",
    "feature_sizes",
    "targets",
    "all_versions",
    "available_versions",
  ],
  title: "DataInfo",
} as const;

export const DataVersionSchema = {
  type: "string",
  enum: ["1.0"],
  title: "DataVersion",
  description: "All ever existing data versions",
} as const;

export const DataVersionInfoSchema = {
  properties: {
    version: {
      $ref: "#/components/schemas/DataVersion",
      description: "Data version",
    },
    release_date: {
      type: "integer",
      title: "Release Date",
      description: "Release date of the data version in unix timestamp",
    },
  },
  type: "object",
  required: ["version", "release_date"],
  title: "DataVersionInfo",
} as const;

export const DownloadLinksSchema = {
  properties: {
    y_train: {
      type: "string",
      title: "Y Train",
    },
    X_test: {
      type: "string",
      title: "X Test",
    },
    X_train: {
      type: "string",
      title: "X Train",
    },
  },
  type: "object",
  required: ["y_train", "X_test", "X_train"],
  title: "DownloadLinks",
} as const;

export const EvaluationSchema = {
  properties: {
    timestamp: {
      type: "integer",
      title: "Timestamp",
      description: "Evaluation timestamp",
    },
    score: {
      type: "number",
      title: "Score",
      description: "Evaluation score",
    },
  },
  type: "object",
  required: ["timestamp", "score"],
  title: "Evaluation",
  description: "Pydantic model for model evaluation data",
} as const;

export const EvaluationResponseSchema = {
  properties: {
    metrics: {
      additionalProperties: {
        type: "number",
      },
      type: "object",
      title: "Metrics",
      description: "Evaluation metrics",
    },
  },
  type: "object",
  required: ["metrics"],
  title: "EvaluationResponse",
  description: "Pydantic model for evaluation response",
} as const;

export const ExceptionDetailSchema = {
  properties: {
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Message",
      description: "An additional error message",
    },
    code: {
      $ref: "#/components/schemas/ApiErrorIdentifier",
      description: "The unique error code",
    },
    type: {
      $ref: "#/components/schemas/ApiErrorType",
      description: "The type of error",
    },
    level: {
      $ref: "#/components/schemas/ApiErrorLevel",
      description: "The level of the error",
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      description: "The HTTP status code",
    },
    details: {
      title: "Details",
      description: "Additional details about the error",
    },
  },
  type: "object",
  required: ["code", "type", "level", "status_code"],
  title: "ExceptionDetail",
  description:
    "This is the detail of the exception. It is used to enrich the exception with additional information by unwrapping the ApiError into its components.",
} as const;

export const FeatureSizeSchema = {
  type: "string",
  enum: ["small", "medium", "large"],
  title: "FeatureSize",
  description: "All ever existing feature sizes",
} as const;

export const ModelSchema = {
  properties: {
    model_id: {
      type: "integer",
      title: "Model Id",
      description: "Unique model identifier",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Model name",
    },
    coin_id: {
      $ref: "#/components/schemas/Coins",
      description: "Coin ID",
    },
    target: {
      $ref: "#/components/schemas/Target",
      description: "Target variable",
    },
    status: {
      $ref: "#/components/schemas/ModelStatus",
      description: "Model status",
    },
    target_type: {
      $ref: "#/components/schemas/TargetType",
      description: "Target type",
    },
    evaluations: {
      items: {
        $ref: "#/components/schemas/Evaluation",
      },
      type: "array",
      title: "Evaluations",
      description: "Model evaluations",
    },
    user_id: {
      type: "string",
      title: "User Id",
      description: "Developer user ID",
    },
    created_at: {
      type: "integer",
      title: "Created At",
      description: "Model creation unix timestamp",
    },
    updated_at: {
      type: "integer",
      title: "Updated At",
      description: "Model update unix timestamp",
    },
  },
  type: "object",
  required: [
    "model_id",
    "name",
    "coin_id",
    "target",
    "status",
    "target_type",
    "evaluations",
    "user_id",
    "created_at",
    "updated_at",
  ],
  title: "Model",
  description: "Pydantic model for model response",
} as const;

export const ModelCreateSchema = {
  properties: {
    coin_id: {
      $ref: "#/components/schemas/Coins",
      description: "Coin ID for the model",
    },
    target: {
      $ref: "#/components/schemas/Target",
      description: "Target variable for the model",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Model name",
    },
  },
  type: "object",
  required: ["coin_id", "target", "name"],
  title: "ModelCreate",
  description: "Base Pydantic model for model data",
} as const;

export const ModelStatusSchema = {
  type: "string",
  enum: ["created", "evaluated"],
  title: "ModelStatus",
  description: "Enum for model status",
} as const;

export const ModelUpdateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Model name",
    },
  },
  type: "object",
  required: ["name"],
  title: "ModelUpdate",
  description: "Pydantic model for model update",
} as const;

export const TargetSchema = {
  type: "string",
  enum: ["Tatooine", "Alderaan", "Hoth"],
  title: "Target",
  description: "All ever existing targets",
} as const;

export const TargetInfoSchema = {
  properties: {
    name: {
      $ref: "#/components/schemas/Target",
      description: "Target name",
    },
    type: {
      $ref: "#/components/schemas/TargetType",
      description: "Target type",
    },
    version: {
      $ref: "#/components/schemas/DataVersion",
      description: "Data version",
    },
  },
  type: "object",
  required: ["name", "type", "version"],
  title: "TargetInfo",
} as const;

export const TargetTypeSchema = {
  type: "string",
  enum: ["continuous", "binary"],
  title: "TargetType",
} as const;
