import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  PingError,
  PingResponse,
  GetTimeData,
  GetTimeError,
  GetTimeResponse,
  GetConfigError,
  GetConfigResponse,
  CreateModelData,
  CreateModelError,
  CreateModelResponse,
  EvaluateModelData,
  EvaluateModelError,
  EvaluateModelResponse,
  GetModelData,
  GetModelError,
  GetModelResponse,
  GetAllModelsError,
  GetAllModelsResponse,
  DeleteModelData,
  DeleteModelError,
  DeleteModelResponse,
  UpdateModelData,
  UpdateModelError,
  UpdateModelResponse,
  DownloadDataData,
  DownloadDataError,
  DownloadDataResponse,
  GetDataInfoError,
  GetDataInfoResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Time
   * Returns the current time in the specified format.
   */
  const getTime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetTimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTimeResponse,
      GetTimeError,
      ThrowOnError
    >({
      ...options,
      url: "/time",
    });
  };

  /**
   * Config
   * Returns the version of the crypticorn library and the environment.
   */
  const getConfig = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetConfigResponse,
      GetConfigError,
      ThrowOnError
    >({
      ...options,
      url: "/config",
    });
  };

  /**
   * Create Model
   * Create a new model
   */
  const createModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateModelResponse,
      CreateModelError,
      ThrowOnError
    >({
      ...options,
      url: "/model/creation",
    });
  };

  /**
   * Evaluate Model
   * Evaluate a model's predictions
   */
  const evaluateModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<EvaluateModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      EvaluateModelResponse,
      EvaluateModelError,
      ThrowOnError
    >({
      ...options,
      url: "/model/evaluation/{id}",
    });
  };

  /**
   * Get Model
   * Get a model by ID or name
   */
  const getModel = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetModelResponse,
      GetModelError,
      ThrowOnError
    >({
      ...options,
      url: "/model",
    });
  };

  /**
   * Get All Models
   * List all models
   */
  const getAllModels = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetAllModelsResponse,
      GetAllModelsError,
      ThrowOnError
    >({
      ...options,
      url: "/model/all",
    });
  };

  /**
   * Delete Model
   * Delete a model
   */
  const deleteModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteModelResponse,
      DeleteModelError,
      ThrowOnError
    >({
      ...options,
      url: "/model/{id}",
    });
  };

  /**
   * Update Model
   * Update a model's information
   */
  const updateModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateModelResponse,
      UpdateModelError,
      ThrowOnError
    >({
      ...options,
      url: "/model/{id}",
    });
  };

  /**
   * Download Data
   * Get download links for model training data
   */
  const downloadData = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DownloadDataData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      DownloadDataResponse,
      DownloadDataError,
      ThrowOnError
    >({
      ...options,
      url: "/data",
    });
  };

  /**
   * Get Data Info
   * Get information about available data and options for the latest data version
   */
  const getDataInfo = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetDataInfoResponse,
      GetDataInfoError,
      ThrowOnError
    >({
      ...options,
      url: "/data/info",
    });
  };

  return {
    ping,
    getTime,
    getConfig,
    createModel,
    evaluateModel,
    getModel,
    getAllModels,
    deleteModel,
    updateModel,
    downloadData,
    getDataInfo,
  };
}
