import {
  createClient as createNativeClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";

import type {
  PingError,
  PingResponse,
  GetTimeData,
  GetTimeError,
  GetTimeResponse,
  CreateModelData,
  CreateModelError,
  CreateModelResponse,
  EvaluateModelData,
  EvaluateModelError,
  EvaluateModelResponse,
  GetModelData,
  GetModelError,
  GetModelResponse,
  DeleteModelData,
  DeleteModelError,
  DeleteModelResponse,
  UpdateModelData,
  UpdateModelError,
  UpdateModelResponse,
  GetModelByNameData,
  GetModelByNameError,
  GetModelByNameResponse,
  GetModelsData,
  GetModelsError,
  GetModelsResponse,
  DownloadDataData,
  DownloadDataError,
  DownloadDataResponse,
  GetDataInfoError,
  GetDataInfoResponse,
  GetLogLevelError,
  GetLogLevelResponse,
  GetUptimeData,
  GetUptimeError,
  GetUptimeResponse,
  GetMemoryUsageError,
  GetMemoryUsageResponse,
  GetThreadsError,
  GetThreadsResponse,
  GetContainerLimitsError,
  GetContainerLimitsResponse,
  GetDependenciesData,
  GetDependenciesError,
  GetDependenciesResponse,
} from "./types.gen";

export function createClient(
  baseUrl: string,
  headers: any,
  fetch = globalThis.fetch,
) {
  const client = createNativeClient(
    createConfig({
      baseUrl,
      fetch,
      headers,
    }),
  );

  // This file is auto-generated by @hey-api/openapi-ts

  /**
   * Ping
   * Returns 'OK' if the API is running.
   */
  const ping = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      PingResponse,
      PingError,
      ThrowOnError
    >({
      ...options,
      url: "/",
    });
  };

  /**
   * Time
   * Returns the current time in either ISO or Unix timestamp (seconds) format.
   */
  const getTime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetTimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetTimeResponse,
      GetTimeError,
      ThrowOnError
    >({
      ...options,
      url: "/time",
    });
  };

  /**
   * Create Model
   * Create a new model
   */
  const createModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<CreateModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      CreateModelResponse,
      CreateModelError,
      ThrowOnError
    >({
      ...options,
      url: "/models/creation",
    });
  };

  /**
   * Evaluate Model
   * Evaluate a model's predictions against the internal `y_test` data. Returns metrics based on the type of the model.
   */
  const evaluateModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<EvaluateModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).post<
      EvaluateModelResponse,
      EvaluateModelError,
      ThrowOnError
    >({
      ...options,
      url: "/models/evaluation/{id}",
    });
  };

  /**
   * Get Model
   * Get a model by ID
   */
  const getModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetModelResponse,
      GetModelError,
      ThrowOnError
    >({
      ...options,
      url: "/models/{id}",
    });
  };

  /**
   * Delete Model
   * Delete a model
   */
  const deleteModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DeleteModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).delete<
      DeleteModelResponse,
      DeleteModelError,
      ThrowOnError
    >({
      ...options,
      url: "/models/{id}",
    });
  };

  /**
   * Update Model
   * Update a model's information
   */
  const updateModel = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<UpdateModelData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).put<
      UpdateModelResponse,
      UpdateModelError,
      ThrowOnError
    >({
      ...options,
      url: "/models/{id}",
    });
  };

  /**
   * Get Model By Name
   * Get a model by name
   */
  const getModelByName = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<GetModelByNameData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetModelByNameResponse,
      GetModelByNameError,
      ThrowOnError
    >({
      ...options,
      url: "/models/by-name/{name}",
    });
  };

  /**
   * Get All Models
   * List all models
   */
  const getModels = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetModelsData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetModelsResponse,
      GetModelsError,
      ThrowOnError
    >({
      ...options,
      url: "/models",
    });
  };

  /**
   * Download Data
   * Get download links for model training data
   */
  const downloadData = <ThrowOnError extends boolean = false>(
    options: OptionsLegacyParser<DownloadDataData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      DownloadDataResponse,
      DownloadDataError,
      ThrowOnError
    >({
      ...options,
      url: "/data",
    });
  };

  /**
   * Get Data Info
   * Get information about available data and options for the latest data version
   */
  const getDataInfo = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetDataInfoResponse,
      GetDataInfoError,
      ThrowOnError
    >({
      ...options,
      url: "/data/info",
    });
  };

  /**
   * @deprecated
   * Get Logging Level
   * Get the log level of the server logger. Will be removed in a future release.
   */
  const getLogLevel = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetLogLevelResponse,
      GetLogLevelError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/log-level",
    });
  };

  /**
   * Get Uptime
   * Return the server uptime in seconds or human-readable form.
   */
  const getUptime = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetUptimeData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetUptimeResponse,
      GetUptimeError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/uptime",
    });
  };

  /**
   * Get Memory Usage
   * Resident Set Size (RSS) in MB — the actual memory used by the process in RAM.
   * Represents the physical memory footprint. Important for monitoring real usage.
   */
  const getMemoryUsage = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetMemoryUsageResponse,
      GetMemoryUsageError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/memory",
    });
  };

  /**
   * Get Threads
   * Return count and names of active threads.
   */
  const getThreads = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetThreadsResponse,
      GetThreadsError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/threads",
    });
  };

  /**
   * Get Container Limits
   * Return container resource limits from cgroup.
   */
  const getContainerLimits = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<unknown, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetContainerLimitsResponse,
      GetContainerLimitsError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/limits",
    });
  };

  /**
   * List Installed Packages
   * Return a list of installed packages and versions.
   *
   * The include parameter accepts regex patterns to match against package names.
   * For example:
   * - crypticorn.* will match all packages starting with 'crypticorn'
   * - .*tic.* will match all packages containing 'tic' in their name
   */
  const getDependencies = <ThrowOnError extends boolean = false>(
    options?: OptionsLegacyParser<GetDependenciesData, ThrowOnError>,
  ) => {
    return (options?.client ?? client).get<
      GetDependenciesResponse,
      GetDependenciesError,
      ThrowOnError
    >({
      ...options,
      url: "/admin/dependencies",
    });
  };

  return {
    ping,
    getTime,
    createModel,
    evaluateModel,
    getModel,
    deleteModel,
    updateModel,
    getModelByName,
    getModels,
    downloadData,
    getDataInfo,
    getLogLevel,
    getUptime,
    getMemoryUsage,
    getThreads,
    getContainerLimits,
    getDependencies,
  };
}
