// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/v1/hive` | (string & {});
};

/**
 * BinaryEvaluation
 *
 * Pydantic model for binary evaluation
 */
export type BinaryEvaluation = {
  /**
   * Accuracy
   *
   * Accuracy
   */
  accuracy: number;
  /**
   * Roc Auc
   *
   * ROC AUC
   */
  roc_auc: number;
  /**
   * Precision
   *
   * Precision
   */
  precision: number;
  /**
   * Recall
   *
   * Recall
   */
  recall: number;
  /**
   * F1
   *
   * F1 score
   */
  f1: number;
  /**
   * Conf Matrix
   *
   * Confusion matrix
   */
  conf_matrix: Array<Array<number>>;
};

/**
 * CoinInfo
 *
 * Metadata about a cryptocurrency including availability across data versions.
 */
export type CoinInfo = {
  /**
   * Identifier
   *
   * The identifier of the coin. Obfuscated for public use.
   */
  identifier: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';
  /**
   * Version Added
   *
   * The data version the coin got introduced in
   */
  version_added: '1.0';
  /**
   * Version Removed
   *
   * The data version the coin got removed in. If None, the coin is still available.
   */
  version_removed?: '1.0' | null;
};

/**
 * ContinuousEvaluation
 *
 * Pydantic model for continuous evaluation
 */
export type ContinuousEvaluation = {
  /**
   * Cum Corr
   *
   * Cumulative correlation
   */
  cum_corr: number;
  /**
   * Corr
   *
   * Correlation
   */
  corr: number;
  /**
   * R2
   *
   * R-squared
   */
  r2: number;
  /**
   * Mape
   *
   * Mean Absolute Percentage Error
   */
  mape: number;
  /**
   * Mae
   *
   * Mean Absolute Error
   */
  mae: number;
  /**
   * Rmse
   *
   * Root Mean Squared Error
   */
  rmse: number;
};

/**
 * DataDownloadResponse
 *
 * Response model containing download links and metadata for requested training data.
 */
export type DataDownloadResponse = {
  /**
   * Coin
   *
   * The coin the data is for
   */
  coin: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';
  /**
   * Feature Size
   *
   * The feature size the data is for
   */
  feature_size: 'small' | 'medium' | 'large';
  /**
   * Version
   *
   * The version of the data
   */
  version: '1.0';
  /**
   * The target of the data
   */
  target: Target;
  /**
   * The download links for the data
   */
  links: DownloadLinks;
};

/**
 * DataInfo
 *
 * Comprehensive data catalog including all available datasets, versions, and metadata.
 */
export type DataInfo = {
  /**
   * Data
   *
   * The data available for all data versions.
   */
  data: {
    [key: string]: {
      [key: string]: DataOptions;
    };
  };
  /**
   * Coins
   *
   * The coins available for all data versions.
   */
  coins: Array<CoinInfo>;
  /**
   * Feature Sizes
   *
   * The feature sizes available for all data versions.
   */
  feature_sizes: Array<'small' | 'medium' | 'large'>;
  /**
   * Targets
   *
   * The targets available for all data versions.
   */
  targets: Array<TargetInfo>;
  /**
   * All Versions
   *
   * All ever existing data versions. Some may not be publicly available yet.
   */
  all_versions: Array<DataVersionInfo>;
  /**
   * Available Versions
   *
   * All publicly available data versions.
   */
  available_versions: Array<DataVersionInfo>;
};

/**
 * DataOptions
 *
 * Available options for targets and feature sizes in the latest data version.
 */
export type DataOptions = {
  /**
   * Targets
   *
   * The targets available on the latest data version.
   */
  targets: Array<Target>;
  /**
   * Feature Sizes
   *
   * The feature sizes available on the latest data version.
   */
  feature_sizes: Array<'small' | 'medium' | 'large'>;
};

/**
 * DataVersionInfo
 *
 * Information about a specific data version including release metadata.
 */
export type DataVersionInfo = {
  /**
   * Version
   *
   * Data version
   */
  version: '1.0';
  /**
   * Release Date
   *
   * Release date of the data version in unix timestamp
   */
  release_date: number;
};

/**
 * DownloadLinks
 *
 * Collection of secure download URLs for different dataset splits.
 */
export type DownloadLinks = {
  /**
   * Y Train
   *
   * The download link for the y_train data
   */
  y_train: string;
  /**
   * X Test
   *
   * The download link for the X_test data
   */
  X_test: string;
  /**
   * X Train
   *
   * The download link for the X_train data
   */
  X_train: string;
};

/**
 * ErrorResponse
 *
 * Error response schema.
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * Evaluation
 *
 * Pydantic model for model evaluation data
 */
export type Evaluation = {
  /**
   * Timestamp
   *
   * Evaluation timestamp
   */
  timestamp: number;
  /**
   * Score
   *
   * Evaluation score
   */
  score: number;
};

/**
 * EvaluationResponse
 *
 * Pydantic model for evaluation response
 */
export type EvaluationResponse = {
  /**
   * Metrics
   *
   * Evaluation metrics
   */
  metrics: BinaryEvaluation | ContinuousEvaluation;
  /**
   * Benchmarks
   *
   * Evaluation benchmarks
   */
  benchmarks: {
    [key: string]: BinaryEvaluation | ContinuousEvaluation;
  };
};

/**
 * ModelCreate
 *
 * Base Pydantic model for model data
 */
export type ModelCreate = {
  /**
   * Coin Id
   *
   * Coin ID for the model
   */
  coin_id: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';
  /**
   * Target variable for the model
   */
  target: Target;
  /**
   * Name
   *
   * The name of the model.
   */
  name: string;
};

/**
 * ModelRead
 *
 * Pydantic model for model response
 */
export type ModelRead = {
  /**
   * Id
   *
   * Unique model identifier
   */
  id: number;
  /**
   * Name
   *
   * Model name
   */
  name: string;
  /**
   * Coin Id
   *
   * Coin ID
   */
  coin_id: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';
  /**
   * Target variable
   */
  target: Target;
  /**
   * Model status
   */
  status: ModelStatus;
  /**
   * Target Type
   *
   * Target type
   */
  target_type: 'continuous' | 'binary';
  /**
   * Evaluations
   *
   * Model evaluations
   */
  evaluations: Array<Evaluation>;
  /**
   * User Id
   *
   * Developer user ID
   */
  user_id: string;
  /**
   * Created At
   *
   * Model creation unix timestamp
   */
  created_at: number;
  /**
   * Updated At
   *
   * Model update unix timestamp
   */
  updated_at: number;
};

/**
 * ModelStatus
 *
 * Enum for model status
 */
export type ModelStatus = 'created' | 'evaluated';

/**
 * ModelUpdate
 *
 * Pydantic model for model update
 */
export type ModelUpdate = {
  /**
   * Name
   *
   * The name of the model.
   */
  name?: string | null;
};

/**
 * Target
 *
 * AI model prediction targets with obfuscated names for public API access.
 */
export type Target = 'Tatooine' | 'Alderaan' | 'Hoth';

/**
 * TargetInfo
 *
 * Metadata about an AI prediction target including type and version availability.
 */
export type TargetInfo = {
  /**
   * The name of the target.
   */
  name: Target;
  /**
   * Type
   *
   * The type of the target.
   */
  type: 'continuous' | 'binary';
  /**
   * Version Added
   *
   * The data version the target got introduced in.
   */
  version_added: '1.0';
  /**
   * Version Removed
   *
   * The data version the target got removed in. If None, the target is still available.
   */
  version_removed?: '1.0' | null;
};

export type CreateModelData = {
  body: ModelCreate;
  path?: never;
  query?: never;
  url: '/models/creation';
};

export type CreateModelErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type CreateModelError = CreateModelErrors[keyof CreateModelErrors];

export type CreateModelResponses = {
  /**
   * Successful Response
   */
  201: ModelRead;
};

export type CreateModelResponse =
  CreateModelResponses[keyof CreateModelResponses];

export type EvaluateModelData = {
  /**
   * Data
   *
   * Prediction data to evaluate.
   */
  body: Array<unknown>;
  path: {
    /**
     * Id
     *
     * The ID of the model you want to evaluate.
     */
    id: number;
  };
  query?: {
    /**
     * Version
     *
     * Data version for evaluation. Defaults to latest public version. Using older versions won't affect leaderboard rankings but can be useful for additional model testing.
     */
    version?: '1.0' | null;
  };
  url: '/models/evaluation/{id}';
};

export type EvaluateModelErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type EvaluateModelError = EvaluateModelErrors[keyof EvaluateModelErrors];

export type EvaluateModelResponses = {
  /**
   * Successful Response
   */
  200: EvaluationResponse;
};

export type EvaluateModelResponse =
  EvaluateModelResponses[keyof EvaluateModelResponses];

export type DeleteModelData = {
  body?: never;
  path: {
    /**
     * Id
     *
     * The ID of the model to delete.
     */
    id: number;
  };
  query?: never;
  url: '/models/{id}';
};

export type DeleteModelErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DeleteModelError = DeleteModelErrors[keyof DeleteModelErrors];

export type DeleteModelResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteModelResponse =
  DeleteModelResponses[keyof DeleteModelResponses];

export type GetModelData = {
  body?: never;
  path: {
    /**
     * Id
     *
     * The ID of the model to retrieve.
     */
    id: number;
  };
  query?: never;
  url: '/models/{id}';
};

export type GetModelErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetModelError = GetModelErrors[keyof GetModelErrors];

export type GetModelResponses = {
  /**
   * Successful Response
   */
  200: ModelRead;
};

export type GetModelResponse = GetModelResponses[keyof GetModelResponses];

export type UpdateModelData = {
  body: ModelUpdate;
  path: {
    /**
     * Id
     *
     * The ID of the model to update.
     */
    id: number;
  };
  query?: never;
  url: '/models/{id}';
};

export type UpdateModelErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UpdateModelError = UpdateModelErrors[keyof UpdateModelErrors];

export type UpdateModelResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetModelByNameData = {
  body?: never;
  path: {
    /**
     * Name
     *
     * The name of the model to get.
     */
    name: string;
  };
  query?: never;
  url: '/models/by-name/{name}';
};

export type GetModelByNameErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetModelByNameError =
  GetModelByNameErrors[keyof GetModelByNameErrors];

export type GetModelByNameResponses = {
  /**
   * Successful Response
   */
  200: ModelRead;
};

export type GetModelByNameResponse =
  GetModelByNameResponses[keyof GetModelByNameResponses];

export type GetModelsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * By User
     *
     * Whether to get models by a specific user. Else all models are returned.
     */
    by_user?: boolean;
    /**
     * User Id
     *
     * The ID of the user to get models for. Only used if `by_user` is true. Default is current user.
     */
    user_id?: string | null;
  };
  url: '/models';
};

export type GetModelsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetModelsError = GetModelsErrors[keyof GetModelsErrors];

export type GetModelsResponses = {
  /**
   * Response Get Models
   *
   * Successful Response
   */
  200: Array<ModelRead>;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type DownloadDataData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Model Id
     *
     * The ID of the model to download data for.
     */
    model_id: number;
    /**
     * Version
     *
     * The version of the data to download. Default is the latest public version.
     */
    version?: '1.0' | null;
    /**
     * Feature Size
     *
     * The number of features in the data. Default is `LARGE`.
     */
    feature_size?: 'small' | 'medium' | 'large' | null;
  };
  url: '/data';
};

export type DownloadDataErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DownloadDataError = DownloadDataErrors[keyof DownloadDataErrors];

export type DownloadDataResponses = {
  /**
   * Successful Response
   */
  200: DataDownloadResponse;
};

export type DownloadDataResponse =
  DownloadDataResponses[keyof DownloadDataResponses];

export type GetDataInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/data/info';
};

export type GetDataInfoErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetDataInfoError = GetDataInfoErrors[keyof GetDataInfoErrors];

export type GetDataInfoResponses = {
  /**
   * Successful Response
   */
  200: DataInfo;
};

export type GetDataInfoResponse =
  GetDataInfoResponses[keyof GetDataInfoResponses];

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type PingErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type PingError = PingErrors[keyof PingErrors];

export type PingResponses = {
  /**
   * Response Ping
   *
   * Successful Response
   */
  200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/metrics';
};

export type GetMetricsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetMetricsError = GetMetricsErrors[keyof GetMetricsErrors];

export type GetMetricsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
